Continue for-loop, No - before 6 and up.
1
-2
-3
-4
-5
6
7
8
9
10

Continue while-true, No --> before 5 and up.
iteration #0
-->iteration #1
-->iteration #2
-->iteration #3
-->iteration #4
iteration #5
iteration #6
iteration #7
iteration #8
iteration #9

Continue while-false, No - before 3 only.
iteration #10
-iteration #9
-iteration #8
-iteration #7
-iteration #6
-iteration #5
-iteration #4
iteration #3
-iteration #2
-iteration #1
-
Continue times-loop, No ||| before 3.
iteration #0
|||iteration #1
|||iteration #2
iteration #3
|||iteration #4
|||
Test Array each-loop: 0, ... ,2
iteration #0
iteration #2
Test Map each-loop: c only
iterationcthird