(ລາຍຊື່ ໃຫມ່) ໃສ່:['a"b'] ທີ່:['test']
Invalid JSON.
(ລາຍຊື່ ໃຫມ່) ໃສ່:(ຊຸດ ← 1 ; 2 ; (ຊຸດ ← 3 ; 4) ; ((ລາຍຊື່ ໃຫມ່) ໃສ່:(ຊຸດ ← 3 ; 4) ທີ່:['bar'], ໃສ່:1 ທີ່:['foo'])) ທີ່:['nested'], ໃສ່:ບໍ່ ທີ່:['legend'], ໃສ່:27 ທີ່:['age'], ໃສ່:['Jack'] ທີ່:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld