There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. ບໍ່
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is ບໍ່ມີຫຍັງ meters long.
Luckily, this day, there are ບໍ່ມີຫຍັງ wasps in the garden.
The dog named ບໍ່ມີຫຍັງ sleeps under the tree.
a\"bb\"ccc\"
(ລາຍຊື່ ໃຫມ່) ໃສ່:((ລາຍຊື່ ໃຫມ່) ໃສ່:ບໍ່ມີຫຍັງ ທີ່:['dog'], ໃສ່:ບໍ່ມີຫຍັງ ທີ່:['insects'], ໃສ່:((ລາຍຊື່ ໃຫມ່) ໃສ່:15 ທີ່:['length'], ໃສ່:8 ທີ່:['width']) ທີ່:['size'], ໃສ່:(ຊຸດ ← ['tulips'] ; ['roses'] ; ['lillies']) ທີ່:['flower'], ໃສ່:ບໍ່ ທີ່:['shed'], ໃສ່:ໂອເຄ ທີ່:['pool'], ໃສ່:2 ທີ່:['chairs']) ທີ່:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}