(Lethathamo ncha) beha:['a"b'] ka:['test']
Invalid JSON.
(Lethathamo ncha) beha:(Letoto ← 1 ; 2 ; (Letoto ← 3 ; 4) ; ((Lethathamo ncha) beha:(Letoto ← 3 ; 4) ka:['bar'], beha:1 ka:['foo'])) ka:['nested'], beha:Che ka:['legend'], beha:27 ka:['age'], beha:['Jack'] ka:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld