There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Che
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Letho meters long.
Luckily, this day, there are Letho wasps in the garden.
The dog named Letho sleeps under the tree.
a\"bb\"ccc\"
(Lethathamo ncha) beha:((Lethathamo ncha) beha:Letho ka:‘dog’, beha:Letho ka:‘insects’, beha:((Lethathamo ncha) beha:15 ka:‘length’, beha:8 ka:‘width’) ka:‘size’, beha:(Letoto ← ‘tulips’ ; ‘roses’ ; ‘lillies’) ka:‘flower’, beha:Che ka:‘shed’, beha:Ee ka:‘pool’, beha:2 ka:‘chairs’) ka:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}