Ha ho joalo
Ha ho joalo
Boolean
Ke nnete
Boolean
Bohata
Palo
1
Palo
-3
Palo
9,2
Palo
-9,2
Lenane
Lenane ncha 
Lenane
Lenane ← 1 ; 2
Lenane
Lenane ← 1 ; (Lenane ← 2)
Lenane
Lenane ← 1 ; (Lenane ← 2) ; 3
Lenane
Lenane ← 1 ; ((’Mapa ncha) beha:‘a’ ka:‘b’) ; 3
Lenane
Lenane ← 1 ; ((’Mapa ncha) beha:(Lenane ← 9) ka:‘b’) ; 3
’Mapa
(’Mapa ncha) beha:2 ka:‘1’
’Mapa
(’Mapa ncha) beha:2 ka:‘x’
’Mapa
(’Mapa ncha) beha:(Lenane ← 1 ; 2) ka:‘x’
’Mapa
(’Mapa ncha) beha:(Lenane ← ((’Mapa ncha) beha:‘q’ ka:‘y’) ; 2) ka:‘x’
Ha ho joalo
Ha ho joalo
