Tom
Tom
Boolean
Ekte
Boolean
Falsk
Nummer
1
Nummer
-3
Nummer
9,2
Nummer
-9,2
Rekke
Rekke ny 
Rekke
Rekke ← 1 ; 2
Rekke
Rekke ← 1 ; (Rekke ← 2)
Rekke
Rekke ← 1 ; (Rekke ← 2) ; 3
Rekke
Rekke ← 1 ; ((Liste ny) sagt:‘a’ at:‘b’) ; 3
Rekke
Rekke ← 1 ; ((Liste ny) sagt:(Rekke ← 9) at:‘b’) ; 3
Liste
(Liste ny) sagt:2 at:‘1’
Liste
(Liste ny) sagt:2 at:‘x’
Liste
(Liste ny) sagt:(Rekke ← 1 ; 2) at:‘x’
Liste
(Liste ny) sagt:(Rekke ← ((Liste ny) sagt:‘q’ at:‘y’) ; 2) at:‘x’
Tom
Tom