Tom
Tom
Boolean
Ekte
Boolean
Falsk
Tall
1
Tall
-3
Tall
9,2
Tall
-9,2
Rad
Rad ny 
Rad
Rad ← 1 ; 2
Rad
Rad ← 1 ; (Rad ← 2)
Rad
Rad ← 1 ; (Rad ← 2) ; 3
Rad
Rad ← 1 ; ((Liste ny) sagt:['a'] at:['b']) ; 3
Rad
Rad ← 1 ; ((Liste ny) sagt:(Rad ← 9) at:['b']) ; 3
Liste
(Liste ny) sagt:2 at:['1']
Liste
(Liste ny) sagt:2 at:['x']
Liste
(Liste ny) sagt:(Rad ← 1 ; 2) at:['x']
Liste
(Liste ny) sagt:(Rad ← ((Liste ny) sagt:['q'] at:['y']) ; 2) at:['x']
Tom
Tom