LDFLAGS= -shared
CFLAGS= -D WIN

all:libctrpercolator.dll

libctrpercolator.dll: percolator.o
	$(CC) ${LDFLAGS}  percolator.o ../../../ctr${ISO}import.lib -o libctrpercolator.dll

percolator.o:
	$(CC) ${CFLAGS} -I . -c percolator.c -Wall -Werror -fPIC -o percolator.o

clean:
	rm percolator.o
