LDFLAGS= -shared -undefined dynamic_lookup

install-libctrpercolator.dylib: libctrpercolator.dylib
	install libctrpercolator.dylib ../../../bin/Mac/mods/percolator/

libctrpercolator.dylib: percolator.o
	cc ${LDFLAGS} -o libctrpercolator.dylib percolator.o

percolator.o:
	cc -I . -c percolator.c -Wall -Werror -fPIC -o percolator.o

clean:
	rm -rf *.dylib
	rm -rf *.o
