There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Ora
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Boten meters long.
Luckily, this day, there are Boten wasps in the garden.
The dog named Boten sleeps under the tree.
a\"bb\"ccc\"
(Peta anyar) sijine:((Peta anyar) sijine:Boten ing:['dog'], sijine:Boten ing:['insects'], sijine:((Peta anyar) sijine:15 ing:['length'], sijine:8 ing:['width']) ing:['size'], sijine:(Dhaptar ← ['tulips'] ; ['roses'] ; ['lillies']) ing:['flower'], sijine:Ora ing:['shed'], sijine:Ya ing:['pool'], sijine:2 ing:['chairs']) ing:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}