=== Basic test, grab the bottle! ===
>bottle
>bottle
>bottle
>bottle
=== Take a single char ===
>e
>e
=== The 0 case, empty string ===
>
>
=== Edge case, first character only ===
>A
>A
>A
>A
=== Edge case, last character only ===
>.
>.
>.
>.
=== Out of bounds, empty string ===
>
>
>A_
>A
=== Part out of bounds, full string ===
>A_bottle_of_Whisky and a rare steak.
>
>A_bottle_of_Whisky and a rare steak.
>A_bottle_of_Whisky and a rare steak.