(ਨਕਸ਼ਾ ਨਵਾਂ) ਪਾ:['a"b'] ਤੇ:['test']
Invalid JSON.
(ਨਕਸ਼ਾ ਨਵਾਂ) ਪਾ:(ਸੂਚੀ ← 1 ; 2 ; (ਸੂਚੀ ← 3 ; 4) ; ((ਨਕਸ਼ਾ ਨਵਾਂ) ਪਾ:(ਸੂਚੀ ← 3 ; 4) ਤੇ:['bar'], ਪਾ:1 ਤੇ:['foo'])) ਤੇ:['nested'], ਪਾ:ਗਲਤ ਤੇ:['legend'], ਪਾ:27 ਤੇ:['age'], ਪਾ:['Jack'] ਤੇ:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld