(Карта новы) пакласці:‘a"b’ у:‘test’
Invalid JSON.
(Карта новы) пакласці:(Спіс ← 1 ; 2 ; (Спіс ← 3 ; 4) ; ((Карта новы) пакласці:(Спіс ← 3 ; 4) у:‘bar’, пакласці:1 у:‘foo’)) у:‘nested’, пакласці:Ілжывая у:‘legend’, пакласці:27 у:‘age’, пакласці:‘Jack’ у:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld