(Карта новы) пакласці:‘a"b’ _у:‘test’
Invalid JSON.
(Карта новы) пакласці:(Спіс ← 1 ; 2 ; (Спіс ← 3 ; 4) ; ((Карта новы) пакласці:(Спіс ← 3 ; 4) _у:‘bar’, пакласці:1 _у:‘foo’)) _у:‘nested’, пакласці:Ілжывая _у:‘legend’, пакласці:27 _у:‘age’, пакласці:‘Jack’ _у:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
