There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Ілжывая
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Ніль meters long.
Luckily, this day, there are Ніль wasps in the garden.
The dog named Ніль sleeps under the tree.
a\"bb\"ccc\"
(Карта новы) пакласці:((Карта новы) пакласці:Ніль у:‘dog’, пакласці:Ніль у:‘insects’, пакласці:((Карта новы) пакласці:15 у:‘length’, пакласці:8 у:‘width’) у:‘size’, пакласці:(Спіс ← ‘tulips’ ; ‘roses’ ; ‘lillies’) у:‘flower’, пакласці:Ілжывая у:‘shed’, пакласці:Праўда у:‘pool’, пакласці:2 у:‘chairs’) у:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}