(Daftar baru) menempatkan:['a"b'] di:['test']
Invalid JSON.
(Daftar baru) menempatkan:(Seri ← 1 ; 2 ; (Seri ← 3 ; 4) ; ((Daftar baru) menempatkan:(Seri ← 3 ; 4) di:['bar'], menempatkan:1 di:['foo'])) di:['nested'], menempatkan:Salah di:['legend'], menempatkan:27 di:['age'], menempatkan:['Jack'] di:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld