Void
Void
Boolean
Benar
Boolean
Salah
Jumlah
1
Jumlah
-3
Jumlah
9,2
Jumlah
-9,2
Seri
Seri baru 
Seri
Seri ← 1 ; 2
Seri
Seri ← 1 ; (Seri ← 2)
Seri
Seri ← 1 ; (Seri ← 2) ; 3
Seri
Seri ← 1 ; ((Daftar baru) menempatkan:‘a’ di:‘b’) ; 3
Seri
Seri ← 1 ; ((Daftar baru) menempatkan:(Seri ← 9) di:‘b’) ; 3
Daftar
(Daftar baru) menempatkan:2 di:‘1’
Daftar
(Daftar baru) menempatkan:2 di:‘x’
Daftar
(Daftar baru) menempatkan:(Seri ← 1 ; 2) di:‘x’
Daftar
(Daftar baru) menempatkan:(Seri ← ((Daftar baru) menempatkan:‘q’ di:‘y’) ; 2) di:‘x’
Void
Void