Nol
Nol
Boolean
Benar
Boolean
Salah
Jumlah
1
Jumlah
-3
Jumlah
9,2
Jumlah
-9,2
Daftar
Daftar baru 
Daftar
Daftar ← 1 ; 2
Daftar
Daftar ← 1 ; (Daftar ← 2)
Daftar
Daftar ← 1 ; (Daftar ← 2) ; 3
Daftar
Daftar ← 1 ; ((Peta baru) menempatkan:‘a’ di:‘b’) ; 3
Daftar
Daftar ← 1 ; ((Peta baru) menempatkan:(Daftar ← 9) di:‘b’) ; 3
Peta
(Peta baru) menempatkan:2 di:‘1’
Peta
(Peta baru) menempatkan:2 di:‘x’
Peta
(Peta baru) menempatkan:(Daftar ← 1 ; 2) di:‘x’
Peta
(Peta baru) menempatkan:(Daftar ← ((Peta baru) menempatkan:‘q’ di:‘y’) ; 2) di:‘x’
Nol
Nol
