There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Na
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Vala meters long.
Luckily, this day, there are Vala wasps in the garden.
The dog named Vala sleeps under the tree.
a\"bb\"ccc\"
(Lîsteyek nşh) danîn:((Lîsteyek nşh) danîn:Vala li:['dog'], danîn:Vala li:['insects'], danîn:((Lîsteyek nşh) danîn:15 li:['length'], danîn:8 li:['width']) li:['size'], danîn:(Rêzek ← ['tulips'] ; ['roses'] ; ['lillies']) li:['flower'], danîn:Na li:['shed'], danîn:Erê li:['pool'], danîn:2 li:['chairs']) li:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}