Vala
Vala
Erê/Na
Erê
Erê/Na
Na
Jimare
1
Jimare
-3
Jimare
9,2
Jimare
-9,2
Rêzek
Rêzek nşh 
Rêzek
Rêzek ← 1 ; 2
Rêzek
Rêzek ← 1 ; (Rêzek ← 2)
Rêzek
Rêzek ← 1 ; (Rêzek ← 2) ; 3
Rêzek
Rêzek ← 1 ; ((Lîsteyek nşh) danîn:‘a’ li:‘b’) ; 3
Rêzek
Rêzek ← 1 ; ((Lîsteyek nşh) danîn:(Rêzek ← 9) li:‘b’) ; 3
Lîsteyek
(Lîsteyek nşh) danîn:2 li:‘1’
Lîsteyek
(Lîsteyek nşh) danîn:2 li:‘x’
Lîsteyek
(Lîsteyek nşh) danîn:(Rêzek ← 1 ; 2) li:‘x’
Lîsteyek
(Lîsteyek nşh) danîn:(Rêzek ← ((Lîsteyek nşh) danîn:‘q’ li:‘y’) ; 2) li:‘x’
Vala
Vala