There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. şaş
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Qert nşh) danîn:((Qert nşh) danîn:Nil li:‘dog’, danîn:Nil li:‘insects’, danîn:((Qert nşh) danîn:15 li:‘length’, danîn:8 li:‘width’) li:‘size’, danîn:(Rêzok ← ‘tulips’ ; ‘roses’ ; ‘lillies’) li:‘flower’, danîn:şaş li:‘shed’, danîn:Rast li:‘pool’, danîn:2 li:‘chairs’) li:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
