(Lîsteyek nşh) danîn:['a"b'] li:['test']
Invalid JSON.
(Lîsteyek nşh) danîn:(Rêzek ← 1 ; 2 ; (Rêzek ← 3 ; 4) ; ((Lîsteyek nşh) danîn:(Rêzek ← 3 ; 4) li:['bar'], danîn:1 li:['foo'])) li:['nested'], danîn:Na li:['legend'], danîn:27 li:['age'], danîn:['Jack'] li:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld