There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Nu
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Serieă neł) pune:((Serieă neł) pune:Nil la:‘dog’, pune:Nil la:‘insects’, pune:((Serieă neł) pune:15 la:‘length’, pune:8 la:‘width’) la:‘size’, pune:(Serie ← ‘tulips’ ; ‘roses’ ; ‘lillies’) la:‘flower’, pune:Nu la:‘shed’, pune:Da la:‘pool’, pune:2 la:‘chairs’) la:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}