(Serieă neł) pune:['a"b'] la:['test']
Invalid JSON.
(Serieă neł) pune:(Serie ← 1 ; 2 ; (Serie ← 3 ; 4) ; ((Serieă neł) pune:(Serie ← 3 ; 4) la:['bar'], pune:1 la:['foo'])) la:['nested'], pune:Nu la:['legend'], pune:27 la:['age'], pune:['Jack'] la:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld