Nil
Nil
Būlean
Da
Būlean
Nu
Number
1
Number
-3
Number
9,2
Number
-9,2
Serie
Serie neł 
Serie
Serie ← 1 ; 2
Serie
Serie ← 1 ; (Serie ← 2)
Serie
Serie ← 1 ; (Serie ← 2) ; 3
Serie
Serie ← 1 ; ((Serieă neł) pune:‘a’ la:‘b’) ; 3
Serie
Serie ← 1 ; ((Serieă neł) pune:(Serie ← 9) la:‘b’) ; 3
Serieă
(Serieă neł) pune:2 la:‘1’
Serieă
(Serieă neł) pune:2 la:‘x’
Serieă
(Serieă neł) pune:(Serie ← 1 ; 2) la:‘x’
Serieă
(Serieă neł) pune:(Serie ← ((Serieă neł) pune:‘q’ la:‘y’) ; 2) la:‘x’
Nil
Nil