There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. սխալ
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is դատարկ meters long.
Luckily, this day, there are դատարկ wasps in the garden.
The dog named դատարկ sleeps under the tree.
a\"bb\"ccc\"
(ցուցակը նոր) տալ.((ցուցակը նոր) տալ.դատարկ համար.['dog'], տալ.դատարկ համար.['insects'], տալ.((ցուցակը նոր) տալ.15 համար.['length'], տալ.8 համար.['width']) համար.['size'], տալ.(շարքը ← ['tulips'] ; ['roses'] ; ['lillies']) համար.['flower'], տալ.սխալ համար.['shed'], տալ.լավ համար.['pool'], տալ.2 համար.['chairs']) համար.['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}