There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Rangt
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Tómt meters long.
Luckily, this day, there are Tómt wasps in the garden.
The dog named Tómt sleeps under the tree.
a\"bb\"ccc\"
(Listi nýtt) settu:((Listi nýtt) settu:Tómt í:‘dog’, settu:Tómt í:‘insects’, settu:((Listi nýtt) settu:15 í:‘length’, settu:8 í:‘width’) í:‘size’, settu:(Röð ← ‘tulips’ ; ‘roses’ ; ‘lillies’) í:‘flower’, settu:Rangt í:‘shed’, settu:Satt í:‘pool’, settu:2 í:‘chairs’) í:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}