There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Anghywir
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Dim meters long.
Luckily, this day, there are Dim wasps in the garden.
The dog named Dim sleeps under the tree.
a\"bb\"ccc\"
(Map newydd) rhoi:((Map newydd) rhoi:Dim yn:['dog'], rhoi:Dim yn:['insects'], rhoi:((Map newydd) rhoi:15 yn:['length'], rhoi:8 yn:['width']) yn:['size'], rhoi:(Rhestr ← ['tulips'] ; ['roses'] ; ['lillies']) yn:['flower'], rhoi:Anghywir yn:['shed'], rhoi:Gwir yn:['pool'], rhoi:2 yn:['chairs']) yn:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}