There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. ના
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is ખાલી meters long.
Luckily, this day, there are ખાલી wasps in the garden.
The dog named ખાલી sleeps under the tree.
a\"bb\"ccc\"
(યાદી નવું) મૂકો:((યાદી નવું) મૂકો:ખાલી પર:['dog'], મૂકો:ખાલી પર:['insects'], મૂકો:((યાદી નવું) મૂકો:15 પર:['length'], મૂકો:8 પર:['width']) પર:['size'], મૂકો:(કતાર ← ['tulips'] ; ['roses'] ; ['lillies']) પર:['flower'], મૂકો:ના પર:['shed'], મૂકો:હા પર:['pool'], મૂકો:2 પર:['chairs']) પર:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}