(યાદી નવું) મૂકો:['a"b'] પર:['test']
Invalid JSON.
(યાદી નવું) મૂકો:(કતાર ← 1 ; 2 ; (કતાર ← 3 ; 4) ; ((યાદી નવું) મૂકો:(કતાર ← 3 ; 4) પર:['bar'], મૂકો:1 પર:['foo'])) પર:['nested'], મૂકો:ના પર:['legend'], મૂકો:27 પર:['age'], મૂકો:['Jack'] પર:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld