Sending toString to Program yields a PID string:
Nil
Sending toNumber to Program yields a PID number:
0
Sending toString to Dice yields a random number string:
666
Sending toNumber to Dice yields a random number:
666
Sending toString to Clock yields a date and time string:
1666-01-13 06:06:06
Sending toNumber to Clock yields a time stamp number:
999
Sending toString to File yields a path:
[File (no path)]
Sending toNumber to File yields a 1:
1
(Map new) put:(Nil) at:'program', put:(666) at:'dice'
List ← (666) ; (Nil)
