There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Yalan
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Xəritə yeni) qoymaq:((Xəritə yeni) qoymaq:Nil __:dog, qoymaq:Nil __:insects, qoymaq:((Xəritə yeni) qoymaq:15 __:'length', qoymaq:8 __:'width') __:'size', qoymaq:(Siyahı ← 'tulips' ; 'roses' ; 'lillies') __:'flower', qoymaq:Yalan __:'shed', qoymaq:Doğru __:'pool', qoymaq:2 __:'chairs') __:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
