There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falsch
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Null meters long.
Luckily, this day, there are Null wasps in the garden.
The dog named Null sleeps under the tree.
a\"bb\"ccc\"
(Karte neu) put:((Karte neu) put:Null at:dog, put:Null at:insects, put:((Karte neu) put:15 at:‘length’, put:8 at:‘width’) at:‘size’, put:(Aufführen ← ‘tulips’ ; ‘roses’ ; ‘lillies’) at:‘flower’, put:Falsch at:‘shed’, put:Wahr at:‘pool’, put:2 at:‘chairs’) at:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
