There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Salah
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Peta anyar) sijine:((Peta anyar) sijine:Nil ing:dog, sijine:Nil ing:insects, sijine:((Peta anyar) sijine:15 ing:‘length’, sijine:8 ing:‘width’) ing:‘size’, sijine:(Dhaptar ← ‘tulips’ ; ‘roses’ ; ‘lillies’) ing:‘flower’, sijine:Salah ing:‘shed’, sijine:Bener ing:‘pool’, sijine:2 ing:‘chairs’) ing:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
