There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Sese
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Faʻafanua fou) tuʻu:((Faʻafanua fou) tuʻu:Nil _i:dog, tuʻu:Nil _i:insects, tuʻu:((Faʻafanua fou) tuʻu:15 _i:‘length’, tuʻu:8 _i:‘width’) _i:‘size’, tuʻu:(Lisi ← ‘tulips’ ; ‘roses’ ; ‘lillies’) _i:‘flower’, tuʻu:Sese _i:‘shed’, tuʻu:Faamaoni _i:‘pool’, tuʻu:2 _i:‘chairs’) _i:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
