(แผนที่ ใหม่) ใส่:'a"b' ที่:'test'
Invalid JSON.
(แผนที่ ใหม่) ใส่:(รายการ ← 1 ; 2 ; (รายการ ← 3 ; 4) ; ((แผนที่ ใหม่) ใส่:(รายการ ← 3 ; 4) ที่:'bar', ใส่:1 ที่:'foo')) ที่:'nested', ใส่:เท็จ ที่:'legend', ใส่:27 ที่:'age', ใส่:'Jack' ที่:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
