Nil
Nil
Boolean
Kweli
Boolean
Uongo
Nambari
1
Nambari
-3
Nambari
9,2
Nambari
-9,2
Orodha
Orodha mpya 
Orodha
Orodha ← 1 ; 2
Orodha
Orodha ← 1 ; (Orodha ← 2)
Orodha
Orodha ← 1 ; (Orodha ← 2) ; 3
Orodha
Orodha ← 1 ; ((Ramani mpya) weka:‘a’ saa:‘b’) ; 3
Orodha
Orodha ← 1 ; ((Ramani mpya) weka:(Orodha ← 9) saa:‘b’) ; 3
Ramani
(Ramani mpya) weka:2 saa:‘1’
Ramani
(Ramani mpya) weka:2 saa:‘x’
Ramani
(Ramani mpya) weka:(Orodha ← 1 ; 2) saa:‘x’
Ramani
(Ramani mpya) weka:(Orodha ← ((Ramani mpya) weka:‘q’ saa:‘y’) ; 2) saa:‘x’
Nil
Nil
