There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falso
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Mapa novo) poñer:((Mapa novo) poñer:Nil en:dog, poñer:Nil en:insects, poñer:((Mapa novo) poñer:15 en:‘length’, poñer:8 en:‘width’) en:‘size’, poñer:(Lista ← ‘tulips’ ; ‘roses’ ; ‘lillies’) en:‘flower’, poñer:Falso en:‘shed’, poñer:Certo en:‘pool’, poñer:2 en:‘chairs’) en:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
