Neoni
Neoni
Boole
Fìor
Boole
Meallta
Àireamh
1
Àireamh
-3
Àireamh
9,2
Àireamh
-9,2
Liosta
Liosta ùr 
Liosta
Liosta ← 1 ; 2
Liosta
Liosta ← 1 ; (Liosta ← 2)
Liosta
Liosta ← 1 ; (Liosta ← 2) ; 3
Liosta
Liosta ← 1 ; ((Mapa ùr) put:‘a’ aig:‘b’) ; 3
Liosta
Liosta ← 1 ; ((Mapa ùr) put:(Liosta ← 9) aig:‘b’) ; 3
Mapa
(Mapa ùr) put:2 aig:‘1’
Mapa
(Mapa ùr) put:2 aig:‘x’
Mapa
(Mapa ùr) put:(Liosta ← 1 ; 2) aig:‘x’
Mapa
(Mapa ùr) put:(Liosta ← ((Mapa ùr) put:‘q’ aig:‘y’) ; 2) aig:‘x’
Neoni
Neoni
