Nil
Nil
Boolean
Veru
Boolean
Falz
Numru
1
Numru
-3
Numru
9,2
Numru
-9,2
Lista
Lista ġdid 
Lista
Lista ← 1 ; 2
Lista
Lista ← 1 ; (Lista ← 2)
Lista
Lista ← 1 ; (Lista ← 2) ; 3
Lista
Lista ← 1 ; ((Mappa ġdid) tpoġġi:‘a’ fi:‘b’) ; 3
Lista
Lista ← 1 ; ((Mappa ġdid) tpoġġi:(Lista ← 9) fi:‘b’) ; 3
Mappa
(Mappa ġdid) tpoġġi:2 fi:‘1’
Mappa
(Mappa ġdid) tpoġġi:2 fi:‘x’
Mappa
(Mappa ġdid) tpoġġi:(Lista ← 1 ; 2) fi:‘x’
Mappa
(Mappa ġdid) tpoġġi:(Lista ← ((Mappa ġdid) tpoġġi:‘q’ fi:‘y’) ; 2) fi:‘x’
Nil
Nil
