There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Palsu
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Peta anyar) nempatkeun:((Peta anyar) nempatkeun:Nil di:dog, nempatkeun:Nil di:insects, nempatkeun:((Peta anyar) nempatkeun:15 di:‘length’, nempatkeun:8 di:‘width’) di:‘size’, nempatkeun:(Daptar ← ‘tulips’ ; ‘roses’ ; ‘lillies’) di:‘flower’, nempatkeun:Palsu di:‘shed’, nempatkeun:Leres di:‘pool’, nempatkeun:2 di:‘chairs’) di:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
