There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Uongo
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Ramani mpya) weka:((Ramani mpya) weka:Nil saa:dog, weka:Nil saa:insects, weka:((Ramani mpya) weka:15 saa:‘length’, weka:8 saa:‘width’) saa:‘size’, weka:(Orodha ← ‘tulips’ ; ‘roses’ ; ‘lillies’) saa:‘flower’, weka:Uongo saa:‘shed’, weka:Kweli saa:‘pool’, weka:2 saa:‘chairs’) saa:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
