Nil
Nil
Būlean
True
Būlean
False
Number
1
Number
-3
Number
9,2
Number
-9,2
List
List neł 
List
List ← 1 ; 2
List
List ← 1 ; (List ← 2)
List
List ← 1 ; (List ← 2) ; 3
List
List ← 1 ; ((Map neł) put:‘a’ at:‘b’) ; 3
List
List ← 1 ; ((Map neł) put:(List ← 9) at:‘b’) ; 3
Map
(Map neł) put:2 at:‘1’
Map
(Map neł) put:2 at:‘x’
Map
(Map neł) put:(List ← 1 ; 2) at:‘x’
Map
(Map neł) put:(List ← ((Map neł) put:‘q’ at:‘y’) ; 2) at:‘x’
Nil
Nil
