There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Sealňyş
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Karta täze) goý:((Karta täze) goý:Nil at:dog, goý:Nil at:insects, goý:((Karta täze) goý:15 at:'length', goý:8 at:'width') at:'size', goý:(Sanaw ← 'tulips' ; 'roses' ; 'lillies') at:'flower', goý:Sealňyş at:'shed', goý:Dogry at:'pool', goý:2 at:'chairs') at:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
