(Карта ново) стави:'a"b' на:'test'
Invalid JSON.
(Карта ново) стави:(Листа ← 1 ; 2 ; (Листа ← 3 ; 4) ; ((Карта ново) стави:(Листа ← 3 ; 4) на:'bar', стави:1 на:'foo')) на:'nested', стави:Лажни на:'legend', стави:27 на:'age', стави:'Jack' на:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
