Null
Null
Boolean
Tõsi
Boolean
Vale
Arv
1
Arv
-3
Arv
9,2
Arv
-9,2
Loend
Loend uus 
Loend
Loend ← 1 ; 2
Loend
Loend ← 1 ; (Loend ← 2)
Loend
Loend ← 1 ; (Loend ← 2) ; 3
Loend
Loend ← 1 ; ((Kaart uus) panna:‘a’ juures:‘b’) ; 3
Loend
Loend ← 1 ; ((Kaart uus) panna:(Loend ← 9) juures:‘b’) ; 3
Kaart
(Kaart uus) panna:2 juures:‘1’
Kaart
(Kaart uus) panna:2 juures:‘x’
Kaart
(Kaart uus) panna:(Loend ← 1 ; 2) juures:‘x’
Kaart
(Kaart uus) panna:(Loend ← ((Kaart uus) panna:‘q’ juures:‘y’) ; 2) juures:‘x’
Null
Null
