There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falso
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nada meters long.
Luckily, this day, there are Nada wasps in the garden.
The dog named Nada sleeps under the tree.
a\"bb\"ccc\"
(Mapa novo) coloque em:((Mapa novo) coloque em:Nada __:dog, coloque em:Nada __:insects, coloque em:((Mapa novo) coloque em:15 __:‘length’, coloque em:8 __:‘width’) __:‘size’, coloque em:(Lista ← ‘tulips’ ; ‘roses’ ; ‘lillies’) __:‘flower’, coloque em:Falso __:‘shed’, coloque em:Verdade __:‘pool’, coloque em:2 __:‘chairs’) __:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
