There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Lažno
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Zemljevid novo) dal:((Zemljevid novo) dal:Nil na:‘dog’, dal:Nil na:‘insects’, dal:((Zemljevid novo) dal:15 na:‘length’, dal:8 na:‘width’) na:‘size’, dal:(Seznam ← ‘tulips’ ; ‘roses’ ; ‘lillies’) na:‘flower’, dal:Lažno na:‘shed’, dal:Prav na:‘pool’, dal:2 na:‘chairs’) na:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
