Nil
Nil
Faʻamalie
Faamaoni
Faʻamalie
Sese
Numera
1
Numera
-3
Numera
9,2
Numera
-9,2
Lisi
Lisi fou 
Lisi
Lisi ← 1 ; 2
Lisi
Lisi ← 1 ; (Lisi ← 2)
Lisi
Lisi ← 1 ; (Lisi ← 2) ; 3
Lisi
Lisi ← 1 ; ((Faʻafanua fou) tuʻu:‘a’ _i:‘b’) ; 3
Lisi
Lisi ← 1 ; ((Faʻafanua fou) tuʻu:(Lisi ← 9) _i:‘b’) ; 3
Faʻafanua
(Faʻafanua fou) tuʻu:2 _i:‘1’
Faʻafanua
(Faʻafanua fou) tuʻu:2 _i:‘x’
Faʻafanua
(Faʻafanua fou) tuʻu:(Lisi ← 1 ; 2) _i:‘x’
Faʻafanua
(Faʻafanua fou) tuʻu:(Lisi ← ((Faʻafanua fou) tuʻu:‘q’ _i:‘y’) ; 2) _i:‘x’
Nil
Nil
