There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Nhema
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Mepu nyowani) isa:((Mepu nyowani) isa:Nil pa:‘dog’, isa:Nil pa:‘insects’, isa:((Mepu nyowani) isa:15 pa:‘length’, isa:8 pa:‘width’) pa:‘size’, isa:(Rondedzero ← ‘tulips’ ; ‘roses’ ; ‘lillies’) pa:‘flower’, isa:Nhema pa:‘shed’, isa:Chokwadi pa:‘pool’, isa:2 pa:‘chairs’) pa:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
