(Map vaovao) hametraka:'a"b' amin’ny:'test'
Invalid JSON.
(Map vaovao) hametraka:(List ← 1 ; 2 ; (List ← 3 ; 4) ; ((Map vaovao) hametraka:(List ← 3 ; 4) amin’ny:'bar', hametraka:1 amin’ny:'foo')) amin’ny:'nested', hametraka:Diso amin’ny:'legend', hametraka:27 amin’ny:'age', hametraka:'Jack' amin’ny:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
