Nula
Nula
Boolean
Skutečný
Boolean
Nepravdivé
Číslo
1
Číslo
-3
Číslo
9,2
Číslo
-9,2
Seznam
Seznam nový 
Seznam
Seznam ← 1 ; 2
Seznam
Seznam ← 1 ; (Seznam ← 2)
Seznam
Seznam ← 1 ; (Seznam ← 2) ; 3
Seznam
Seznam ← 1 ; ((Mapa nový) dát:‘a’ na:‘b’) ; 3
Seznam
Seznam ← 1 ; ((Mapa nový) dát:(Seznam ← 9) na:‘b’) ; 3
Mapa
(Mapa nový) dát:2 na:‘1’
Mapa
(Mapa nový) dát:2 na:‘x’
Mapa
(Mapa nový) dát:(Seznam ← 1 ; 2) na:‘x’
Mapa
(Mapa nový) dát:(Seznam ← ((Mapa nový) dát:‘q’ na:‘y’) ; 2) na:‘x’
Nula
Nula
