(Xəritə yeni) qoymaq:‘a"b’ __:‘test’
Invalid JSON.
(Xəritə yeni) qoymaq:(Siyahı ← 1 ; 2 ; (Siyahı ← 3 ; 4) ; ((Xəritə yeni) qoymaq:(Siyahı ← 3 ; 4) __:‘bar’, qoymaq:1 __:‘foo’)) __:‘nested’, qoymaq:Yalan __:‘legend’, qoymaq:27 __:‘age’, qoymaq:‘Jack’ __:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
