There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. False
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(карта жаңы) койду эле:((карта жаңы) койду эле:Nil __:dog, койду эле:Nil __:insects, койду эле:((карта жаңы) койду эле:15 __:‘length’, койду эле:8 __:‘width’) __:‘size’, койду эле:(тизме ← ‘tulips’ ; ‘roses’ ; ‘lillies’) __:‘flower’, койду эле:False __:‘shed’, койду эле:True __:‘pool’, койду эле:2 __:‘chairs’) __:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
