(Mappa novu) mette:'a"b' _à:'test'
Invalid JSON.
(Mappa novu) mette:(Elencu ← 1 ; 2 ; (Elencu ← 3 ; 4) ; ((Mappa novu) mette:(Elencu ← 3 ; 4) _à:'bar', mette:1 _à:'foo')) _à:'nested', mette:False _à:'legend', mette:27 _à:'age', mette:'Jack' _à:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
