Nil
Nil
Boolean
Rigtigt
Boolean
Falsk
Nummer
1
Nummer
-3
Nummer
9,2
Nummer
-9,2
Liste
Liste ny 
Liste
Liste ← 1 ; 2
Liste
Liste ← 1 ; (Liste ← 2)
Liste
Liste ← 1 ; (Liste ← 2) ; 3
Liste
Liste ← 1 ; ((Kort ny) sætte:‘a’ på:‘b’) ; 3
Liste
Liste ← 1 ; ((Kort ny) sætte:(Liste ← 9) på:‘b’) ; 3
Kort
(Kort ny) sætte:2 på:‘1’
Kort
(Kort ny) sætte:2 på:‘x’
Kort
(Kort ny) sætte:(Liste ← 1 ; 2) på:‘x’
Kort
(Kort ny) sætte:(Liste ← ((Kort ny) sætte:‘q’ på:‘y’) ; 2) på:‘x’
Nil
Nil
