There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. 그릇된
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is _무 meters long.
Luckily, this day, there are _무 wasps in the garden.
The dog named _무 sleeps under the tree.
a\"bb\"ccc\"
(지도 새로운) 넣어 :((지도 새로운) 넣어 :_무 at :dog, 넣어 :_무 at :insects, 넣어 :((지도 새로운) 넣어 :15 at :'length', 넣어 :8 at :'width') at :'size', 넣어 :(명부 ← 'tulips' ; 'roses' ; 'lillies') at :'flower', 넣어 :그릇된 at :'shed', 넣어 :진실 at :'pool', 넣어 :2 at :'chairs') at :'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
