(Taswira sabo) sanya:‘a"b’ _a:‘test’
Invalid JSON.
(Taswira sabo) sanya:(Lissafi ← 1 ; 2 ; (Lissafi ← 3 ; 4) ; ((Taswira sabo) sanya:(Lissafi ← 3 ; 4) _a:‘bar’, sanya:1 _a:‘foo’)) _a:‘nested’, sanya:Karya _a:‘legend’, sanya:27 _a:‘age’, sanya:‘Jack’ _a:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
