(Mapa nou) posar:'a"b' _a:'test'
Invalid JSON.
(Mapa nou) posar:(Llista ← 1 ; 2 ; (Llista ← 3 ; 4) ; ((Mapa nou) posar:(Llista ← 3 ; 4) _a:'bar', posar:1 _a:'foo')) _a:'nested', posar:Fals _a:'legend', posar:27 _a:'age', posar:'Jack' _a:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
