There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Bakak
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Mapa bag-o nga) gibutang:((Mapa bag-o nga) gibutang:Nil sa:‘dog’, gibutang:Nil sa:‘insects’, gibutang:((Mapa bag-o nga) gibutang:15 sa:‘length’, gibutang:8 sa:‘width’) sa:‘size’, gibutang:(Paglista ← ‘tulips’ ; ‘roses’ ; ‘lillies’) sa:‘flower’, gibutang:Bakak sa:‘shed’, gibutang:Tinuod sa:‘pool’, gibutang:2 sa:‘chairs’) sa:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
