There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Nepravdivý
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nula meters long.
Luckily, this day, there are Nula wasps in the garden.
The dog named Nula sleeps under the tree.
a\"bb\"ccc\"
(Mapa nový) povedané:((Mapa nový) povedané:Nula na adrese:dog, povedané:Nula na adrese:insects, povedané:((Mapa nový) povedané:15 na adrese:'length', povedané:8 na adrese:'width') na adrese:'size', povedané:(Zoznam ← 'tulips' ; 'roses' ; 'lillies') na adrese:'flower', povedané:Nepravdivý na adrese:'shed', povedané:Pravdivý na adrese:'pool', povedané:2 na adrese:'chairs') na adrese:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
