There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Mali
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Map bago) ilagay:((Map bago) ilagay:Nil sa:dog, ilagay:Nil sa:insects, ilagay:((Map bago) ilagay:15 sa:‘length’, ilagay:8 sa:‘width’) sa:‘size’, ilagay:(Listahan ← ‘tulips’ ; ‘roses’ ; ‘lillies’) sa:‘flower’, ilagay:Mali sa:‘shed’, ilagay:Totoo sa:‘pool’, ilagay:2 sa:‘chairs’) sa:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
