(Lĳst nieuw) zet:'a"b' bĳ:'test'
Invalid JSON.
(Lĳst nieuw) zet:(Reeks ← 1 ; 2 ; (Reeks ← 3 ; 4) ; ((Lĳst nieuw) zet:(Reeks ← 3 ; 4) bĳ:'bar', zet:1 bĳ:'foo')) bĳ:'nested', zet:Onwaar bĳ:'legend', zet:27 bĳ:'age', zet:'Jack' bĳ:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
