There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Hamis
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nulla meters long.
Luckily, this day, there are Nulla wasps in the garden.
The dog named Nulla sleeps under the tree.
a\"bb\"ccc\"
(Térkép új) magyarán:((Térkép új) magyarán:Nulla itt:dog, magyarán:Nulla itt:insects, magyarán:((Térkép új) magyarán:15 itt:'length', magyarán:8 itt:'width') itt:'size', magyarán:(Lista ← 'tulips' ; 'roses' ; 'lillies') itt:'flower', magyarán:Hamis itt:'shed', magyarán:Igaz itt:'pool', magyarán:2 itt:'chairs') itt:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
