There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falsch
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Null meters long.
Luckily, this day, there are Null wasps in the garden.
The dog named Null sleeps under the tree.
a\"bb\"ccc\"
(Kaart nei) setzen:((Kaart nei) setzen:Null bei:dog, setzen:Null bei:insects, setzen:((Kaart nei) setzen:15 bei:‘length’, setzen:8 bei:‘width’) bei:‘size’, setzen:(Lëscht ← ‘tulips’ ; ‘roses’ ; ‘lillies’) bei:‘flower’, setzen:Falsch bei:‘shed’, setzen:Richteg bei:‘pool’, setzen:2 bei:‘chairs’) bei:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
