There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. ບໍ່ຖືກຕ້ອງ
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is _ນ meters long.
Luckily, this day, there are _ນ wasps in the garden.
The dog named _ນ sleeps under the tree.
a\"bb\"ccc\"
(ແຜນທີ່ ໃຫມ່) ໃສ່:((ແຜນທີ່ ໃຫມ່) ໃສ່:_ນ ທີ່:‘dog’, ໃສ່:_ນ ທີ່:‘insects’, ໃສ່:((ແຜນທີ່ ໃຫມ່) ໃສ່:15 ທີ່:‘length’, ໃສ່:8 ທີ່:‘width’) ທີ່:‘size’, ໃສ່:(ລາຍຊື່ ← ‘tulips’ ; ‘roses’ ; ‘lillies’) ທີ່:‘flower’, ໃສ່:ບໍ່ຖືກຕ້ອງ ທີ່:‘shed’, ໃສ່:ຖືກຕ້ອງ ທີ່:‘pool’, ໃສ່:2 ທີ່:‘chairs’) ທີ່:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
