There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Lažan
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nula meters long.
Luckily, this day, there are Nula wasps in the garden.
The dog named Nula sleeps under the tree.
a\"bb\"ccc\"
(Karta novi) staviti:((Karta novi) staviti:Nula na:dog, staviti:Nula na:insects, staviti:((Karta novi) staviti:15 na:'length', staviti:8 na:'width') na:'size', staviti:(Popis ← 'tulips' ; 'roses' ; 'lillies') na:'flower', staviti:Lažan na:'shed', staviti:Pravi na:'pool', staviti:2 na:'chairs') na:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
