(نقشه نوی) لګول:'a"b' په:'test'
Invalid JSON.
(نقشه نوی) لګول:(لیست ← 1 ; 2 ; (لیست ← 3 ; 4) ; ((نقشه نوی) لګول:(لیست ← 3 ; 4) په:'bar', لګول:1 په:'foo')) په:'nested', لګول:غلط په:'legend', لګول:27 په:'age', لګول:'Jack' په:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
