(地図 新着) put：at：__:'a"b' __:'test'
Invalid JSON.
(地図 新着) put：at：__:(リスト ← 1 ; 2 ; (リスト ← 3 ; 4) ; ((地図 新着) put：at：__:(リスト ← 3 ; 4) __:'bar', put：at：__:1 __:'foo')) __:'nested', put：at：__:誤り __:'legend', put：at：__:27 __:'age', put：at：__:'Jack' __:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
