(Lijst nieuw) zet:'a"b' bij:'test'
(Lijst nieuw) zet:(Reeks ← 1 ; 2 ; (Reeks ← 3 ; 4) ; ((Lijst nieuw) zet:Niets bij:Reeks ← 3 ; 4, zet:1 bij:'foo')) bij:'nested', zet:Onwaar bij:'legend', zet:27 bij:'age', zet:'Jack' bij:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
