There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Tsis tseeb
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Daim ntawv qhia tshiab) muab:((Daim ntawv qhia tshiab) muab:Nil rau:dog, muab:Nil rau:insects, muab:((Daim ntawv qhia tshiab) muab:15 rau:'length', muab:8 rau:'width') rau:'size', muab:(Sau ← 'tulips' ; 'roses' ; 'lillies') rau:'flower', muab:Tsis tseeb rau:'shed', muab:Muaj tseeb rau:'pool', muab:2 rau:'chairs') rau:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
