There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Yanlış
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Sıfır meters long.
Luckily, this day, there are Sıfır wasps in the garden.
The dog named Sıfır sleeps under the tree.
a\"bb\"ccc\"
(Harita yeni) koyun:((Harita yeni) koyun:Sıfır at:dog, koyun:Sıfır at:insects, koyun:((Harita yeni) koyun:15 at:‘length’, koyun:8 at:‘width’) at:‘size’, koyun:(Liste ← ‘tulips’ ; ‘roses’ ; ‘lillies’) at:‘flower’, koyun:Yanlış at:‘shed’, koyun:Doğru at:‘pool’, koyun:2 at:‘chairs’) at:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
