There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Meallta
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Neoni meters long.
Luckily, this day, there are Neoni wasps in the garden.
The dog named Neoni sleeps under the tree.
a\"bb\"ccc\"
(Mapa ùr) put:((Mapa ùr) put:Neoni aig:dog, put:Neoni aig:insects, put:((Mapa ùr) put:15 aig:'length', put:8 aig:'width') aig:'size', put:(Liosta ← 'tulips' ; 'roses' ; 'lillies') aig:'flower', put:Meallta aig:'shed', put:Fìor aig:'pool', put:2 aig:'chairs') aig:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
