(Karta täze) goý:‘a"b’ at:‘test’
Invalid JSON.
(Karta täze) goý:(Sanaw ← 1 ; 2 ; (Sanaw ← 3 ; 4) ; ((Karta täze) goý:(Sanaw ← 3 ; 4) at:‘bar’, goý:1 at:‘foo’)) at:‘nested’, goý:Sealňyş at:‘legend’, goý:27 at:‘age’, goý:‘Jack’ at:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
