There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Ялган
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Нил meters long.
Luckily, this day, there are Нил wasps in the garden.
The dog named Нил sleeps under the tree.
a\"bb\"ccc\"
(Карта яңа) куярга:((Карта яңа) куярга:Нил at:‘dog’, куярга:Нил at:‘insects’, куярга:((Карта яңа) куярга:15 at:‘length’, куярга:8 at:‘width’) at:‘size’, куярга:(Исемлек ← ‘tulips’ ; ‘roses’ ; ‘lillies’) at:‘flower’, куярга:Ялган at:‘shed’, куярга:Дөрес at:‘pool’, куярга:2 at:‘chairs’) at:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
