There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. අසත්‍යය
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is නිල් meters long.
Luckily, this day, there are නිල් wasps in the garden.
The dog named නිල් sleeps under the tree.
a\"bb\"ccc\"
(සිතියම නව) put:((සිතියම නව) put:නිල් at:dog, put:නිල් at:insects, put:((සිතියම නව) put:15 at:'length', put:8 at:'width') at:'size', put:(ලැයිස්තුව ← 'tulips' ; 'roses' ; 'lillies') at:'flower', put:අසත්‍යය at:'shed', put:සැබෑ at:'pool', put:2 at:'chairs') at:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
