There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Nepravdivé
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nula meters long.
Luckily, this day, there are Nula wasps in the garden.
The dog named Nula sleeps under the tree.
a\"bb\"ccc\"
(Mapa nový) dát:((Mapa nový) dát:Nula na:dog, dát:Nula na:insects, dát:((Mapa nový) dát:15 na:'length', dát:8 na:'width') na:'size', dát:(Seznam ← 'tulips' ; 'roses' ; 'lillies') na:'flower', dát:Nepravdivé na:'shed', dát:Skutečný na:'pool', dát:2 na:'chairs') na:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
