There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falsk
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Kart ny) sagt:((Kart ny) sagt:Nil at:dog, sagt:Nil at:insects, sagt:((Kart ny) sagt:15 at:‘length’, sagt:8 at:‘width’) at:‘size’, sagt:(Liste ← ‘tulips’ ; ‘roses’ ; ‘lillies’) at:‘flower’, sagt:Falsk at:‘shed’, sagt:Ekte at:‘pool’, sagt:2 at:‘chairs’) at:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
