There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. பொய்
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is இல்லை meters long.
Luckily, this day, there are இல்லை wasps in the garden.
The dog named இல்லை sleeps under the tree.
a\"bb\"ccc\"
(வரைபடம் புதியது) put:((வரைபடம் புதியது) put:இல்லை at:dog, put:இல்லை at:insects, put:((வரைபடம் புதியது) put:15 at:‘length’, put:8 at:‘width’) at:‘size’, put:(பட்டியல் ← ‘tulips’ ; ‘roses’ ; ‘lillies’) at:‘flower’, put:பொய் at:‘shed’, put:உண்மை at:‘pool’, put:2 at:‘chairs’) at:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
