There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Nee
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Niets meters long.
Luckily, this day, there are Niets wasps in the garden.
The dog named Niets sleeps under the tree.
a\"bb\"ccc\"
(Lĳst nieuw) zet:((Lĳst nieuw) zet:Niets bĳ:“dog”, zet:Niets bĳ:“insects”, zet:((Lĳst nieuw) zet:15 bĳ:“length”, zet:8 bĳ:“width”) bĳ:“size”, zet:(Reeks ← “tulips” ; “roses” ; “lillies”) bĳ:“flower”, zet:Nee bĳ:“shed”, zet:Ja bĳ:“pool”, zet:2 bĳ:“chairs”) bĳ:“garden”
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
