There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. ತಪ್ಪು
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is ನಿಲ್ meters long.
Luckily, this day, there are ನಿಲ್ wasps in the garden.
The dog named ನಿಲ್ sleeps under the tree.
a\"bb\"ccc\"
(ನಕ್ಷೆ ಹೊಸದು) ಪುಟ್:((ನಕ್ಷೆ ಹೊಸದು) ಪುಟ್:ನಿಲ್ ನಲ್ಲಿ:dog, ಪುಟ್:ನಿಲ್ ನಲ್ಲಿ:insects, ಪುಟ್:((ನಕ್ಷೆ ಹೊಸದು) ಪುಟ್:15 ನಲ್ಲಿ:'length', ಪುಟ್:8 ನಲ್ಲಿ:'width') ನಲ್ಲಿ:'size', ಪುಟ್:(ಪಟ್ಟಿ ← 'tulips' ; 'roses' ; 'lillies') ನಲ್ಲಿ:'flower', ಪುಟ್:ತಪ್ಪು ನಲ್ಲಿ:'shed', ಪುಟ್:ನಿಜ ನಲ್ಲಿ:'pool', ಪುಟ್:2 ನಲ್ಲಿ:'chairs') ನಲ್ಲಿ:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
