Zero
Zero
Booleano
Vero
Booleano
Falso
Numero
1
Numero
-3
Numero
9,2
Numero
-9,2
Elenco
Elenco nuovo 
Elenco
Elenco ← 1 ; 2
Elenco
Elenco ← 1 ; (Elenco ← 2)
Elenco
Elenco ← 1 ; (Elenco ← 2) ; 3
Elenco
Elenco ← 1 ; ((Carta geografica nuovo) mettere:‘a’ _a:‘b’) ; 3
Elenco
Elenco ← 1 ; ((Carta geografica nuovo) mettere:(Elenco ← 9) _a:‘b’) ; 3
Carta geografica
(Carta geografica nuovo) mettere:2 _a:‘1’
Carta geografica
(Carta geografica nuovo) mettere:2 _a:‘x’
Carta geografica
(Carta geografica nuovo) mettere:(Elenco ← 1 ; 2) _a:‘x’
Carta geografica
(Carta geografica nuovo) mettere:(Elenco ← ((Carta geografica nuovo) mettere:‘q’ _a:‘y’) ; 2) _a:‘x’
Zero
Zero
