There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falso
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nulo meters long.
Luckily, this day, there are Nulo wasps in the garden.
The dog named Nulo sleeps under the tree.
a\"bb\"ccc\"
(Mapa nuevo) ponlo en:((Mapa nuevo) ponlo en:Nulo __:‘dog’, ponlo en:Nulo __:‘insects’, ponlo en:((Mapa nuevo) ponlo en:15 __:‘length’, ponlo en:8 __:‘width’) __:‘size’, ponlo en:(Lista ← ‘tulips’ ; ‘roses’ ; ‘lillies’) __:‘flower’, ponlo en:Falso __:‘shed’, ponlo en:Cierto __:‘pool’, ponlo en:2 __:‘chairs’) __:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
