There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. False
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Mappa novu) mette:((Mappa novu) mette:Nil _à:‘dog’, mette:Nil _à:‘insects’, mette:((Mappa novu) mette:15 _à:‘length’, mette:8 _à:‘width’) _à:‘size’, mette:(Elencu ← ‘tulips’ ; ‘roses’ ; ‘lillies’) _à:‘flower’, mette:False _à:‘shed’, mette:Hè vera _à:‘pool’, mette:2 _à:‘chairs’) _à:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
