There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. မှား
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(မြေပုံ အသစ်) ထား:((မြေပုံ အသစ်) ထား:Nil မှာ:dog, ထား:Nil မှာ:insects, ထား:((မြေပုံ အသစ်) ထား:15 မှာ:'length', ထား:8 မှာ:'width') မှာ:'size', ထား:(စာရင်း ← 'tulips' ; 'roses' ; 'lillies') မှာ:'flower', ထား:မှား မှာ:'shed', ထား:မှန်ပါတယ် မှာ:'pool', ထား:2 မှာ:'chairs') မှာ:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
