There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Gha
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Maapụ ohuru) tinye:((Maapụ ohuru) tinye:Nil na:dog, tinye:Nil na:insects, tinye:((Maapụ ohuru) tinye:15 na:'length', tinye:8 na:'width') na:'size', tinye:(Ndepụta ← 'tulips' ; 'roses' ; 'lillies') na:'flower', tinye:Gha na:'shed', tinye:Eziokwu na:'pool', tinye:2 na:'chairs') na:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
