(Peta anyar) nempatkeun:'a"b' di:'test'
Invalid JSON.
(Peta anyar) nempatkeun:(Daptar ← 1 ; 2 ; (Daptar ← 3 ; 4) ; ((Peta anyar) nempatkeun:(Daptar ← 3 ; 4) di:'bar', nempatkeun:1 di:'foo')) di:'nested', nempatkeun:Palsu di:'legend', nempatkeun:27 di:'age', nempatkeun:'Jack' di:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
