(Мапа Нова) пут:‘a"b’ ат:‘test’
Invalid JSON.
(Мапа Нова) пут:(Листа ← 1 ; 2 ; (Листа ← 3 ; 4) ; ((Мапа Нова) пут:(Листа ← 3 ; 4) ат:‘bar’, пут:1 ат:‘foo’)) ат:‘nested’, пут:Лажно ат:‘legend’, пут:27 ат:‘age’, пут:‘Jack’ ат:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
