Null
Null
Boolschen
Richteg
Boolschen
Falsch
Zuel
1
Zuel
-3
Zuel
9,2
Zuel
-9,2
Lëscht
Lëscht nei 
Lëscht
Lëscht ← 1 ; 2
Lëscht
Lëscht ← 1 ; (Lëscht ← 2)
Lëscht
Lëscht ← 1 ; (Lëscht ← 2) ; 3
Lëscht
Lëscht ← 1 ; ((Kaart nei) setzen:‘a’ bei:‘b’) ; 3
Lëscht
Lëscht ← 1 ; ((Kaart nei) setzen:(Lëscht ← 9) bei:‘b’) ; 3
Kaart
(Kaart nei) setzen:2 bei:‘1’
Kaart
(Kaart nei) setzen:2 bei:‘x’
Kaart
(Kaart nei) setzen:(Lëscht ← 1 ; 2) bei:‘x’
Kaart
(Kaart nei) setzen:(Lëscht ← ((Kaart nei) setzen:‘q’ bei:‘y’) ; 2) bei:‘x’
Null
Null
