There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Бардурӯғ
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Нил meters long.
Luckily, this day, there are Нил wasps in the garden.
The dog named Нил sleeps under the tree.
a\"bb\"ccc\"
(Харитаи нав) гузошта:((Харитаи нав) гузошта:Нил дар:dog, гузошта:Нил дар:insects, гузошта:((Харитаи нав) гузошта:15 дар:‘length’, гузошта:8 дар:‘width’) дар:‘size’, гузошта:(Рӯйхат ← ‘tulips’ ; ‘roses’ ; ‘lillies’) дар:‘flower’, гузошта:Бардурӯғ дар:‘shed’, гузошта:Дуруст аст дар:‘pool’, гузошта:2 дар:‘chairs’) дар:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
