There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Կեղծ
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Զրո meters long.
Luckily, this day, there are Զրո wasps in the garden.
The dog named Զրո sleeps under the tree.
a\"bb\"ccc\"
(Քարտեզ նոր) տեղադրել:((Քարտեզ նոր) տեղադրել:Զրո at:dog, տեղադրել:Զրո at:insects, տեղադրել:((Քարտեզ նոր) տեղադրել:15 at:‘length’, տեղադրել:8 at:‘width’) at:‘size’, տեղադրել:(Ցուցակ ← ‘tulips’ ; ‘roses’ ; ‘lillies’) at:‘flower’, տեղադրել:Կեղծ at:‘shed’, տեղադրել:Ճիշտ at:‘pool’, տեղադրել:2 at:‘chairs’) at:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
