There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. ყალბი
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is ნილ meters long.
Luckily, this day, there are ნილ wasps in the garden.
The dog named ნილ sleeps under the tree.
a\"bb\"ccc\"
(რუქა ახალი) დააყენა:((რუქა ახალი) დააყენა:ნილ at:dog, დააყენა:ნილ at:insects, დააყენა:((რუქა ახალი) დააყენა:15 at:‘length’, დააყენა:8 at:‘width’) at:‘size’, დააყენა:(ჩამოთვლა ← ‘tulips’ ; ‘roses’ ; ‘lillies’) at:‘flower’, დააყენა:ყალბი at:‘shed’, დააყენა:მართალია at:‘pool’, დააყენა:2 at:‘chairs’) at:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
