There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Lažno
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Mapa novo) put:((Mapa novo) put:Nil at:dog, put:Nil at:insects, put:((Mapa novo) put:15 at:'length', put:8 at:'width') at:'size', put:(Lista ← 'tulips' ; 'roses' ; 'lillies') at:'flower', put:Lažno at:'shed', put:Istinito at:'pool', put:2 at:'chairs') at:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
