Nil
Nil
Boolean
Bener
Boolean
Salah
Nomer
1
Nomer
-3
Nomer
9,2
Nomer
-9,2
Dhaptar
Dhaptar anyar 
Dhaptar
Dhaptar ← 1 ; 2
Dhaptar
Dhaptar ← 1 ; (Dhaptar ← 2)
Dhaptar
Dhaptar ← 1 ; (Dhaptar ← 2) ; 3
Dhaptar
Dhaptar ← 1 ; ((Peta anyar) sijine:‘a’ ing:‘b’) ; 3
Dhaptar
Dhaptar ← 1 ; ((Peta anyar) sijine:(Dhaptar ← 9) ing:‘b’) ; 3
Peta
(Peta anyar) sijine:2 ing:‘1’
Peta
(Peta anyar) sijine:2 ing:‘x’
Peta
(Peta anyar) sijine:(Dhaptar ← 1 ; 2) ing:‘x’
Peta
(Peta anyar) sijine:(Dhaptar ← ((Peta anyar) sijine:‘q’ ing:‘y’) ; 2) ing:‘x’
Nil
Nil
