There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Жалған
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Нил meters long.
Luckily, this day, there are Нил wasps in the garden.
The dog named Нил sleeps under the tree.
a\"bb\"ccc\"
(Карта жаңа) қою:((Карта жаңа) қою:Нил __:‘dog’, қою:Нил __:‘insects’, қою:((Карта жаңа) қою:15 __:‘length’, қою:8 __:‘width’) __:‘size’, қою:(Тізім ← ‘tulips’ ; ‘roses’ ; ‘lillies’) __:‘flower’, қою:Жалған __:‘shed’, қою:Рас __:‘pool’, қою:2 __:‘chairs’) __:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
