There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Fałszywy
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Zero meters long.
Luckily, this day, there are Zero wasps in the garden.
The dog named Zero sleeps under the tree.
a\"bb\"ccc\"
(Mapa nowy) położyć na coś:((Mapa nowy) położyć na coś:Zero __:dog, położyć na coś:Zero __:insects, położyć na coś:((Mapa nowy) położyć na coś:15 __:‘length’, położyć na coś:8 __:‘width’) __:‘size’, położyć na coś:(Lista ← ‘tulips’ ; ‘roses’ ; ‘lillies’) __:‘flower’, położyć na coś:Fałszywy __:‘shed’, położyć na coś:Prawdziwe __:‘pool’, położyć na coś:2 __:‘chairs’) __:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
