(Mappa ġdid) tpoġġi:'a"b' fi:'test'
Invalid JSON.
(Mappa ġdid) tpoġġi:(Lista ← 1 ; 2 ; (Lista ← 3 ; 4) ; ((Mappa ġdid) tpoġġi:(Lista ← 3 ; 4) fi:'bar', tpoġġi:1 fi:'foo')) fi:'nested', tpoġġi:Falz fi:'legend', tpoġġi:27 fi:'age', tpoġġi:'Jack' fi:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
