Nul
Nul
Boolean
Wier
Boolean
Falsk
Nûmer
1
Nûmer
-3
Nûmer
9,2
Nûmer
-9,2
List
List nij 
List
List ← 1 ; 2
List
List ← 1 ; (List ← 2)
List
List ← 1 ; (List ← 2) ; 3
List
List ← 1 ; ((Kaart nij) put:‘a’ at:‘b’) ; 3
List
List ← 1 ; ((Kaart nij) put:(List ← 9) at:‘b’) ; 3
Kaart
(Kaart nij) put:2 at:‘1’
Kaart
(Kaart nij) put:2 at:‘x’
Kaart
(Kaart nij) put:(List ← 1 ; 2) at:‘x’
Kaart
(Kaart nij) put:(List ← ((Kaart nij) put:‘q’ at:‘y’) ; 2) at:‘x’
Nul
Nul
