Null
Null
Boolescher Wert
Wahr
Boolescher Wert
Falsch
Nummer
1
Nummer
-3
Nummer
9,2
Nummer
-9,2
Aufführen
Aufführen neu 
Aufführen
Aufführen ← 1 ; 2
Aufführen
Aufführen ← 1 ; (Aufführen ← 2)
Aufführen
Aufführen ← 1 ; (Aufführen ← 2) ; 3
Aufführen
Aufführen ← 1 ; ((Karte neu) put:‘a’ at:‘b’) ; 3
Aufführen
Aufführen ← 1 ; ((Karte neu) put:(Aufführen ← 9) at:‘b’) ; 3
Karte
(Karte neu) put:2 at:‘1’
Karte
(Karte neu) put:2 at:‘x’
Karte
(Karte neu) put:(Aufführen ← 1 ; 2) at:‘x’
Karte
(Karte neu) put:(Aufführen ← ((Karte neu) put:‘q’ at:‘y’) ; 2) at:‘x’
Null
Null
