There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. ମିଥ୍ୟା
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is ନିଲ୍ meters long.
Luckily, this day, there are ନିଲ୍ wasps in the garden.
The dog named ନିଲ୍ sleeps under the tree.
a\"bb\"ccc\"
(ମାନଚିତ୍ର ନୂତନ) put:((ମାନଚିତ୍ର ନୂତନ) put:ନିଲ୍ at:dog, put:ନିଲ୍ at:insects, put:((ମାନଚିତ୍ର ନୂତନ) put:15 at:‘length’, put:8 at:‘width’) at:‘size’, put:(ତାଲିକା | ← ‘tulips’ ; ‘roses’ ; ‘lillies’) at:‘flower’, put:ମିଥ୍ୟା at:‘shed’, put:ସତ at:‘pool’, put:2 at:‘chairs’) at:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
