Núll
Núll
Boolean
Satt
Boolean
Rangt
Fjöldi
1
Fjöldi
-3
Fjöldi
9,2
Fjöldi
-9,2
Listi
Listi nýtt 
Listi
Listi ← 1 ; 2
Listi
Listi ← 1 ; (Listi ← 2)
Listi
Listi ← 1 ; (Listi ← 2) ; 3
Listi
Listi ← 1 ; ((Kort nýtt) setja:‘a’ _á:‘b’) ; 3
Listi
Listi ← 1 ; ((Kort nýtt) setja:(Listi ← 9) _á:‘b’) ; 3
Kort
(Kort nýtt) setja:2 _á:‘1’
Kort
(Kort nýtt) setja:2 _á:‘x’
Kort
(Kort nýtt) setja:(Listi ← 1 ; 2) _á:‘x’
Kort
(Kort nýtt) setja:(Listi ← ((Kort nýtt) setja:‘q’ _á:‘y’) ; 2) _á:‘x’
Núll
Núll
