Không
Không
Boolean
Thật
Boolean
Sai
Con số
1
Con số
-3
Con số
9,2
Con số
-9,2
Danh sách
Danh sách mới 
Danh sách
Danh sách ← 1 ; 2
Danh sách
Danh sách ← 1 ; (Danh sách ← 2)
Danh sách
Danh sách ← 1 ; (Danh sách ← 2) ; 3
Danh sách
Danh sách ← 1 ; ((Bản đồ mới) đặt:‘a’ tại:‘b’) ; 3
Danh sách
Danh sách ← 1 ; ((Bản đồ mới) đặt:(Danh sách ← 9) tại:‘b’) ; 3
Bản đồ
(Bản đồ mới) đặt:2 tại:‘1’
Bản đồ
(Bản đồ mới) đặt:2 tại:‘x’
Bản đồ
(Bản đồ mới) đặt:(Danh sách ← 1 ; 2) tại:‘x’
Bản đồ
(Bản đồ mới) đặt:(Danh sách ← ((Bản đồ mới) đặt:‘q’ tại:‘y’) ; 2) tại:‘x’
Không
Không
