hello there
+ 3 to Number gives: 3 
Adding 3 to Number gives: 3 
Appending something to String gives: something
False
[Block]
Can I execute a code block without assigning code?
[Block]
True
[Object]
This Nil has no file
0
Boolean ☞ 1.
Boolean ⛏ 1.
Boolean ⚿ 1.
Boolean • 1.
Boolean = 1.
Boolean + 1.
Boolean - 1.
Boolean * 1.
Boolean / 1.
Boolean > 1.
Boolean < 1.
Boolean ? 1.
Boolean ✎ 1.
Boolean ← 1.
Boolean ≥ 1.
Boolean ≤ 1.
Boolean ≠ 1.
Boolean new.
Boolean equals: 1 .
Boolean and: 1 .
Boolean or: 1 .
Boolean modulo: 1 .
Boolean nor: 1 .
Boolean on: 1 do: 1 .
error
Boolean type.
Boolean Nil?.
Boolean myself.
Boolean do.
Boolean done.
Boolean false: 1 .
error
Boolean true: 1 .
Boolean while: 1 .
Boolean message: 1 arguments: 1 .
error
Boolean message: 1 .
Boolean learn: 1 means: 1 .
Boolean break.
Boolean continue.
Boolean else: 1 .
error
Boolean not.
Boolean number.
Boolean string.
Boolean character: 1 .
Boolean either: 1 or: 1 .
Boolean by: 1 .
Boolean floor.
Boolean ceil.
Boolean round.
Boolean absolute.
Boolean square root.
Boolean power: 1 .
Boolean minimum.
Boolean maximum.
Boolean odd?.
Boolean even?.
Boolean positive?.
Boolean negative?.
Boolean boolean.
Boolean between: 1 and: 1 .
Boolean bytes.
Boolean length.
Boolean from: 1 length: 1 .
Boolean remove surrounding spaces.
Boolean at: 1 .
Boolean position: 1 .
Boolean byte: 1 .
Boolean find: 1 .
Boolean last: 1 .
Boolean replace: 1 with: 1 .
Boolean split: 1 .
Boolean offset: 1 .
Boolean pattern: 1 process: 1 .
Boolean run.
Boolean apply: 1 .
Boolean apply: 1 and: 1 .
Boolean set: 1 value: 1 .
Boolean error: 1 .
Boolean catch: 1 .
Boolean ; 1.
Boolean shift.
Boolean count.
Boolean join: 1 .
Boolean pop.
Boolean sort: 1 .
Boolean put: 1 at: 1 .
Boolean map: 1 .
Boolean each: 1 .
Boolean write: 1 .
Boolean path.
Boolean read.
Boolean append: 1 .
Boolean prepend: 1 .
Boolean exists.
Boolean size.
Boolean delete.
Boolean include.
Boolean open: 1 .
Boolean close.
Boolean list: 1 .
Boolean read bytes: 1 .
Boolean write bytes: 1 .
Boolean seek: 1 .
Boolean rewind.
Boolean end.
Boolean argument: 1 .
Boolean arguments.
Boolean ask.
Boolean input.
Boolean flush.
Boolean wait: 1 .
Boolean time.
Boolean respond: 1 .
Boolean respond: 1 and: 1 .
Boolean shell: 1 .
Boolean clean memory.
Boolean memory: 1 .
Boolean memory.
Boolean tidiness: 1 .
Boolean hash: 1 .
Boolean byte.
Boolean characters.
Boolean list.
Boolean append byte: 1 .
Boolean qualify: 1 .
Boolean qualification.
Boolean new: 1 .
Boolean hour.
Boolean hour: 1 .
Boolean minute: 1 .
Boolean minute.
Boolean second: 1 .
Boolean second.
Boolean day.
Boolean day: 1 .
Boolean week.
Boolean week: 1 .
Boolean month.
Boolean month: 1 .
Boolean year.
Boolean year: 1 .
Boolean weekday.
Boolean day of the year.
Boolean zone.
Boolean zone: 1 .
Boolean add: 1 .
Boolean subtract: 1 .
Boolean multiply by: 1 .
Boolean divide by: 1 .
Boolean like: 1 .
Boolean format: 1 .
Boolean lock.
Boolean unlock.
Boolean last.
Boolean first.
Boolean second last.
Boolean fill: 1 with: 1 .
Boolean replace: 1 length: 1 with: 1 .
Boolean values.
Boolean entries.
Boolean compare: 1 .
Boolean has: 1 .
Boolean copy.
Boolean case: 1 do: 1 .
error
Boolean stop.
Boolean uppercase.
Boolean lowercase.
Boolean pattern: 1 process: 1 options: 1 .
Boolean matches: 1 .
Boolean contains: 1 .
Boolean apply: 1 and: 1 and: 1 .
Boolean setting: 1 .
Boolean setting: 1 value: 1 .
Boolean respond: 1 and: 1 and: 1 .
Boolean respond: 1 and: 1 and: 1 and: 1 .
Boolean this code block.
True ☞ 1.
True ⛏ 1.
True ⚿ 1.
True • 1.
True = 1.
True + 1.
True - 1.
True * 1.
True / 1.
True > 1.
True < 1.
True ? 1.
True ✎ 1.
True ← 1.
True ≥ 1.
True ≤ 1.
True ≠ 1.
True new.
True equals: 1 .
True and: 1 .
True or: 1 .
True modulo: 1 .
True nor: 1 .
True on: 1 do: 1 .
error
True type.
True Nil?.
True myself.
True do.
True done.
True false: 1 .
True true: 1 .
error
True while: 1 .
True message: 1 arguments: 1 .
error
True message: 1 .
True learn: 1 means: 1 .
True break.
True continue.
True else: 1 .
True not.
True number.
True string.
True character: 1 .
True either: 1 or: 1 .
True by: 1 .
True floor.
True ceil.
True round.
True absolute.
True square root.
True power: 1 .
True minimum.
True maximum.
True odd?.
True even?.
True positive?.
True negative?.
True boolean.
True between: 1 and: 1 .
True bytes.
True length.
True from: 1 length: 1 .
True remove surrounding spaces.
True at: 1 .
True position: 1 .
True byte: 1 .
True find: 1 .
True last: 1 .
True replace: 1 with: 1 .
True split: 1 .
True offset: 1 .
True pattern: 1 process: 1 .
True run.
True apply: 1 .
True apply: 1 and: 1 .
True set: 1 value: 1 .
True error: 1 .
True catch: 1 .
True ; 1.
True shift.
True count.
True join: 1 .
True pop.
True sort: 1 .
True put: 1 at: 1 .
True map: 1 .
True each: 1 .
True write: 1 .
True path.
True read.
True append: 1 .
True prepend: 1 .
True exists.
True size.
True delete.
True include.
True open: 1 .
True close.
True list: 1 .
True read bytes: 1 .
True write bytes: 1 .
True seek: 1 .
True rewind.
True end.
True argument: 1 .
True arguments.
True ask.
True input.
True flush.
True wait: 1 .
True time.
True respond: 1 .
True respond: 1 and: 1 .
True shell: 1 .
True clean memory.
True memory: 1 .
True memory.
True tidiness: 1 .
True hash: 1 .
True byte.
True characters.
True list.
True append byte: 1 .
True qualify: 1 .
True qualification.
True new: 1 .
True hour.
True hour: 1 .
True minute: 1 .
True minute.
True second: 1 .
True second.
True day.
True day: 1 .
True week.
True week: 1 .
True month.
True month: 1 .
True year.
True year: 1 .
True weekday.
True day of the year.
True zone.
True zone: 1 .
True add: 1 .
True subtract: 1 .
True multiply by: 1 .
True divide by: 1 .
True like: 1 .
True format: 1 .
True lock.
True unlock.
True last.
True first.
True second last.
True fill: 1 with: 1 .
True replace: 1 length: 1 with: 1 .
True values.
True entries.
True compare: 1 .
True has: 1 .
True copy.
True case: 1 do: 1 .
error
True stop.
True uppercase.
True lowercase.
True pattern: 1 process: 1 options: 1 .
True matches: 1 .
True contains: 1 .
True apply: 1 and: 1 and: 1 .
True setting: 1 .
True setting: 1 value: 1 .
True respond: 1 and: 1 and: 1 .
True respond: 1 and: 1 and: 1 and: 1 .
True this code block.
False ☞ 1.
False ⛏ 1.
False ⚿ 1.
False • 1.
False = 1.
False + 1.
False - 1.
False * 1.
False / 1.
False > 1.
False < 1.
False ? 1.
False ✎ 1.
False ← 1.
False ≥ 1.
False ≤ 1.
False ≠ 1.
False new.
False equals: 1 .
False and: 1 .
False or: 1 .
False modulo: 1 .
False nor: 1 .
False on: 1 do: 1 .
error
False type.
False Nil?.
False myself.
False do.
False done.
False false: 1 .
error
False true: 1 .
False while: 1 .
False message: 1 arguments: 1 .
error
False message: 1 .
False learn: 1 means: 1 .
False break.
False continue.
False else: 1 .
error
False not.
False number.
False string.
False character: 1 .
False either: 1 or: 1 .
False by: 1 .
False floor.
False ceil.
False round.
False absolute.
False square root.
False power: 1 .
False minimum.
False maximum.
False odd?.
False even?.
False positive?.
False negative?.
False boolean.
False between: 1 and: 1 .
False bytes.
False length.
False from: 1 length: 1 .
False remove surrounding spaces.
False at: 1 .
False position: 1 .
False byte: 1 .
False find: 1 .
False last: 1 .
False replace: 1 with: 1 .
False split: 1 .
False offset: 1 .
False pattern: 1 process: 1 .
False run.
False apply: 1 .
False apply: 1 and: 1 .
False set: 1 value: 1 .
False error: 1 .
False catch: 1 .
False ; 1.
False shift.
False count.
False join: 1 .
False pop.
False sort: 1 .
False put: 1 at: 1 .
False map: 1 .
False each: 1 .
False write: 1 .
False path.
False read.
False append: 1 .
False prepend: 1 .
False exists.
False size.
False delete.
False include.
False open: 1 .
False close.
False list: 1 .
False read bytes: 1 .
False write bytes: 1 .
False seek: 1 .
False rewind.
False end.
False argument: 1 .
False arguments.
False ask.
False input.
False flush.
False wait: 1 .
False time.
False respond: 1 .
False respond: 1 and: 1 .
False shell: 1 .
False clean memory.
False memory: 1 .
False memory.
False tidiness: 1 .
False hash: 1 .
False byte.
False characters.
False list.
False append byte: 1 .
False qualify: 1 .
False qualification.
False new: 1 .
False hour.
False hour: 1 .
False minute: 1 .
False minute.
False second: 1 .
False second.
False day.
False day: 1 .
False week.
False week: 1 .
False month.
False month: 1 .
False year.
False year: 1 .
False weekday.
False day of the year.
False zone.
False zone: 1 .
False add: 1 .
False subtract: 1 .
False multiply by: 1 .
False divide by: 1 .
False like: 1 .
False format: 1 .
False lock.
False unlock.
False last.
False first.
False second last.
False fill: 1 with: 1 .
False replace: 1 length: 1 with: 1 .
False values.
False entries.
False compare: 1 .
False has: 1 .
False copy.
False case: 1 do: 1 .
error
False stop.
False uppercase.
False lowercase.
False pattern: 1 process: 1 options: 1 .
False matches: 1 .
False contains: 1 .
False apply: 1 and: 1 and: 1 .
False setting: 1 .
False setting: 1 value: 1 .
False respond: 1 and: 1 and: 1 .
False respond: 1 and: 1 and: 1 and: 1 .
False this code block.
Number ☞ 1.
Number ⛏ 1.
Number ⚿ 1.
Number • 1.
Number = 1.
Number + 1.
Number - 1.
Number * 1.
Number / 1.
Number > 1.
Number < 1.
Number ? 1.
Number ✎ 1.
Number ← 1.
Number ≥ 1.
Number ≤ 1.
Number ≠ 1.
Number new.
Number equals: 1 .
Number and: 1 .
Number or: 1 .
Number modulo: 1 .
Number nor: 1 .
Number on: 1 do: 1 .
error
Number type.
Number Nil?.
Number myself.
Number do.
Number done.
Number false: 1 .
Number true: 1 .
error
Number while: 1 .
Number message: 1 arguments: 1 .
error
Number message: 1 .
Number learn: 1 means: 1 .
Number break.
Number continue.
Number else: 1 .
Number not.
Number number.
Number string.
Number character: 1 .
Number either: 1 or: 1 .
Number by: 1 .
Number floor.
Number ceil.
Number round.
Number absolute.
Number square root.
Number power: 1 .
Number minimum.
Number maximum.
Number odd?.
Number even?.
Number positive?.
Number negative?.
Number boolean.
Number between: 1 and: 1 .
Number bytes.
Number length.
Number from: 1 length: 1 .
Number remove surrounding spaces.
Number at: 1 .
Number position: 1 .
Number byte: 1 .
Number find: 1 .
Number last: 1 .
Number replace: 1 with: 1 .
Number split: 1 .
Number offset: 1 .
Number pattern: 1 process: 1 .
Number run.
Number apply: 1 .
Number apply: 1 and: 1 .
Number set: 1 value: 1 .
Number error: 1 .
Number catch: 1 .
Number ; 1.
Number shift.
Number count.
Number join: 1 .
Number pop.
Number sort: 1 .
Number put: 1 at: 1 .
Number map: 1 .
Number each: 1 .
Number write: 1 .
Number path.
Number read.
Number append: 1 .
Number prepend: 1 .
Number exists.
Number size.
Number delete.
Number include.
Number open: 1 .
Number close.
Number list: 1 .
Number read bytes: 1 .
Number write bytes: 1 .
Number seek: 1 .
Number rewind.
Number end.
Number argument: 1 .
Number arguments.
Number ask.
Number input.
Number flush.
Number wait: 1 .
Number time.
Number respond: 1 .
Number respond: 1 and: 1 .
Number shell: 1 .
Number clean memory.
Number memory: 1 .
Number memory.
Number tidiness: 1 .
Number hash: 1 .
Number byte.
Number characters.
Number list.
Number append byte: 1 .
Number qualify: 1 .
Number qualification.
Number new: 1 .
Number hour.
Number hour: 1 .
Number minute: 1 .
Number minute.
Number second: 1 .
Number second.
Number day.
Number day: 1 .
Number week.
Number week: 1 .
Number month.
Number month: 1 .
Number year.
Number year: 1 .
Number weekday.
Number day of the year.
Number zone.
Number zone: 1 .
Number add: 1 .
Number subtract: 1 .
Number multiply by: 1 .
Number divide by: 1 .
Number like: 1 .
Number format: 1 .
Number lock.
Number unlock.
Number last.
Number first.
Number second last.
Number fill: 1 with: 1 .
Number replace: 1 length: 1 with: 1 .
Number values.
Number entries.
Number compare: 1 .
Number has: 1 .
Number copy.
Number case: 1 do: 1 .
error
Number stop.
Number uppercase.
Number lowercase.
Number pattern: 1 process: 1 options: 1 .
Number matches: 1 .
Number contains: 1 .
Number apply: 1 and: 1 and: 1 .
Number setting: 1 .
Number setting: 1 value: 1 .
Number respond: 1 and: 1 and: 1 .
Number respond: 1 and: 1 and: 1 and: 1 .
Number this code block.
String ☞ 1.
String ⛏ 1.
String ⚿ 1.
String • 1.
String = 1.
String + 1.
String - 1.
String * 1.
String / 1.
String > 1.
String < 1.
String ? 1.
String ✎ 1.
String ← 1.
String ≥ 1.
String ≤ 1.
String ≠ 1.
String new.
String equals: 1 .
String and: 1 .
String or: 1 .
String modulo: 1 .
String nor: 1 .
String on: 1 do: 1 .
error
String type.
String Nil?.
String myself.
String do.
String done.
String false: 1 .
String true: 1 .
error
String while: 1 .
String message: 1 arguments: 1 .
error
String message: 1 .
String learn: 1 means: 1 .
String break.
String continue.
String else: 1 .
String not.
String number.
String string.
String character: 1 .
String either: 1 or: 1 .
String by: 1 .
String floor.
String ceil.
String round.
String absolute.
String square root.
String power: 1 .
String minimum.
String maximum.
String odd?.
String even?.
String positive?.
String negative?.
String boolean.
String between: 1 and: 1 .
String bytes.
String length.
String from: 1 length: 1 .
String remove surrounding spaces.
String at: 1 .
String position: 1 .
String byte: 1 .
String find: 1 .
String last: 1 .
String replace: 1 with: 1 .
String split: 1 .
String offset: 1 .
String pattern: 1 process: 1 .
error
String run.
String apply: 1 .
String apply: 1 and: 1 .
String set: 1 value: 1 .
String error: 1 .
String catch: 1 .
String ; 1.
String shift.
String count.
String join: 1 .
String pop.
String sort: 1 .
String put: 1 at: 1 .
String map: 1 .
String each: 1 .
String write: 1 .
String path.
String read.
String append: 1 .
String prepend: 1 .
String exists.
String size.
String delete.
String include.
String open: 1 .
String close.
String list: 1 .
String read bytes: 1 .
String write bytes: 1 .
String seek: 1 .
String rewind.
String end.
String argument: 1 .
String arguments.
String ask.
String input.
String flush.
String wait: 1 .
String time.
String respond: 1 .
String respond: 1 and: 1 .
String shell: 1 .
String clean memory.
String memory: 1 .
String memory.
String tidiness: 1 .
String hash: 1 .
error
String byte.
String characters.
String list.
String append byte: 1 .
String qualify: 1 .
String qualification.
String new: 1 .
String hour.
String hour: 1 .
String minute: 1 .
String minute.
String second: 1 .
String second.
String day.
String day: 1 .
String week.
String week: 1 .
String month.
String month: 1 .
String year.
String year: 1 .
String weekday.
String day of the year.
String zone.
String zone: 1 .
String add: 1 .
String subtract: 1 .
String multiply by: 1 .
String divide by: 1 .
String like: 1 .
String format: 1 .
String lock.
String unlock.
String last.
String first.
String second last.
String fill: 1 with: 1 .
String replace: 1 length: 1 with: 1 .
String values.
String entries.
String compare: 1 .
String has: 1 .
String copy.
String case: 1 do: 1 .
error
String stop.
String uppercase.
String lowercase.
String pattern: 1 process: 1 options: 1 .
error
String matches: 1 .
String contains: 1 .
String apply: 1 and: 1 and: 1 .
String setting: 1 .
String setting: 1 value: 1 .
String respond: 1 and: 1 and: 1 .
String respond: 1 and: 1 and: 1 and: 1 .
String this code block.
Object ☞ 1.
Object ⛏ 1.
Object ⚿ 1.
Object • 1.
Object = 1.
Object + 1.
Object - 1.
Object * 1.
Object / 1.
Object > 1.
Object < 1.
Object ? 1.
Object ✎ 1.
Object ← 1.
Object ≥ 1.
Object ≤ 1.
Object ≠ 1.
Object new.
Object equals: 1 .
Object and: 1 .
Object or: 1 .
Object modulo: 1 .
Object nor: 1 .
Object on: 1 do: 1 .
error
Object type.
Object Nil?.
Object myself.
Object do.
Object done.
Object false: 1 .
Object true: 1 .
error
Object while: 1 .
Object message: 1 arguments: 1 .
error
Object message: 1 .
Object learn: 1 means: 1 .
Object break.
Object continue.
Object else: 1 .
Object not.
Object number.
Object string.
Object character: 1 .
Object either: 1 or: 1 .
Object by: 1 .
Object floor.
Object ceil.
Object round.
Object absolute.
Object square root.
Object power: 1 .
Object minimum.
Object maximum.
Object odd?.
Object even?.
Object positive?.
Object negative?.
Object boolean.
Object between: 1 and: 1 .
Object bytes.
Object length.
Object from: 1 length: 1 .
Object remove surrounding spaces.
Object at: 1 .
Object position: 1 .
Object byte: 1 .
Object find: 1 .
Object last: 1 .
Object replace: 1 with: 1 .
Object split: 1 .
Object offset: 1 .
Object pattern: 1 process: 1 .
Object run.
Object apply: 1 .
Object apply: 1 and: 1 .
Object set: 1 value: 1 .
Object error: 1 .
Object catch: 1 .
Object ; 1.
Object shift.
Object count.
Object join: 1 .
Object pop.
Object sort: 1 .
Object put: 1 at: 1 .
Object map: 1 .
Object each: 1 .
Object write: 1 .
Object path.
Object read.
Object append: 1 .
Object prepend: 1 .
Object exists.
Object size.
Object delete.
Object include.
Object open: 1 .
Object close.
Object list: 1 .
Object read bytes: 1 .
Object write bytes: 1 .
Object seek: 1 .
Object rewind.
Object end.
Object argument: 1 .
Object arguments.
Object ask.
Object input.
Object flush.
Object wait: 1 .
Object time.
Object respond: 1 .
Object respond: 1 and: 1 .
Object shell: 1 .
Object clean memory.
Object memory: 1 .
Object memory.
Object tidiness: 1 .
Object hash: 1 .
Object byte.
Object characters.
Object list.
Object append byte: 1 .
Object qualify: 1 .
Object qualification.
Object new: 1 .
Object hour.
Object hour: 1 .
Object minute: 1 .
Object minute.
Object second: 1 .
Object second.
Object day.
Object day: 1 .
Object week.
Object week: 1 .
Object month.
Object month: 1 .
Object year.
Object year: 1 .
Object weekday.
Object day of the year.
Object zone.
Object zone: 1 .
Object add: 1 .
Object subtract: 1 .
Object multiply by: 1 .
Object divide by: 1 .
Object like: 1 .
Object format: 1 .
Object lock.
Object unlock.
Object last.
Object first.
Object second last.
Object fill: 1 with: 1 .
Object replace: 1 length: 1 with: 1 .
Object values.
Object entries.
Object compare: 1 .
Object has: 1 .
Object copy.
Object case: 1 do: 1 .
error
Object stop.
Object uppercase.
Object lowercase.
Object pattern: 1 process: 1 options: 1 .
Object matches: 1 .
Object contains: 1 .
Object apply: 1 and: 1 and: 1 .
Object setting: 1 .
Object setting: 1 value: 1 .
Object respond: 1 and: 1 and: 1 .
Object respond: 1 and: 1 and: 1 and: 1 .
Object this code block.
List ☞ 1.
List ⛏ 1.
List ⚿ 1.
List • 1.
List = 1.
List + 1.
List - 1.
List * 1.
List / 1.
List > 1.
List < 1.
List ? 1.
error
List ✎ 1.
List ← 1.
List ≥ 1.
List ≤ 1.
List ≠ 1.
List new.
List equals: 1 .
List and: 1 .
List or: 1 .
List modulo: 1 .
List nor: 1 .
List on: 1 do: 1 .
error
List type.
List Nil?.
List myself.
List do.
List done.
List false: 1 .
List true: 1 .
error
List while: 1 .
List message: 1 arguments: 1 .
error
List message: 1 .
List learn: 1 means: 1 .
List break.
List continue.
List else: 1 .
List not.
List number.
List string.
List character: 1 .
List either: 1 or: 1 .
List by: 1 .
List floor.
List ceil.
List round.
List absolute.
List square root.
List power: 1 .
List minimum.
List maximum.
List odd?.
List even?.
List positive?.
List negative?.
List boolean.
List between: 1 and: 1 .
List bytes.
List length.
List from: 1 length: 1 .
error
List remove surrounding spaces.
List at: 1 .
List position: 1 .
error
List byte: 1 .
List find: 1 .
List last: 1 .
List replace: 1 with: 1 .
List split: 1 .
List offset: 1 .
List pattern: 1 process: 1 .
List run.
List apply: 1 .
List apply: 1 and: 1 .
List set: 1 value: 1 .
List error: 1 .
List catch: 1 .
List ; 1.
List shift.
List count.
List join: 1 .
List pop.
List sort: 1 .
error
List put: 1 at: 1 .
List map: 1 .
error
List each: 1 .
error
List write: 1 .
List path.
List read.
List append: 1 .
List prepend: 1 .
List exists.
List size.
List delete.
List include.
List open: 1 .
List close.
List list: 1 .
List read bytes: 1 .
List write bytes: 1 .
List seek: 1 .
List rewind.
List end.
List argument: 1 .
List arguments.
List ask.
List input.
List flush.
List wait: 1 .
List time.
List respond: 1 .
List respond: 1 and: 1 .
List shell: 1 .
List clean memory.
List memory: 1 .
List memory.
List tidiness: 1 .
List hash: 1 .
List byte.
List characters.
List list.
List append byte: 1 .
List qualify: 1 .
List qualification.
List new: 1 .
List hour.
List hour: 1 .
List minute: 1 .
List minute.
List second: 1 .
List second.
List day.
List day: 1 .
List week.
List week: 1 .
List month.
List month: 1 .
List year.
List year: 1 .
List weekday.
List day of the year.
List zone.
List zone: 1 .
List add: 1 .
List subtract: 1 .
List multiply by: 1 .
List divide by: 1 .
List like: 1 .
List format: 1 .
List lock.
List unlock.
List last.
List first.
List second last.
List fill: 1 with: 1 .
List replace: 1 length: 1 with: 1 .
error
List values.
List entries.
List compare: 1 .
List has: 1 .
List copy.
List case: 1 do: 1 .
error
List stop.
List uppercase.
List lowercase.
List pattern: 1 process: 1 options: 1 .
List matches: 1 .
List contains: 1 .
List apply: 1 and: 1 and: 1 .
List setting: 1 .
List setting: 1 value: 1 .
List respond: 1 and: 1 and: 1 .
List respond: 1 and: 1 and: 1 and: 1 .
List this code block.
Map ☞ 1.
Map ⛏ 1.
Map ⚿ 1.
Map • 1.
Map = 1.
Map + 1.
Map - 1.
Map * 1.
Map / 1.
Map > 1.
Map < 1.
Map ? 1.
Map ✎ 1.
Map ← 1.
Map ≥ 1.
Map ≤ 1.
Map ≠ 1.
Map new.
Map equals: 1 .
Map and: 1 .
Map or: 1 .
Map modulo: 1 .
Map nor: 1 .
Map on: 1 do: 1 .
error
Map type.
Map Nil?.
Map myself.
Map do.
Map done.
Map false: 1 .
Map true: 1 .
error
Map while: 1 .
Map message: 1 arguments: 1 .
error
Map message: 1 .
Map learn: 1 means: 1 .
Map break.
Map continue.
Map else: 1 .
Map not.
Map number.
Map string.
Map character: 1 .
Map either: 1 or: 1 .
Map by: 1 .
Map floor.
Map ceil.
Map round.
Map absolute.
Map square root.
Map power: 1 .
Map minimum.
Map maximum.
Map odd?.
Map even?.
Map positive?.
Map negative?.
Map boolean.
Map between: 1 and: 1 .
Map bytes.
Map length.
Map from: 1 length: 1 .
Map remove surrounding spaces.
Map at: 1 .
Map position: 1 .
Map byte: 1 .
Map find: 1 .
Map last: 1 .
Map replace: 1 with: 1 .
Map split: 1 .
Map offset: 1 .
Map pattern: 1 process: 1 .
Map run.
Map apply: 1 .
Map apply: 1 and: 1 .
Map set: 1 value: 1 .
Map error: 1 .
Map catch: 1 .
Map ; 1.
Map shift.
Map count.
Map join: 1 .
Map pop.
Map sort: 1 .
Map put: 1 at: 1 .
Map map: 1 .
error
Map each: 1 .
error
Map write: 1 .
Map path.
Map read.
Map append: 1 .
Map prepend: 1 .
Map exists.
Map size.
Map delete.
Map include.
Map open: 1 .
Map close.
Map list: 1 .
Map read bytes: 1 .
Map write bytes: 1 .
Map seek: 1 .
Map rewind.
Map end.
Map argument: 1 .
Map arguments.
Map ask.
Map input.
Map flush.
Map wait: 1 .
Map time.
Map respond: 1 .
Map respond: 1 and: 1 .
Map shell: 1 .
Map clean memory.
Map memory: 1 .
Map memory.
Map tidiness: 1 .
Map hash: 1 .
Map byte.
Map characters.
Map list.
Map append byte: 1 .
Map qualify: 1 .
Map qualification.
Map new: 1 .
Map hour.
Map hour: 1 .
Map minute: 1 .
Map minute.
Map second: 1 .
Map second.
Map day.
Map day: 1 .
Map week.
Map week: 1 .
Map month.
Map month: 1 .
Map year.
Map year: 1 .
Map weekday.
Map day of the year.
Map zone.
Map zone: 1 .
Map add: 1 .
Map subtract: 1 .
Map multiply by: 1 .
Map divide by: 1 .
Map like: 1 .
Map format: 1 .
Map lock.
Map unlock.
Map last.
Map first.
Map second last.
Map fill: 1 with: 1 .
Map replace: 1 length: 1 with: 1 .
Map values.
Map entries.
Map compare: 1 .
Map has: 1 .
Map copy.
Map case: 1 do: 1 .
error
Map stop.
Map uppercase.
Map lowercase.
Map pattern: 1 process: 1 options: 1 .
Map matches: 1 .
Map contains: 1 .
Map apply: 1 and: 1 and: 1 .
Map setting: 1 .
Map setting: 1 value: 1 .
Map respond: 1 and: 1 and: 1 .
Map respond: 1 and: 1 and: 1 and: 1 .
Map this code block.
File ☞ 1.
File ⛏ 1.
File ⚿ 1.
File • 1.
File = 1.
File + 1.
File - 1.
File * 1.
File / 1.
File > 1.
File < 1.
File ? 1.
File ✎ 1.
File ← 1.
File ≥ 1.
File ≤ 1.
File ≠ 1.
File new.
File equals: 1 .
File and: 1 .
File or: 1 .
File modulo: 1 .
File nor: 1 .
File on: 1 do: 1 .
error
File type.
File Nil?.
File myself.
File do.
File done.
File false: 1 .
File true: 1 .
error
File while: 1 .
File message: 1 arguments: 1 .
error
File message: 1 .
File learn: 1 means: 1 .
File break.
File continue.
File else: 1 .
File not.
File number.
File string.
File character: 1 .
File either: 1 or: 1 .
File by: 1 .
File floor.
File ceil.
File round.
File absolute.
File square root.
File power: 1 .
File minimum.
File maximum.
File odd?.
File even?.
File positive?.
File negative?.
File boolean.
File between: 1 and: 1 .
File bytes.
File length.
File from: 1 length: 1 .
File remove surrounding spaces.
File at: 1 .
File position: 1 .
File byte: 1 .
File find: 1 .
File last: 1 .
File replace: 1 with: 1 .
File split: 1 .
File offset: 1 .
File pattern: 1 process: 1 .
File run.
File apply: 1 .
File apply: 1 and: 1 .
File set: 1 value: 1 .
File error: 1 .
File catch: 1 .
File ; 1.
File shift.
File count.
File join: 1 .
File pop.
File sort: 1 .
File put: 1 at: 1 .
File map: 1 .
File each: 1 .
File write: 1 .
File path.
File read.
File append: 1 .
File prepend: 1 .
File exists.
File size.
File delete.
File include.
File open: 1 .
File close.
File list: 1 .
error
File read bytes: 1 .
File write bytes: 1 .
File seek: 1 .
File rewind.
File end.
File argument: 1 .
File arguments.
File ask.
File input.
File flush.
File wait: 1 .
File time.
File respond: 1 .
File respond: 1 and: 1 .
File shell: 1 .
File clean memory.
File memory: 1 .
File memory.
File tidiness: 1 .
File hash: 1 .
File byte.
File characters.
File list.
File append byte: 1 .
File qualify: 1 .
File qualification.
File new: 1 .
File hour.
File hour: 1 .
File minute: 1 .
File minute.
File second: 1 .
File second.
File day.
File day: 1 .
File week.
File week: 1 .
File month.
File month: 1 .
File year.
File year: 1 .
File weekday.
File day of the year.
File zone.
File zone: 1 .
File add: 1 .
File subtract: 1 .
File multiply by: 1 .
File divide by: 1 .
File like: 1 .
File format: 1 .
File lock.
error
File unlock.
error
File last.
File first.
File second last.
File fill: 1 with: 1 .
File replace: 1 length: 1 with: 1 .
File values.
File entries.
File compare: 1 .
File has: 1 .
File copy.
File case: 1 do: 1 .
error
File stop.
File uppercase.
File lowercase.
File pattern: 1 process: 1 options: 1 .
File matches: 1 .
File contains: 1 .
File apply: 1 and: 1 and: 1 .
File setting: 1 .
File setting: 1 value: 1 .
File respond: 1 and: 1 and: 1 .
File respond: 1 and: 1 and: 1 and: 1 .
File this code block.
Moment ☞ 1.
Moment ⛏ 1.
Moment ⚿ 1.
Moment • 1.
Moment = 1.
Moment + 1.
Moment - 1.
Moment * 1.
Moment / 1.
Moment > 1.
Moment < 1.
Moment ? 1.
Moment ✎ 1.
Moment ← 1.
Moment ≥ 1.
Moment ≤ 1.
Moment ≠ 1.
Moment new.
Moment equals: 1 .
Moment and: 1 .
Moment or: 1 .
Moment modulo: 1 .
Moment nor: 1 .
Moment on: 1 do: 1 .
error
Moment type.
Moment Nil?.
Moment myself.
Moment do.
Moment done.
Moment false: 1 .
Moment true: 1 .
error
Moment while: 1 .
Moment message: 1 arguments: 1 .
error
Moment message: 1 .
Moment learn: 1 means: 1 .
Moment break.
Moment continue.
Moment else: 1 .
Moment not.
Moment number.
Moment string.
Moment character: 1 .
Moment either: 1 or: 1 .
Moment by: 1 .
Moment floor.
Moment ceil.
Moment round.
Moment absolute.
Moment square root.
Moment power: 1 .
Moment minimum.
Moment maximum.
Moment odd?.
Moment even?.
Moment positive?.
Moment negative?.
Moment boolean.
Moment between: 1 and: 1 .
Moment bytes.
Moment length.
Moment from: 1 length: 1 .
Moment remove surrounding spaces.
Moment at: 1 .
Moment position: 1 .
Moment byte: 1 .
Moment find: 1 .
Moment last: 1 .
Moment replace: 1 with: 1 .
Moment split: 1 .
Moment offset: 1 .
Moment pattern: 1 process: 1 .
Moment run.
Moment apply: 1 .
Moment apply: 1 and: 1 .
Moment set: 1 value: 1 .
Moment error: 1 .
Moment catch: 1 .
Moment ; 1.
Moment shift.
Moment count.
Moment join: 1 .
Moment pop.
Moment sort: 1 .
Moment put: 1 at: 1 .
Moment map: 1 .
Moment each: 1 .
Moment write: 1 .
Moment path.
Moment read.
Moment append: 1 .
Moment prepend: 1 .
Moment exists.
Moment size.
Moment delete.
Moment include.
Moment open: 1 .
Moment close.
Moment list: 1 .
Moment read bytes: 1 .
Moment write bytes: 1 .
Moment seek: 1 .
Moment rewind.
Moment end.
Moment argument: 1 .
Moment arguments.
Moment ask.
Moment input.
Moment flush.
Moment wait: 1 .
Moment time.
Moment respond: 1 .
Moment respond: 1 and: 1 .
Moment shell: 1 .
Moment clean memory.
Moment memory: 1 .
Moment memory.
Moment tidiness: 1 .
Moment hash: 1 .
Moment byte.
Moment characters.
Moment list.
Moment append byte: 1 .
Moment qualify: 1 .
Moment qualification.
Moment new: 1 .
Moment hour.
Moment hour: 1 .
Moment minute: 1 .
Moment minute.
Moment second: 1 .
Moment second.
Moment day.
Moment day: 1 .
Moment week.
Moment week: 1 .
Moment month.
Moment month: 1 .
Moment year.
Moment year: 1 .
Moment weekday.
Moment day of the year.
Moment zone.
Moment zone: 1 .
Moment add: 1 .
Moment subtract: 1 .
Moment multiply by: 1 .
Moment divide by: 1 .
Moment like: 1 .
Moment format: 1 .
Moment lock.
Moment unlock.
Moment last.
Moment first.
Moment second last.
Moment fill: 1 with: 1 .
Moment replace: 1 length: 1 with: 1 .
Moment values.
Moment entries.
Moment compare: 1 .
Moment has: 1 .
Moment copy.
Moment case: 1 do: 1 .
error
Moment stop.
Moment uppercase.
Moment lowercase.
Moment pattern: 1 process: 1 options: 1 .
Moment matches: 1 .
Moment contains: 1 .
Moment apply: 1 and: 1 and: 1 .
Moment setting: 1 .
Moment setting: 1 value: 1 .
Moment respond: 1 and: 1 and: 1 .
Moment respond: 1 and: 1 and: 1 and: 1 .
Moment this code block.
☞ ☞ 1.
Uncatched error has occurred.
Parse error, unexpected number ( eval: 1 )
Expected message.

#4 new: (tests/test0209.ctr: 44)
#3 code (tests/test0209.ctr: 44)
#2 each: (tests/test0209.ctr: 29)
#1 each: (tests/test0209.ctr: 28)
