(नक्शा नयाँ) राख्नुहोस्:'a"b' मा:'test'
Invalid JSON.
(नक्शा नयाँ) राख्नुहोस्:(सूची ← 1 ; 2 ; (सूची ← 3 ; 4) ; ((नक्शा नयाँ) राख्नुहोस्:(सूची ← 3 ; 4) मा:'bar', राख्नुहोस्:1 मा:'foo')) मा:'nested', राख्नुहोस्:गलत मा:'legend', राख्नुहोस्:27 मा:'age', राख्नुहोस्:'Jack' मा:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
