Nil
Nil
Boolean
Dogry
Boolean
Sealňyş
San
1
San
-3
San
9,2
San
-9,2
Sanaw
Sanaw täze 
Sanaw
Sanaw ← 1 ; 2
Sanaw
Sanaw ← 1 ; (Sanaw ← 2)
Sanaw
Sanaw ← 1 ; (Sanaw ← 2) ; 3
Sanaw
Sanaw ← 1 ; ((Karta täze) goý:‘a’ at:‘b’) ; 3
Sanaw
Sanaw ← 1 ; ((Karta täze) goý:(Sanaw ← 9) at:‘b’) ; 3
Karta
(Karta täze) goý:2 at:‘1’
Karta
(Karta täze) goý:2 at:‘x’
Karta
(Karta täze) goý:(Sanaw ← 1 ; 2) at:‘x’
Karta
(Karta täze) goý:(Sanaw ← ((Karta täze) goý:‘q’ at:‘y’) ; 2) at:‘x’
Nil
Nil
