(Mapa novo) coloque em:'a"b' __:'test'
Invalid JSON.
(Mapa novo) coloque em:(Lista ← 1 ; 2 ; (Lista ← 3 ; 4) ; ((Mapa novo) coloque em:(Lista ← 3 ; 4) __:'bar', coloque em:1 __:'foo')) __:'nested', coloque em:Falso __:'legend', coloque em:27 __:'age', coloque em:'Jack' __:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
