There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falso
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nulo meters long.
Luckily, this day, there are Nulo wasps in the garden.
The dog named Nulo sleeps under the tree.
a\"bb\"ccc\"
(Novo mapa) coloque:((Novo mapa) coloque:Nulo no:“dog”, coloque:Nulo no:“insects”, coloque:((Novo mapa) coloque:15 no:“length”, coloque:8 no:“width”) no:“size”, coloque:(Listar ← “tulips” ; “roses” ; “lillies”) no:“flower”, coloque:Falso no:“shed”, coloque:Verdadeiro no:“pool”, coloque:2 no:“chairs”) no:“garden”
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
