There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. يالغان
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(خەرىتە new) put:((خەرىتە new) put:Nil at:dog, put:Nil at:insects, put:((خەرىتە new) put:15 at:'length', put:8 at:'width') at:'size', put:(تىزىملىك ← 'tulips' ; 'roses' ; 'lillies') at:'flower', put:يالغان at:'shed', put:توغرا at:'pool', put:2 at:'chairs') at:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
