There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. ਗਲਤ
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is ਨੀ meters long.
Luckily, this day, there are ਨੀ wasps in the garden.
The dog named ਨੀ sleeps under the tree.
a\"bb\"ccc\"
(ਨਕਸ਼ਾ ਨਵਾਂ) ਪਾ:((ਨਕਸ਼ਾ ਨਵਾਂ) ਪਾ:ਨੀ ਤੇ:dog, ਪਾ:ਨੀ ਤੇ:insects, ਪਾ:((ਨਕਸ਼ਾ ਨਵਾਂ) ਪਾ:15 ਤੇ:‘length’, ਪਾ:8 ਤੇ:‘width’) ਤੇ:‘size’, ਪਾ:(ਸੂਚੀ ← ‘tulips’ ; ‘roses’ ; ‘lillies’) ਤੇ:‘flower’, ਪਾ:ਗਲਤ ਤੇ:‘shed’, ਪਾ:ਸਚੁ ਤੇ:‘pool’, ਪਾ:2 ਤੇ:‘chairs’) ਤੇ:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
