(Mahere hou) tuu:'a"b' _i:'test'
Invalid JSON.
(Mahere hou) tuu:(Raarangi ← 1 ; 2 ; (Raarangi ← 3 ; 4) ; ((Mahere hou) tuu:(Raarangi ← 3 ; 4) _i:'bar', tuu:1 _i:'foo')) _i:'nested', tuu:Horihori _i:'legend', tuu:27 _i:'age', tuu:'Jack' _i:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
