(Qert nşh) danîn:'a"b' li:'test'
Invalid JSON.
(Qert nşh) danîn:(Rêzok ← 1 ; 2 ; (Rêzok ← 3 ; 4) ; ((Qert nşh) danîn:(Rêzok ← 3 ; 4) li:'bar', danîn:1 li:'foo')) li:'nested', danîn:şaş li:'legend', danîn:27 li:'age', danîn:'Jack' li:'name'
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
