Yep
100
Devil
False
List ← 'hello' ; 'world' ; True ; Nil ; 666 ; 1
(Map new) put:Nil at:Nil
668
Error noted: Must return a string.
Error noted: Must return a number.
Error noted: Must return a boolean.
Error noted: Must return a string.
Error noted: Must return a number.
Error noted: Must return a boolean.
Error noted: Must return a string.
Error noted: Must return a number.
Error noted: Must return a boolean.
Error noted: Must return a string.
Error noted: Must return a number.
Error noted: Must return a boolean.
