Néant
Néant
Booléen
Vrai
Booléen
Faux
Nombre
1
Nombre
-3
Nombre
9,2
Nombre
-9,2
Liste
Liste nouveau 
Liste
Liste ← 1 ; 2
Liste
Liste ← 1 ; (Liste ← 2)
Liste
Liste ← 1 ; (Liste ← 2) ; 3
Liste
Liste ← 1 ; ((Carte nouveau) mettre:‘a’ _à:‘b’) ; 3
Liste
Liste ← 1 ; ((Carte nouveau) mettre:(Liste ← 9) _à:‘b’) ; 3
Carte
(Carte nouveau) mettre:2 _à:‘1’
Carte
(Carte nouveau) mettre:2 _à:‘x’
Carte
(Carte nouveau) mettre:(Liste ← 1 ; 2) _à:‘x’
Carte
(Carte nouveau) mettre:(Liste ← ((Carte nouveau) mettre:‘q’ _à:‘y’) ; 2) _à:‘x’
Néant
Néant
