There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falsk
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Noll meters long.
Luckily, this day, there are Noll wasps in the garden.
The dog named Noll sleeps under the tree.
a\"bb\"ccc\"
(Karta ny) sätta vid:((Karta ny) sätta vid:Noll __:dog, sätta vid:Noll __:insects, sätta vid:((Karta ny) sätta vid:15 __:‘length’, sätta vid:8 __:‘width’) __:‘size’, sätta vid:(Lista ← ‘tulips’ ; ‘roses’ ; ‘lillies’) __:‘flower’, sätta vid:Falsk __:‘shed’, sätta vid:Sann __:‘pool’, sätta vid:2 __:‘chairs’) __:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
