There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. פאַלש
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is ניל meters long.
Luckily, this day, there are ניל wasps in the garden.
The dog named ניל sleeps under the tree.
a\"bb\"ccc\"
(מאפע נייַ) שטעלן:((מאפע נייַ) שטעלן:ניל אין:dog, שטעלן:ניל אין:insects, שטעלן:((מאפע נייַ) שטעלן:15 אין:'length', שטעלן:8 אין:'width') אין:'size', שטעלן:(רשימה ← 'tulips' ; 'roses' ; 'lillies') אין:'flower', שטעלן:פאַלש אין:'shed', שטעלן:אמת אין:'pool', שטעלן:2 אין:'chairs') אין:'garden'
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
