Nil
Nil
Boole
True
Boole
Onwaar
Aantal
1
Aantal
-3
Aantal
9,2
Aantal
-9,2
Lys
Lys nuwe 
Lys
Lys ← 1 ; 2
Lys
Lys ← 1 ; (Lys ← 2)
Lys
Lys ← 1 ; (Lys ← 2) ; 3
Lys
Lys ← 1 ; ((Kaart nuwe) sit by:‘a’ __:‘b’) ; 3
Lys
Lys ← 1 ; ((Kaart nuwe) sit by:(Lys ← 9) __:‘b’) ; 3
Kaart
(Kaart nuwe) sit by:2 __:‘1’
Kaart
(Kaart nuwe) sit by:2 __:‘x’
Kaart
(Kaart nuwe) sit by:(Lys ← 1 ; 2) __:‘x’
Kaart
(Kaart nuwe) sit by:(Lys ← ((Kaart nuwe) sit by:‘q’ __:‘y’) ; 2) __:‘x’
Nil
Nil
