There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falsk
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Kort ny) sætte:((Kort ny) sætte:Nil på:dog, sætte:Nil på:insects, sætte:((Kort ny) sætte:15 på:‘length’, sætte:8 på:‘width’) på:‘size’, sætte:(Liste ← ‘tulips’ ; ‘roses’ ; ‘lillies’) på:‘flower’, sætte:Falsk på:‘shed’, sætte:Rigtigt på:‘pool’, sætte:2 på:‘chairs’) på:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
