(Dict new) put:['a"b'] at:['test']
Invalid JSON.
(Dict new) put:(List ← 1 ; 2 ; (List ← 3 ; 4) ; ((Dict new) put:(List ← 3 ; 4) at:['bar'], put:1 at:['foo'])) at:['nested'], put:False at:['legend'], put:27 at:['age'], put:['Jack'] at:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
