None
None
Bool
True
Bool
False
Number
1
Number
-3
Number
9.2
Number
-9.2
List
List new 
List
List ← 1 ; 2
List
List ← 1 ; (List ← 2)
List
List ← 1 ; (List ← 2) ; 3
List
List ← 1 ; ((Dict new) put:['a'] at:['b']) ; 3
List
List ← 1 ; ((Dict new) put:(List ← 9) at:['b']) ; 3
Dict
(Dict new) put:2 at:['1']
Dict
(Dict new) put:2 at:['x']
Dict
(Dict new) put:(List ← 1 ; 2) at:['x']
Dict
(Dict new) put:(List ← ((Dict new) put:['q'] at:['y']) ; 2) at:['x']
None
None