Break for-loop, 0-4.
iteration #1
iteration #2
iteration #3
iteration #4
Break while-true loop, 0-4.
iteration #0
iteration #1
iteration #2
iteration #3
iteration #4
Break while-false loop, 5,4.
iteration #5
iteration #4
Break times loop, 1-4.
iteration #1
iteration #2
iteration #3
iteration #4
Break block, dont print line.
Break block, dont fire catch...
Test Array each-loop: 0,1
iteration #1
Test Map each-loop: c only
iterationfirsta
