Nula
Nula
Booleova
Pravi
Booleova
Lažan
Broj
1
Broj
-3
Broj
9,2
Broj
-9,2
Popis
Popis novi 
Popis
Popis ← 1 ; 2
Popis
Popis ← 1 ; (Popis ← 2)
Popis
Popis ← 1 ; (Popis ← 2) ; 3
Popis
Popis ← 1 ; ((Karta novi) staviti:‘a’ na:‘b’) ; 3
Popis
Popis ← 1 ; ((Karta novi) staviti:(Popis ← 9) na:‘b’) ; 3
Karta
(Karta novi) staviti:2 na:‘1’
Karta
(Karta novi) staviti:2 na:‘x’
Karta
(Karta novi) staviti:(Popis ← 1 ; 2) na:‘x’
Karta
(Karta novi) staviti:(Popis ← ((Karta novi) staviti:‘q’ na:‘y’) ; 2) na:‘x’
Nula
Nula
