Ništa
Ništa
Da-ili-Ne
Da
Da-ili-Ne
Ne
Broj
1
Broj
-3
Broj
9,2
Broj
-9,2
Serija
Serija novi 
Serija
Serija ← 1 ; 2
Serija
Serija ← 1 ; (Serija ← 2)
Serija
Serija ← 1 ; (Serija ← 2) ; 3
Serija
Serija ← 1 ; ((Popis novi) staviti:['a'] na:['b']) ; 3
Serija
Serija ← 1 ; ((Popis novi) staviti:(Serija ← 9) na:['b']) ; 3
Popis
(Popis novi) staviti:2 na:['1']
Popis
(Popis novi) staviti:2 na:['x']
Popis
(Popis novi) staviti:(Serija ← 1 ; 2) na:['x']
Popis
(Popis novi) staviti:(Serija ← ((Popis novi) staviti:['q'] na:['y']) ; 2) na:['x']
Ništa
Ništa