(Rarangi hou) ahanoa:‘a"b’ wahi:‘test’
Invalid JSON.
(Rarangi hou) ahanoa:(Raupapa ← 1 ; 2 ; (Raupapa ← 3 ; 4) ; ((Rarangi hou) ahanoa:(Raupapa ← 3 ; 4) wahi:‘bar’, ahanoa:1 wahi:‘foo’)) wahi:‘nested’, ahanoa:Kahore wahi:‘legend’, ahanoa:27 wahi:‘age’, ahanoa:‘Jack’ wahi:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld