Nil
Nil
Poei
Pono
Poei
Horihori
Tau
1
Tau
-3
Tau
9,2
Tau
-9,2
Raarangi
Raarangi hou 
Raarangi
Raarangi ← 1 ; 2
Raarangi
Raarangi ← 1 ; (Raarangi ← 2)
Raarangi
Raarangi ← 1 ; (Raarangi ← 2) ; 3
Raarangi
Raarangi ← 1 ; ((Mahere hou) tuu:‘a’ _i:‘b’) ; 3
Raarangi
Raarangi ← 1 ; ((Mahere hou) tuu:(Raarangi ← 9) _i:‘b’) ; 3
Mahere
(Mahere hou) tuu:2 _i:‘1’
Mahere
(Mahere hou) tuu:2 _i:‘x’
Mahere
(Mahere hou) tuu:(Raarangi ← 1 ; 2) _i:‘x’
Mahere
(Mahere hou) tuu:(Raarangi ← ((Mahere hou) tuu:‘q’ _i:‘y’) ; 2) _i:‘x’
Nil
Nil
