Kau
Kau
Ae/Kahore
Ae
Ae/Kahore
Kahore
Tau
1
Tau
-3
Tau
9,2
Tau
-9,2
Raupapa
Raupapa hou 
Raupapa
Raupapa ← 1 ; 2
Raupapa
Raupapa ← 1 ; (Raupapa ← 2)
Raupapa
Raupapa ← 1 ; (Raupapa ← 2) ; 3
Raupapa
Raupapa ← 1 ; ((Rarangi hou) ahanoa:‘a’ wahi:‘b’) ; 3
Raupapa
Raupapa ← 1 ; ((Rarangi hou) ahanoa:(Raupapa ← 9) wahi:‘b’) ; 3
Rarangi
(Rarangi hou) ahanoa:2 wahi:‘1’
Rarangi
(Rarangi hou) ahanoa:2 wahi:‘x’
Rarangi
(Rarangi hou) ahanoa:(Raupapa ← 1 ; 2) wahi:‘x’
Rarangi
(Rarangi hou) ahanoa:(Raupapa ← ((Rarangi hou) ahanoa:‘q’ wahi:‘y’) ; 2) wahi:‘x’
Kau
Kau