(Mapa nový) dát:‘a"b’ na:‘test’
Invalid JSON.
(Mapa nový) dát:(Seznam ← 1 ; 2 ; (Seznam ← 3 ; 4) ; ((Mapa nový) dát:(Seznam ← 3 ; 4) na:‘bar’, dát:1 na:‘foo’)) na:‘nested’, dát:Nepravdivé na:‘legend’, dát:27 na:‘age’, dát:‘Jack’ na:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
