Nic
Nic
Boolean
Pravda
Boolean
Nepravda
Číslo
1
Číslo
-3
Číslo
9,2
Číslo
-9,2
Seznam
Seznam nový 
Seznam
Seznam ← 1 ; 2
Seznam
Seznam ← 1 ; (Seznam ← 2)
Seznam
Seznam ← 1 ; (Seznam ← 2) ; 3
Seznam
Seznam ← 1 ; ((Mapa nový) umístit:„a” na:„b”) ; 3
Seznam
Seznam ← 1 ; ((Mapa nový) umístit:(Seznam ← 9) na:„b”) ; 3
Mapa
(Mapa nový) umístit:2 na:„1”
Mapa
(Mapa nový) umístit:2 na:„x”
Mapa
(Mapa nový) umístit:(Seznam ← 1 ; 2) na:„x”
Mapa
(Mapa nový) umístit:(Seznam ← ((Mapa nový) umístit:„q” na:„y”) ; 2) na:„x”
Nic
Nic
