(Tarree haaraa) kaa'i:['a"b'] bakka:['test']
Invalid JSON.
(Tarree haaraa) kaa'i:(Walduraa-duuba ← 1 ; 2 ; (Walduraa-duuba ← 3 ; 4) ; ((Tarree haaraa) kaa'i:(Walduraa-duuba ← 3 ; 4) bakka:['bar'], kaa'i:1 bakka:['foo'])) bakka:['nested'], kaa'i:Soba bakka:['legend'], kaa'i:27 bakka:['age'], kaa'i:['Jack'] bakka:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld