Homaa
Homaa
Dhugaa-Sobaa
Dhugaa
Dhugaa-Sobaa
Soba
Lakkoofsa
1
Lakkoofsa
-3
Lakkoofsa
9.2
Lakkoofsa
-9.2
Walduraa-duuba
Walduraa-duuba haaraa 
Walduraa-duuba
Walduraa-duuba ← 1 ; 2
Walduraa-duuba
Walduraa-duuba ← 1 ; (Walduraa-duuba ← 2)
Walduraa-duuba
Walduraa-duuba ← 1 ; (Walduraa-duuba ← 2) ; 3
Walduraa-duuba
Walduraa-duuba ← 1 ; Homaa ; 3
Walduraa-duuba
Walduraa-duuba ← 1 ; Homaa ; 3
Homaa
Homaa
Homaa
Homaa
Homaa
Homaa
Homaa
Homaa
Homaa
Homaa