There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Soba
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Homaa meters long.
Luckily, this day, there are Homaa wasps in the garden.
The dog named Homaa sleeps under the tree.
a\"bb\"ccc\"
(Tarree haaraa) kaa'i:((Tarree haaraa) kaa'i:Homaa bakka:['dog'], kaa'i:Homaa bakka:['insects'], kaa'i:((Tarree haaraa) kaa'i:15 bakka:['length'], kaa'i:8 bakka:['width']) bakka:['size'], kaa'i:(Walduraa-duuba ← ['tulips'] ; ['roses'] ; ['lillies']) bakka:['flower'], kaa'i:Soba bakka:['shed'], kaa'i:Dhugaa bakka:['pool'], kaa'i:2 bakka:['chairs']) bakka:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}