Nil
Nil
Boolean
Verum
Boolean
Falsus
Numerus
1
Numerus
-3
Numerus
9,2
Numerus
-9,2
Album
Album novus 
Album
Album ← 1 ; 2
Album
Album ← 1 ; (Album ← 2)
Album
Album ← 1 ; (Album ← 2) ; 3
Album
Album ← 1 ; ((Map novus) posuit:‘a’ at:‘b’) ; 3
Album
Album ← 1 ; ((Map novus) posuit:(Album ← 9) at:‘b’) ; 3
Map
(Map novus) posuit:2 at:‘1’
Map
(Map novus) posuit:2 at:‘x’
Map
(Map novus) posuit:(Album ← 1 ; 2) at:‘x’
Map
(Map novus) posuit:(Album ← ((Map novus) posuit:‘q’ at:‘y’) ; 2) at:‘x’
Nil
Nil
