(Map novus) ponere:‘a"b’ cum:‘test’
Invalid JSON.
(Map novus) ponere:(Album ← 1 ; 2 ; (Album ← 3 ; 4) ; ((Map novus) ponere:(Album ← 3 ; 4) cum:‘bar’, ponere:1 cum:‘foo’)) cum:‘nested’, ponere:Falsus cum:‘legend’, ponere:27 cum:‘age’, ponere:‘Jack’ cum:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld