Nihil
Nihil
Veritas
Verum
Veritas
Falsus
Numerus
1
Numerus
-3
Numerus
9,2
Numerus
-9,2
Album
Album novus 
Album
Album ← 1 ; 2
Album
Album ← 1 ; (Album ← 2)
Album
Album ← 1 ; (Album ← 2) ; 3
Album
Album ← 1 ; ((Map novus) ponere:‘a’ cum:‘b’) ; 3
Album
Album ← 1 ; ((Map novus) ponere:(Album ← 9) cum:‘b’) ; 3
Map
(Map novus) ponere:2 cum:‘1’
Map
(Map novus) ponere:2 cum:‘x’
Map
(Map novus) ponere:(Album ← 1 ; 2) cum:‘x’
Map
(Map novus) ponere:(Album ← ((Map novus) ponere:‘q’ cum:‘y’) ; 2) cum:‘x’
Nihil
Nihil