There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Vale
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Tühi meters long.
Luckily, this day, there are Tühi wasps in the garden.
The dog named Tühi sleeps under the tree.
a\"bb\"ccc\"
(Nimekiri uus) panna:((Nimekiri uus) panna:Tühi juures:‘dog’, panna:Tühi juures:‘insects’, panna:((Nimekiri uus) panna:15 juures:‘length’, panna:8 juures:‘width’) juures:‘size’, panna:(Seeria ← ‘tulips’ ; ‘roses’ ; ‘lillies’) juures:‘flower’, panna:Vale juures:‘shed’, panna:Tõsi juures:‘pool’, panna:2 juures:‘chairs’) juures:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}