(Kaart uus) panna:‘a"b’ juures:‘test’
Invalid JSON.
(Kaart uus) panna:(Loend ← 1 ; 2 ; (Loend ← 3 ; 4) ; ((Kaart uus) panna:(Loend ← 3 ; 4) juures:‘bar’, panna:1 juures:‘foo’)) juures:‘nested’, panna:Vale juures:‘legend’, panna:27 juures:‘age’, panna:‘Jack’ juures:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
