(Liste neu) setzen:‘a"b’ auf:‘test’
Invalid JSON.
(Liste neu) setzen:(Serie ← 1 ; 2 ; (Serie ← 3 ; 4) ; ((Liste neu) setzen:(Serie ← 3 ; 4) auf:‘bar’, setzen:1 auf:‘foo’)) auf:‘nested’, setzen:Nein auf:‘legend’, setzen:27 auf:‘age’, setzen:‘Jack’ auf:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
