There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Nein
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nichts meters long.
Luckily, this day, there are Nichts wasps in the garden.
The dog named Nichts sleeps under the tree.
a\"bb\"ccc\"
(Liste neu) setzen:((Liste neu) setzen:Nichts auf:»dog«, setzen:Nichts auf:»insects«, setzen:((Liste neu) setzen:15 auf:»length«, setzen:8 auf:»width«) auf:»size«, setzen:(Serie ← »tulips« ; »roses« ; »lillies«) auf:»flower«, setzen:Nein auf:»shed«, setzen:Ja auf:»pool«, setzen:2 auf:»chairs«) auf:»garden«
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}