Nichts
Nichts
Ja-oder-Nein
Ja
Ja-oder-Nein
Nein
Zahl
1
Zahl
-3
Zahl
9,2
Zahl
-9,2
Serie
Serie neu 
Serie
Serie ← 1 ; 2
Serie
Serie ← 1 ; (Serie ← 2)
Serie
Serie ← 1 ; (Serie ← 2) ; 3
Serie
Serie ← 1 ; ((Liste neu) setzen:['a'] auf:['b']) ; 3
Serie
Serie ← 1 ; ((Liste neu) setzen:(Serie ← 9) auf:['b']) ; 3
Liste
(Liste neu) setzen:2 auf:['1']
Liste
(Liste neu) setzen:2 auf:['x']
Liste
(Liste neu) setzen:(Serie ← 1 ; 2) auf:['x']
Liste
(Liste neu) setzen:(Serie ← ((Liste neu) setzen:['q'] auf:['y']) ; 2) auf:['x']
Nichts
Nichts