(စာရင်း အသစ်) ရွှေ့:['a"b'] သို့:['test']
Invalid JSON.
(စာရင်း အသစ်) ရွှေ့:(စီးရီး ← 1 ; 2 ; (စီးရီး ← 3 ; 4) ; ((စာရင်း အသစ်) ရွှေ့:(စီးရီး ← 3 ; 4) သို့:['bar'], ရွှေ့:1 သို့:['foo'])) သို့:['nested'], ရွှေ့:မဟုတ်ဘူး သို့:['legend'], ရွှေ့:27 သို့:['age'], ရွှေ့:['Jack'] သို့:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld