Nil
Nil
Boole
True
Boole
Onwaar
Aantal
1
Aantal
-3
Aantal
9,2
Aantal
-9,2
Lys
Lys nuwe 
Lys
Lys ← 1 ; 2
Lys
Lys ← 1 ; (Lys ← 2)
Lys
Lys ← 1 ; (Lys ← 2) ; 3
Lys
Lys ← 1 ; ((Kaart nuwe) sit:‘a’ by:‘b’) ; 3
Lys
Lys ← 1 ; ((Kaart nuwe) sit:(Lys ← 9) by:‘b’) ; 3
Kaart
(Kaart nuwe) sit:2 by:‘1’
Kaart
(Kaart nuwe) sit:2 by:‘x’
Kaart
(Kaart nuwe) sit:(Lys ← 1 ; 2) by:‘x’
Kaart
(Kaart nuwe) sit:(Lys ← ((Kaart nuwe) sit:‘q’ by:‘y’) ; 2) by:‘x’
Nil
Nil
