Nil
Nil
Boolean
True
Boolean
False
Number
1
Number
-3
Number
9.2
Number
-9.2
List
List new 
List
List ← 1 ; 2
List
List ← 1 ; (List ← 2)
List
List ← 1 ; (List ← 2) ; 3
List
List ← 1 ; ((Map new) put:‘a’ at:‘b’) ; 3
List
List ← 1 ; ((Map new) put:(List ← 9) at:‘b’) ; 3
Map
(Map new) put:2 at:‘1’
Map
(Map new) put:2 at:‘x’
Map
(Map new) put:(List ← 1 ; 2) at:‘x’
Map
(Map new) put:(List ← ((Map new) put:‘q’ at:‘y’) ; 2) at:‘x’
Nil
Nil
