None
None
Boolean
Yes
Boolean
No
Number
1
Number
-3
Number
9.2
Number
-9.2
Sequence
Sequence new 
Sequence
Sequence ← 1 ; 2
Sequence
Sequence ← 1 ; (Sequence ← 2)
Sequence
Sequence ← 1 ; (Sequence ← 2) ; 3
Sequence
Sequence ← 1 ; ((List new) put:['a'] at:['b']) ; 3
Sequence
Sequence ← 1 ; ((List new) put:(Sequence ← 9) at:['b']) ; 3
List
(List new) put:2 at:['1']
List
(List new) put:2 at:['x']
List
(List new) put:(Sequence ← 1 ; 2) at:['x']
List
(List new) put:(Sequence ← ((List new) put:['q'] at:['y']) ; 2) at:['x']
None
None