There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. False
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is 15 meters long.
Luckily, this day, there are None wasps in the garden.
The dog named None sleeps under the tree.
a\"bb\"ccc\"
(List new) put:((List new) put:None at:['dog'], put:None at:['insects'], put:((List new) put:15 at:['length'], put:8 at:['width']) at:['size'], put:(Sequence ← ['tulips'] ; ['roses'] ; ['lillies']) at:['flower'], put:False at:['shed'], put:True at:['pool'], put:2 at:['chairs']) at:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}