There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falso
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Zero meters long.
Luckily, this day, there are Zero wasps in the garden.
The dog named Zero sleeps under the tree.
a\"bb\"ccc\"
(Elenco nuovo) mettere:((Elenco nuovo) mettere:Zero a:‘dog’, mettere:Zero a:‘insects’, mettere:((Elenco nuovo) mettere:15 a:‘length’, mettere:8 a:‘width’) a:‘size’, mettere:(Elenco ← ‘tulips’ ; ‘roses’ ; ‘lillies’) a:‘flower’, mettere:Falso a:‘shed’, mettere:Vero a:‘pool’, mettere:2 a:‘chairs’) a:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}