(Carta geografica nuovo) mettere:‘a"b’ _a:‘test’
Invalid JSON.
(Carta geografica nuovo) mettere:(Elenco ← 1 ; 2 ; (Elenco ← 3 ; 4) ; ((Carta geografica nuovo) mettere:(Elenco ← 3 ; 4) _a:‘bar’, mettere:1 _a:‘foo’)) _a:‘nested’, mettere:Falso _a:‘legend’, mettere:27 _a:‘age’, mettere:‘Jack’ _a:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
