(Карта яңа) куярга:‘a"b’ at:‘test’
Invalid JSON.
(Карта яңа) куярга:(Исемлек ← 1 ; 2 ; (Исемлек ← 3 ; 4) ; ((Карта яңа) куярга:(Исемлек ← 3 ; 4) at:‘bar’, куярга:1 at:‘foo’)) at:‘nested’, куярга:Ялган at:‘legend’, куярга:27 at:‘age’, куярга:‘Jack’ at:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
