(Исемлек яңа) объект:‘a"b’ урын:‘test’
Invalid JSON.
(Исемлек яңа) объект:(Серияләре ← 1 ; 2 ; (Серияләре ← 3 ; 4) ; ((Исемлек яңа) объект:(Серияләре ← 3 ; 4) урын:‘bar’, объект:1 урын:‘foo’)) урын:‘nested’, объект:Ялган урын:‘legend’, объект:27 урын:‘age’, объект:‘Jack’ урын:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld