Nialas
Nialas
Boole
Fíor
Boole
Bréagach
Uimhir
1
Uimhir
-3
Uimhir
9,2
Uimhir
-9,2
Liosta
Liosta nua 
Liosta
Liosta ← 1 ; 2
Liosta
Liosta ← 1 ; (Liosta ← 2)
Liosta
Liosta ← 1 ; (Liosta ← 2) ; 3
Liosta
Liosta ← 1 ; ((Léarscáil nua) put:['a'] at:['b']) ; 3
Liosta
Liosta ← 1 ; ((Léarscáil nua) put:(Liosta ← 9) at:['b']) ; 3
Léarscáil
(Léarscáil nua) put:2 at:['1']
Léarscáil
(Léarscáil nua) put:2 at:['x']
Léarscáil
(Léarscáil nua) put:(Liosta ← 1 ; 2) at:['x']
Léarscáil
(Léarscáil nua) put:(Liosta ← ((Léarscáil nua) put:['q'] at:['y']) ; 2) at:['x']
Nialas
Nialas