There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falso
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nulo meters long.
Luckily, this day, there are Nulo wasps in the garden.
The dog named Nulo sleeps under the tree.
a\"bb\"ccc\"
(Mapa novo) colocar:((Mapa novo) colocar:Nulo em:“dog”, colocar:Nulo em:“insects”, colocar:((Mapa novo) colocar:15 em:“length”, colocar:8 em:“width”) em:“size”, colocar:(Listar ← “tulips” ; “roses” ; “lillies”) em:“flower”, colocar:Falso em:“shed”, colocar:Verdadeiro em:“pool”, colocar:2 em:“chairs”) em:“garden”
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}