Nulle
Nulle
Būla
Patiesībā
Būla
Viltus
Skaits
1
Skaits
-3
Skaits
9,2
Skaits
-9,2
Saraksts
Saraksts jauns 
Saraksts
Saraksts ← 1 ; 2
Saraksts
Saraksts ← 1 ; (Saraksts ← 2)
Saraksts
Saraksts ← 1 ; (Saraksts ← 2) ; 3
Saraksts
Saraksts ← 1 ; ((Karte jauns) ievietot:‘a’ pie:‘b’) ; 3
Saraksts
Saraksts ← 1 ; ((Karte jauns) ievietot:(Saraksts ← 9) pie:‘b’) ; 3
Karte
(Karte jauns) ievietot:2 pie:‘1’
Karte
(Karte jauns) ievietot:2 pie:‘x’
Karte
(Karte jauns) ievietot:(Saraksts ← 1 ; 2) pie:‘x’
Karte
(Karte jauns) ievietot:(Saraksts ← ((Karte jauns) ievietot:‘q’ pie:‘y’) ; 2) pie:‘x’
Nulle
Nulle
