There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Viltus
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nulle meters long.
Luckily, this day, there are Nulle wasps in the garden.
The dog named Nulle sleeps under the tree.
a\"bb\"ccc\"
(Karte jauns) ievietot:((Karte jauns) ievietot:Nulle pie:‘dog’, ievietot:Nulle pie:‘insects’, ievietot:((Karte jauns) ievietot:15 pie:‘length’, ievietot:8 pie:‘width’) pie:‘size’, ievietot:(Saraksts ← ‘tulips’ ; ‘roses’ ; ‘lillies’) pie:‘flower’, ievietot:Viltus pie:‘shed’, ievietot:Patiesībā pie:‘pool’, ievietot:2 pie:‘chairs’) pie:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
