(Map naujas) įdėti:['a"b'] _į:['test']
Invalid JSON.
(Map naujas) įdėti:(Sąrašas ← 1 ; 2 ; (Sąrašas ← 3 ; 4) ; ((Map naujas) įdėti:(Sąrašas ← 3 ; 4) _į:['bar'], įdėti:1 _į:['foo'])) _į:['nested'], įdėti:Netiesa _į:['legend'], įdėti:27 _į:['age'], įdėti:['Jack'] _į:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld