Hapana
Hapana
Chisarudzo
Ehe
Chisarudzo
Aihwa
Nhamba
1
Nhamba
-3
Nhamba
9,2
Nhamba
-9,2
Rondedzero
Rondedzero nyowani 
Rondedzero
Rondedzero ← 1 ; 2
Rondedzero
Rondedzero ← 1 ; (Rondedzero ← 2)
Rondedzero
Rondedzero ← 1 ; (Rondedzero ← 2) ; 3
Rondedzero
Rondedzero ← 1 ; ((Mepu nyowani) isa:‘a’ pa:‘b’) ; 3
Rondedzero
Rondedzero ← 1 ; ((Mepu nyowani) isa:(Rondedzero ← 9) pa:‘b’) ; 3
Mepu
(Mepu nyowani) isa:2 pa:‘1’
Mepu
(Mepu nyowani) isa:2 pa:‘x’
Mepu
(Mepu nyowani) isa:(Rondedzero ← 1 ; 2) pa:‘x’
Mepu
(Mepu nyowani) isa:(Rondedzero ← ((Mepu nyowani) isa:‘q’ pa:‘y’) ; 2) pa:‘x’
Hapana
Hapana