There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. തെറ്റായ
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is ഇല്ല meters long.
Luckily, this day, there are ഇല്ല wasps in the garden.
The dog named ഇല്ല sleeps under the tree.
a\"bb\"ccc\"
(മാപ്പ് പുതിയത്) വസ്തു:((മാപ്പ് പുതിയത്) വസ്തു:ഇല്ല സ്ഥാനം:['dog'], വസ്തു:ഇല്ല സ്ഥാനം:['insects'], വസ്തു:((മാപ്പ് പുതിയത്) വസ്തു:15 സ്ഥാനം:['length'], വസ്തു:8 സ്ഥാനം:['width']) സ്ഥാനം:['size'], വസ്തു:(പട്ടിക ← ['tulips'] ; ['roses'] ; ['lillies']) സ്ഥാനം:['flower'], വസ്തു:തെറ്റായ സ്ഥാനം:['shed'], വസ്തു:ശരിയാണ് സ്ഥാനം:['pool'], വസ്തു:2 സ്ഥാനം:['chairs']) സ്ഥാനം:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}