Nau
Nau
Boolean
Kūpono
Boolean
Hoʻolaha
Helu
1
Helu
-3
Helu
9,2
Helu
-9,2
Palapala
Palapala hou 
Palapala
Palapala ← 1 ; 2
Palapala
Palapala ← 1 ; (Palapala ← 2)
Palapala
Palapala ← 1 ; (Palapala ← 2) ; 3
Palapala
Palapala ← 1 ; ((Mua hou) waiho:‘a’ ma:‘b’) ; 3
Palapala
Palapala ← 1 ; ((Mua hou) waiho:(Palapala ← 9) ma:‘b’) ; 3
Mua
(Mua hou) waiho:2 ma:‘1’
Mua
(Mua hou) waiho:2 ma:‘x’
Mua
(Mua hou) waiho:(Palapala ← 1 ; 2) ma:‘x’
Mua
(Mua hou) waiho:(Palapala ← ((Mua hou) waiho:‘q’ ma:‘y’) ; 2) ma:‘x’
Nau
Nau
