Nau
Nau
Boolean
Kūpono
Boolean
Hoʻolaha
Helu
1
Helu
-3
Helu
9,2
Helu
-9,2
Moʻo
Moʻo hou 
Moʻo
Moʻo ← 1 ; 2
Moʻo
Moʻo ← 1 ; (Moʻo ← 2)
Moʻo
Moʻo ← 1 ; (Moʻo ← 2) ; 3
Moʻo
Moʻo ← 1 ; ((Papa-inoa hou) waiho:['a'] ma:['b']) ; 3
Moʻo
Moʻo ← 1 ; ((Papa-inoa hou) waiho:(Moʻo ← 9) ma:['b']) ; 3
Papa-inoa
(Papa-inoa hou) waiho:2 ma:['1']
Papa-inoa
(Papa-inoa hou) waiho:2 ma:['x']
Papa-inoa
(Papa-inoa hou) waiho:(Moʻo ← 1 ; 2) ma:['x']
Papa-inoa
(Papa-inoa hou) waiho:(Moʻo ← ((Papa-inoa hou) waiho:['q'] ma:['y']) ; 2) ma:['x']
Nau
Nau