(Mapa novo) colocar:“a"b” em:“test”
Invalid JSON.
(Mapa novo) colocar:(Listar ← 1 ; 2 ; (Listar ← 3 ; 4) ; ((Mapa novo) colocar:(Listar ← 3 ; 4) em:“bar”, colocar:1 em:“foo”)) em:“nested”, colocar:Falso em:“legend”, colocar:27 em:“age”, colocar:“Jack” em:“name”
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
