There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Hindi
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Wala meters long.
Luckily, this day, there are Wala wasps in the garden.
The dog named Wala sleeps under the tree.
a\"bb\"ccc\"
(Map bago) ilagay:((Map bago) ilagay:Wala sa:‘dog’, ilagay:Wala sa:‘insects’, ilagay:((Map bago) ilagay:15 sa:‘length’, ilagay:8 sa:‘width’) sa:‘size’, ilagay:(Listahan ← ‘tulips’ ; ‘roses’ ; ‘lillies’) sa:‘flower’, ilagay:Hindi sa:‘shed’, ilagay:Oo sa:‘pool’, ilagay:2 sa:‘chairs’) sa:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}