(Sách mới) đặt:‘a"b’ tại:‘test’
Invalid JSON.
(Sách mới) đặt:(Loạt ← 1 ; 2 ; (Loạt ← 3 ; 4) ; ((Sách mới) đặt:(Loạt ← 3 ; 4) tại:‘bar’, đặt:1 tại:‘foo’)) tại:‘nested’, đặt:Sai tại:‘legend’, đặt:27 tại:‘age’, đặt:‘Jack’ tại:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld