There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Үгүй
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Нил meters long.
Luckily, this day, there are Нил wasps in the garden.
The dog named Нил sleeps under the tree.
a\"bb\"ccc\"
(Жагсаалт шинэ) объект:((Жагсаалт шинэ) объект:Нил байршил:‘dog’, объект:Нил байршил:‘insects’, объект:((Жагсаалт шинэ) объект:15 байршил:‘length’, объект:8 байршил:‘width’) байршил:‘size’, объект:(Цуврал ← ‘tulips’ ; ‘roses’ ; ‘lillies’) байршил:‘flower’, объект:Үгүй байршил:‘shed’, объект:Тиймээ байршил:‘pool’, объект:2 байршил:‘chairs’) байршил:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}