(Жагсаалт шинэ) объект:['a"b'] байршил:['test']
Invalid JSON.
(Жагсаалт шинэ) объект:(Цуврал ← 1 ; 2 ; (Цуврал ← 3 ; 4) ; ((Жагсаалт шинэ) объект:(Цуврал ← 3 ; 4) байршил:['bar'], объект:1 байршил:['foo'])) байршил:['nested'], объект:Үгүй байршил:['legend'], объект:27 байршил:['age'], объект:['Jack'] байршил:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld