Nil
Nil
Boolov
Prav
Boolov
Lažno
Številka
1
Številka
-3
Številka
9,2
Številka
-9,2
Seznam
Seznam novo 
Seznam
Seznam ← 1 ; 2
Seznam
Seznam ← 1 ; (Seznam ← 2)
Seznam
Seznam ← 1 ; (Seznam ← 2) ; 3
Seznam
Seznam ← 1 ; ((Zemljevid novo) dal:['a'] na:['b']) ; 3
Seznam
Seznam ← 1 ; ((Zemljevid novo) dal:(Seznam ← 9) na:['b']) ; 3
Zemljevid
(Zemljevid novo) dal:2 na:['1']
Zemljevid
(Zemljevid novo) dal:2 na:['x']
Zemljevid
(Zemljevid novo) dal:(Seznam ← 1 ; 2) na:['x']
Zemljevid
(Zemljevid novo) dal:(Seznam ← ((Zemljevid novo) dal:['q'] na:['y']) ; 2) na:['x']
Nil
Nil