(Faʻafanua fou) tuʻu:‘a"b’ i:‘test’
Invalid JSON.
(Faʻafanua fou) tuʻu:(Lisi ← 1 ; 2 ; (Lisi ← 3 ; 4) ; ((Faʻafanua fou) tuʻu:(Lisi ← 3 ; 4) i:‘bar’, tuʻu:1 i:‘foo’)) i:‘nested’, tuʻu:Sese i:‘legend’, tuʻu:27 i:‘age’, tuʻu:‘Jack’ i:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld