(지도 새로운) 넣어 :‘a"b’ at :‘test’
Invalid JSON.
(지도 새로운) 넣어 :(명부 ← 1 ; 2 ; (명부 ← 3 ; 4) ; ((지도 새로운) 넣어 :(명부 ← 3 ; 4) at :‘bar’, 넣어 :1 at :‘foo’)) at :‘nested’, 넣어 :그릇된 at :‘legend’, 넣어 :27 at :‘age’, 넣어 :‘Jack’ at :‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Unescape
hello\tworld
"hello world"
a"b
hello	world
hello
world
hello	wo
rld
hello		wo

rld
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
