There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. 아니요
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is 무효 meters long.
Luckily, this day, there are 무효 wasps in the garden.
The dog named 무효 sleeps under the tree.
a\"bb\"ccc\"
(지도 새로운) 협회:((지도 새로운) 협회:무효 와:‘dog’, 협회:무효 와:‘insects’, 협회:((지도 새로운) 협회:15 와:‘length’, 협회:8 와:‘width’) 와:‘size’, 협회:(명부 ← ‘tulips’ ; ‘roses’ ; ‘lillies’) 와:‘flower’, 협회:아니요 와:‘shed’, 협회:예 와:‘pool’, 협회:2 와:‘chairs’) 와:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}