LDFLAGS= -shared
CFLAGS= -D WIN

all:libctrmedia.dll

install-libctrmedia.dll: libctrmedia.dll
	install libctrmedia.dll ../../mods/media/

libctrmedia.dll: media.o
	$(CC) ${LDFLAGS}  media.o -lSDL2 -lSDL2_image -lSDL2_ttf ../../ctr${ISO}import.lib -o libctrmedia.dll

media.o:
	$(CC) ${CFLAGS} -I /usr/include/SDL2 -I ../../i18n/${ISO} -I i18n/${ISO} -c media.c -Wall -Werror -fPIC -o media.o

clean:
	rm media.o