LDFLAGS= -shared

install-libctrmedia.so: libctrmedia.so
	install libctrmedia.so ../../mods/media/

libctrmedia.so: media.o
	ld ${LDFLAGS} -o libctrmedia.so media.o

media.o:
	cc -D MOCK $(EXTRACFLAGS) -I . -c media.c -I ../../i18n/${ISO} -I i18n/${ISO} -Wall -Werror -fPIC -o media.o

clean:
	rm -rf libctrmedia.so
	rm -rf *.o
