There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falsk
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Tömma meters long.
Luckily, this day, there are Tömma wasps in the garden.
The dog named Tömma sleeps under the tree.
a\"bb\"ccc\"
(Lista ny) sätta((Lista ny) sättaTömma vid:‘dog’, sättaTömma vid:‘insects’, sätta((Lista ny) sätta15 vid:‘length’, sätta8 vid:‘width’) vid:‘size’, sätta(Serie ← ‘tulips’ ; ‘roses’ ; ‘lillies’) vid:‘flower’, sättaFalsk vid:‘shed’, sättaSann vid:‘pool’, sätta2 vid:‘chairs’) vid:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}