Nil
Nil
Boolean
Vrè
Boolean
Fo
Nimewo
1
Nimewo
-3
Nimewo
9,2
Nimewo
-9,2
Lis
Lis nouvo 
Lis
Lis ← 1 ; 2
Lis
Lis ← 1 ; (Lis ← 2)
Lis
Lis ← 1 ; (Lis ← 2) ; 3
Lis
Lis ← 1 ; ((Kat nouvo) mete:['a'] nan:['b']) ; 3
Lis
Lis ← 1 ; ((Kat nouvo) mete:(Lis ← 9) nan:['b']) ; 3
Kat
(Kat nouvo) mete:2 nan:['1']
Kat
(Kat nouvo) mete:2 nan:['x']
Kat
(Kat nouvo) mete:(Lis ← 1 ; 2) nan:['x']
Kat
(Kat nouvo) mete:(Lis ← ((Kat nouvo) mete:['q'] nan:['y']) ; 2) nan:['x']
Nil
Nil