(خريطة جديد) ضع:‘a"b’ في:‘test’
Invalid JSON.
(خريطة جديد) ضع:(قائمة ← 1 ; 2 ; (قائمة ← 3 ; 4) ; ((خريطة جديد) ضع:(قائمة ← 3 ; 4) في:‘bar’, ضع:1 في:‘foo’)) في:‘nested’, ضع:لا في:‘legend’, ضع:27 في:‘age’, ضع:‘Jack’ في:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld