There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. لا
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is فارغة meters long.
Luckily, this day, there are فارغة wasps in the garden.
The dog named فارغة sleeps under the tree.
a\"bb\"ccc\"
(خريطة جديد) ضع:((خريطة جديد) ضع:فارغة في:['dog'], ضع:فارغة في:['insects'], ضع:((خريطة جديد) ضع:15 في:['length'], ضع:8 في:['width']) في:['size'], ضع:(قائمة ← ['tulips'] ; ['roses'] ; ['lillies']) في:['flower'], ضع:لا في:['shed'], ضع:نعم في:['pool'], ضع:2 في:['chairs']) في:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}