Tømme
Tømme
Boolean
Rigtigt
Boolean
Falsk
Nummer
1
Nummer
-3
Nummer
9,2
Nummer
-9,2
Række
Række ny 
Række
Række ← 1 ; 2
Række
Række ← 1 ; (Række ← 2)
Række
Række ← 1 ; (Række ← 2) ; 3
Række
Række ← 1 ; ((Liste ny) sætte:‘a’ på:‘b’) ; 3
Række
Række ← 1 ; ((Liste ny) sætte:(Række ← 9) på:‘b’) ; 3
Liste
(Liste ny) sætte:2 på:‘1’
Liste
(Liste ny) sætte:2 på:‘x’
Liste
(Liste ny) sætte:(Række ← 1 ; 2) på:‘x’
Liste
(Liste ny) sætte:(Række ← ((Liste ny) sætte:‘q’ på:‘y’) ; 2) på:‘x’
Tømme
Tømme