There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falsk
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Tømme meters long.
Luckily, this day, there are Tømme wasps in the garden.
The dog named Tømme sleeps under the tree.
a\"bb\"ccc\"
(Liste ny) sætte:((Liste ny) sætte:Tømme på:['dog'], sætte:Tømme på:['insects'], sætte:((Liste ny) sætte:15 på:['length'], sætte:8 på:['width']) på:['size'], sætte:(Række ← ['tulips'] ; ['roses'] ; ['lillies']) på:['flower'], sætte:Falsk på:['shed'], sætte:Rigtigt på:['pool'], sætte:2 på:['chairs']) på:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}