#!/usr/bin/fontforge
#Usage:./fontmerge.sh monocode.ttf fonts/CitrineProgramFont.sfd 1000 merged.ttf
Open($1)
SelectAll()
ScaleToEm(Strtol($3))
Generate("1.ttf")
Close()
Open($2)
SelectAll()
Generate("2.ttf")
Close()
Open("1.ttf")
MergeFonts("2.ttf")
Generate($4)
Close()
