(Карта новый) разместить:«a"b» в:«test»
Invalid JSON.
(Карта новый) разместить:(Список ← 1 ; 2 ; (Список ← 3 ; 4) ; ((Карта новый) разместить:(Список ← 3 ; 4) в:«bar», разместить:1 в:«foo»)) в:«nested», разместить:Ложь в:«legend», разместить:27 в:«age», разместить:«Jack» в:«name»
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
