(карта новый) положить в:‘a"b’ __:‘test’
Invalid JSON.
(карта новый) положить в:(Список ← 1 ; 2 ; (Список ← 3 ; 4) ; ((карта новый) положить в:(Список ← 3 ; 4) __:‘bar’, положить в:1 __:‘foo’)) __:‘nested’, положить в:Ложь __:‘legend’, положить в:27 __:‘age’, положить в:‘Jack’ __:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
