There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. 假
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is 空虛 meters long.
Luckily, this day, there are 空虛 wasps in the garden.
The dog named 空虛 sleeps under the tree.
a\"bb\"ccc\"
(列表 新的) 将:((列表 新的) 将:空虛 设置为:“dog”, 将:空虛 设置为:“insects”, 将:((列表 新的) 将:15 设置为:“length”, 将:8 设置为:“width”) 设置为:“size”, 将:(系列 ← “tulips” ; “roses” ; “lillies”) 设置为:“flower”, 将:假 设置为:“shed”, 将:真正 设置为:“pool”, 将:2 设置为:“chairs”) 设置为:“garden”
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}