(பட்டியல் புதியது) நகர்த்து:‘a"b’ முதல்:‘test’
Invalid JSON.
(பட்டியல் புதியது) நகர்த்து:(வரிசை ← 1 ; 2 ; (வரிசை ← 3 ; 4) ; ((பட்டியல் புதியது) நகர்த்து:(வரிசை ← 3 ; 4) முதல்:‘bar’, நகர்த்து:1 முதல்:‘foo’)) முதல்:‘nested’, நகர்த்து:பொய் முதல்:‘legend’, நகர்த்து:27 முதல்:‘age’, நகர்த்து:‘Jack’ முதல்:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld