There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. பொய்
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is வெறுமை meters long.
Luckily, this day, there are வெறுமை wasps in the garden.
The dog named வெறுமை sleeps under the tree.
a\"bb\"ccc\"
(பட்டியல் புதியது) நகர்த்து:((பட்டியல் புதியது) நகர்த்து:வெறுமை முதல்:['dog'], நகர்த்து:வெறுமை முதல்:['insects'], நகர்த்து:((பட்டியல் புதியது) நகர்த்து:15 முதல்:['length'], நகர்த்து:8 முதல்:['width']) முதல்:['size'], நகர்த்து:(வரிசை ← ['tulips'] ; ['roses'] ; ['lillies']) முதல்:['flower'], நகர்த்து:பொய் முதல்:['shed'], நகர்த்து:உண்மை முதல்:['pool'], நகர்த்து:2 முதல்:['chairs']) முதல்:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}