Zero
Zero
Boolean
I vërtetë
Boolean
I rremë
Numër
1
Numër
-3
Numër
9,2
Numër
-9,2
Listë
Listë i ri 
Listë
Listë ← 1 ; 2
Listë
Listë ← 1 ; (Listë ← 2)
Listë
Listë ← 1 ; (Listë ← 2) ; 3
Listë
Listë ← 1 ; ((Hartë i ri) vënë:‘a’ në:‘b’) ; 3
Listë
Listë ← 1 ; ((Hartë i ri) vënë:(Listë ← 9) në:‘b’) ; 3
Hartë
(Hartë i ri) vënë:2 në:‘1’
Hartë
(Hartë i ri) vënë:2 në:‘x’
Hartë
(Hartë i ri) vënë:(Listë ← 1 ; 2) në:‘x’
Hartë
(Hartë i ri) vënë:(Listë ← ((Hartë i ri) vënë:‘q’ në:‘y’) ; 2) në:‘x’
Zero
Zero
