There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Faltsua
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Ez meters long.
Luckily, this day, there are Ez wasps in the garden.
The dog named Ez sleeps under the tree.
a\"bb\"ccc\"
(Mapa berriaren) jarri:((Mapa berriaren) jarri:Ez en:‘dog’, jarri:Ez en:‘insects’, jarri:((Mapa berriaren) jarri:15 en:‘length’, jarri:8 en:‘width’) en:‘size’, jarri:(Zerrenda ← ‘tulips’ ; ‘roses’ ; ‘lillies’) en:‘flower’, jarri:Faltsua en:‘shed’, jarri:Egia en:‘pool’, jarri:2 en:‘chairs’) en:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}