Ez
Ez
Erabakia
Egia
Erabakia
Faltsua
Zenbakia
1
Zenbakia
-3
Zenbakia
9,2
Zenbakia
-9,2
Zerrenda
Zerrenda berriaren 
Zerrenda
Zerrenda ← 1 ; 2
Zerrenda
Zerrenda ← 1 ; (Zerrenda ← 2)
Zerrenda
Zerrenda ← 1 ; (Zerrenda ← 2) ; 3
Zerrenda
Zerrenda ← 1 ; ((Mapa berriaren) jarri:‘a’ en:‘b’) ; 3
Zerrenda
Zerrenda ← 1 ; ((Mapa berriaren) jarri:(Zerrenda ← 9) en:‘b’) ; 3
Mapa
(Mapa berriaren) jarri:2 en:‘1’
Mapa
(Mapa berriaren) jarri:2 en:‘x’
Mapa
(Mapa berriaren) jarri:(Zerrenda ← 1 ; 2) en:‘x’
Mapa
(Mapa berriaren) jarri:(Zerrenda ← ((Mapa berriaren) jarri:‘q’ en:‘y’) ; 2) en:‘x’
Ez
Ez