There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Лажни
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Нула meters long.
Luckily, this day, there are Нула wasps in the garden.
The dog named Нула sleeps under the tree.
a\"bb\"ccc\"
(Карта ново) стави:((Карта ново) стави:Нула на:['dog'], стави:Нула на:['insects'], стави:((Карта ново) стави:15 на:['length'], стави:8 на:['width']) на:['size'], стави:(Листа ← ['tulips'] ; ['roses'] ; ['lillies']) на:['flower'], стави:Лажни на:['shed'], стави:Вистина на:['pool'], стави:2 на:['chairs']) на:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}