Nula
Nula
Boolean
Pravdivý
Boolean
Nepravdivý
Číslo
1
Číslo
-3
Číslo
9,2
Číslo
-9,2
Zoznam
Zoznam nový 
Zoznam
Zoznam ← 1 ; 2
Zoznam
Zoznam ← 1 ; (Zoznam ← 2)
Zoznam
Zoznam ← 1 ; (Zoznam ← 2) ; 3
Zoznam
Zoznam ← 1 ; ((Mapa nový) povedané:['a'] na-adrese:['b']) ; 3
Zoznam
Zoznam ← 1 ; ((Mapa nový) povedané:(Zoznam ← 9) na-adrese:['b']) ; 3
Mapa
(Mapa nový) povedané:2 na-adrese:['1']
Mapa
(Mapa nový) povedané:2 na-adrese:['x']
Mapa
(Mapa nový) povedané:(Zoznam ← 1 ; 2) na-adrese:['x']
Mapa
(Mapa nový) povedané:(Zoznam ← ((Mapa nový) povedané:['q'] na-adrese:['y']) ; 2) na-adrese:['x']
Nula
Nula