There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Ubuxoki
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Engenanto meters long.
Luckily, this day, there are Engenanto wasps in the garden.
The dog named Engenanto sleeps under the tree.
a\"bb\"ccc\"
(Uluhlu intsha) beka:((Uluhlu intsha) beka:Engenanto e:['dog'], beka:Engenanto e:['insects'], beka:((Uluhlu intsha) beka:15 e:['length'], beka:8 e:['width']) e:['size'], beka:(Uthotho ← ['tulips'] ; ['roses'] ; ['lillies']) e:['flower'], beka:Ubuxoki e:['shed'], beka:Kuyinyani e:['pool'], beka:2 e:['chairs']) e:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}