(Uluhlu intsha) beka:‘a"b’ e:‘test’
Invalid JSON.
(Uluhlu intsha) beka:(Uthotho ← 1 ; 2 ; (Uthotho ← 3 ; 4) ; ((Uluhlu intsha) beka:(Uthotho ← 3 ; 4) e:‘bar’, beka:1 e:‘foo’)) e:‘nested’, beka:Ubuxoki e:‘legend’, beka:27 e:‘age’, beka:‘Jack’ e:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld