Nulo
Nulo
Booleano
Verdadero
Booleano
Falso
Número
1
Número
-3
Número
9,2
Número
-9,2
Serie
Serie nuevo
Serie
Serie ← 1 ; 2
Serie
Serie ← 1 ; (Serie ← 2)
Serie
Serie ← 1 ; (Serie ← 2) ; 3
Serie
Serie ← 1 ; ((Lista nuevo) poner:['a'] en:['b']) ; 3
Serie
Serie ← 1 ; ((Lista nuevo) poner:(Serie ← 9) en:['b']) ; 3
Lista
(Lista nuevo) poner:2 en:['1']
Lista
(Lista nuevo) poner:2 en:['x']
Lista
(Lista nuevo) poner:(Serie ← 1 ; 2) en:['x']
Lista
(Lista nuevo) poner:(Serie ← ((Lista nuevo) poner:['q'] en:['y']) ; 2) en:['x']
Nulo
Nulo