Nulo
Nulo
Booleano
Cierto
Booleano
Falso
Número
1
Número
-3
Número
9,2
Número
-9,2
Serie
Serie nuevo 
Serie
Serie ← 1 ; 2
Serie
Serie ← 1 ; (Serie ← 2)
Serie
Serie ← 1 ; (Serie ← 2) ; 3
Serie
Serie ← 1 ; ((Lista nuevo) ponlo:‘a’ en:‘b’) ; 3
Serie
Serie ← 1 ; ((Lista nuevo) ponlo:(Serie ← 9) en:‘b’) ; 3
Lista
(Lista nuevo) ponlo:2 en:‘1’
Lista
(Lista nuevo) ponlo:2 en:‘x’
Lista
(Lista nuevo) ponlo:(Serie ← 1 ; 2) en:‘x’
Lista
(Lista nuevo) ponlo:(Serie ← ((Lista nuevo) ponlo:‘q’ en:‘y’) ; 2) en:‘x’
Nulo
Nulo