(Lista nuevo) ponlo:‘a"b’ en:‘test’
Invalid JSON.
(Lista nuevo) ponlo:(Serie ← 1 ; 2 ; (Serie ← 3 ; 4) ; ((Lista nuevo) ponlo:(Serie ← 3 ; 4) en:‘bar’, ponlo:1 en:‘foo’)) en:‘nested’, ponlo:Falso en:‘legend’, ponlo:27 en:‘age’, ponlo:‘Jack’ en:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld