(Lista nuevo) poner:['a"b'] en:['test']
Invalid JSON.
(Lista nuevo) poner:(Serie ← 1 ; 2 ; (Serie ← 3 ; 4) ; ((Lista nuevo) poner:(Serie ← 3 ; 4) en:['bar'], poner:1 en:['foo'])) en:['nested'], poner:Falso en:['legend'], poner:27 en:['age'], poner:['Jack'] en:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld