(ផែនទី ថ្មី) ដាក់:‘a"b’ នៅ:‘test’
Invalid JSON.
(ផែនទី ថ្មី) ដាក់:(បញ្ជី ← 1 ; 2 ; (បញ្ជី ← 3 ; 4) ; ((ផែនទី ថ្មី) ដាក់:(បញ្ជី ← 3 ; 4) នៅ:‘bar’, ដាក់:1 នៅ:‘foo’)) នៅ:‘nested’, ដាក់:មិនពិត នៅ:‘legend’, ដាក់:27 នៅ:‘age’, ដាក់:‘Jack’ នៅ:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld