(ផែនទី ថ្មី) ដាក់៖ នៅ៖__:‘a"b’ __:‘test’
Invalid JSON.
(ផែនទី ថ្មី) ដាក់៖ នៅ៖__:(បញ្ជី ← 1 ; 2 ; (បញ្ជី ← 3 ; 4) ; ((ផែនទី ថ្មី) ដាក់៖ នៅ៖__:(បញ្ជី ← 3 ; 4) __:‘bar’, ដាក់៖ នៅ៖__:1 __:‘foo’)) __:‘nested’, ដាក់៖ នៅ៖__:មិនពិត __:‘legend’, ដាក់៖ នៅ៖__:27 __:‘age’, ដាក់៖ នៅ៖__:‘Jack’ __:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
