There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. មិនពិត
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is និល meters long.
Luckily, this day, there are និល wasps in the garden.
The dog named និល sleeps under the tree.
a\"bb\"ccc\"
(ផែនទី ថ្មី) ដាក់:((ផែនទី ថ្មី) ដាក់:និល នៅ:‘dog’, ដាក់:និល នៅ:‘insects’, ដាក់:((ផែនទី ថ្មី) ដាក់:15 នៅ:‘length’, ដាក់:8 នៅ:‘width’) នៅ:‘size’, ដាក់:(បញ្ជី ← ‘tulips’ ; ‘roses’ ; ‘lillies’) នៅ:‘flower’, ដាក់:មិនពិត នៅ:‘shed’, ដាក់:ពិត នៅ:‘pool’, ដាក់:2 នៅ:‘chairs’) នៅ:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}