Nul
Nul
Boolean
Adevărat
Boolean
Fals
Număr
1
Număr
-3
Număr
9,2
Număr
-9,2
Listă
Listă crea 
Listă
Listă ← 1 ; 2
Listă
Listă ← 1 ; (Listă ← 2)
Listă
Listă ← 1 ; (Listă ← 2) ; 3
Listă
Listă ← 1 ; ((Hartă crea) pune:['a'] la:['b']) ; 3
Listă
Listă ← 1 ; ((Hartă crea) pune:(Listă ← 9) la:['b']) ; 3
Hartă
(Hartă crea) pune:2 la:['1']
Hartă
(Hartă crea) pune:2 la:['x']
Hartă
(Hartă crea) pune:(Listă ← 1 ; 2) la:['x']
Hartă
(Hartă crea) pune:(Listă ← ((Hartă crea) pune:['q'] la:['y']) ; 2) la:['x']
Nul
Nul