(Lista novu) mette:‘a"b’ à:‘test’
Invalid JSON.
(Lista novu) mette:(Serie ← 1 ; 2 ; (Serie ← 3 ; 4) ; ((Lista novu) mette:(Serie ← 3 ; 4) à:‘bar’, mette:1 à:‘foo’)) à:‘nested’, mette:False à:‘legend’, mette:27 à:‘age’, mette:‘Jack’ à:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld