There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. False
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Lista novu) mette:((Lista novu) mette:Nil à:['dog'], mette:Nil à:['insects'], mette:((Lista novu) mette:15 à:['length'], mette:8 à:['width']) à:['size'], mette:(Serie ← ['tulips'] ; ['roses'] ; ['lillies']) à:['flower'], mette:False à:['shed'], mette:Hè-vera à:['pool'], mette:2 à:['chairs']) à:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}