Nil
Nil
Booleanu
Hè vera
Booleanu
False
Numero
1
Numero
-3
Numero
9,2
Numero
-9,2
Serie
Serie novu 
Serie
Serie ← 1 ; 2
Serie
Serie ← 1 ; (Serie ← 2)
Serie
Serie ← 1 ; (Serie ← 2) ; 3
Serie
Serie ← 1 ; ((Lista novu) mette:‘a’ à:‘b’) ; 3
Serie
Serie ← 1 ; ((Lista novu) mette:(Serie ← 9) à:‘b’) ; 3
Lista
(Lista novu) mette:2 à:‘1’
Lista
(Lista novu) mette:2 à:‘x’
Lista
(Lista novu) mette:(Serie ← 1 ; 2) à:‘x’
Lista
(Lista novu) mette:(Serie ← ((Lista novu) mette:‘q’ à:‘y’) ; 2) à:‘x’
Nil
Nil