(نقشه جدید) قرار دهید:‘a"b’ در:‘test’
Invalid JSON.
(نقشه جدید) قرار دهید:(لیست ← 1 ; 2 ; (لیست ← 3 ; 4) ; ((نقشه جدید) قرار دهید:(لیست ← 3 ; 4) در:‘bar’, قرار دهید:1 در:‘foo’)) در:‘nested’, قرار دهید:غلط در:‘legend’, قرار دهید:27 در:‘age’, قرار دهید:‘Jack’ در:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
