There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. غلط
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is نیل meters long.
Luckily, this day, there are نیل wasps in the garden.
The dog named نیل sleeps under the tree.
a\"bb\"ccc\"
(نقشه جدید) قرار دهید:((نقشه جدید) قرار دهید:نیل در:‘dog’, قرار دهید:نیل در:‘insects’, قرار دهید:((نقشه جدید) قرار دهید:15 در:‘length’, قرار دهید:8 در:‘width’) در:‘size’, قرار دهید:(لیست ← ‘tulips’ ; ‘roses’ ; ‘lillies’) در:‘flower’, قرار دهید:غلط در:‘shed’, قرار دهید:درست است، واقعی در:‘pool’, قرار دهید:2 در:‘chairs’) در:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
