There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Nee
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Niets meters long.
Luckily, this day, there are Niets wasps in the garden.
The dog named Niets sleeps under the tree.
a\"bb\"ccc\"
(Lijst nieuw) zet:((Lijst nieuw) zet:Niets bij:['dog'], zet:Niets bij:['insects'], zet:((Lijst nieuw) zet:15 bij:['length'], zet:8 bij:['width']) bij:['size'], zet:(Reeks ← ['tulips'] ; ['roses'] ; ['lillies']) bij:['flower'], zet:Nee bij:['shed'], zet:Ja bij:['pool'], zet:2 bij:['chairs']) bij:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}