Nil
Nil
Boolean
Rost
Boolean
Yolg’on
Raqam
1
Raqam
-3
Raqam
9,2
Raqam
-9,2
Ro‘yxat
Ro‘yxat yangi 
Ro‘yxat
Ro‘yxat ← 1 ; 2
Ro‘yxat
Ro‘yxat ← 1 ; (Ro‘yxat ← 2)
Ro‘yxat
Ro‘yxat ← 1 ; (Ro‘yxat ← 2) ; 3
Ro‘yxat
Ro‘yxat ← 1 ; ((Xarita yangi) qo’yish:«a» da__:«b») ; 3
Ro‘yxat
Ro‘yxat ← 1 ; ((Xarita yangi) qo’yish:(Ro‘yxat ← 9) da__:«b») ; 3
Xarita
(Xarita yangi) qo’yish:2 da__:«1»
Xarita
(Xarita yangi) qo’yish:2 da__:«x»
Xarita
(Xarita yangi) qo’yish:(Ro‘yxat ← 1 ; 2) da__:«x»
Xarita
(Xarita yangi) qo’yish:(Ro‘yxat ← ((Xarita yangi) qo’yish:«q» da__:«y») ; 2) da__:«x»
Nil
Nil
