(R'yxat yangi) q'yish:«a"b» da:«test»
Invalid JSON.
(R'yxat yangi) q'yish:(Qator ← 1 ; 2 ; (Qator ← 3 ; 4) ; ((R'yxat yangi) q'yish:(Qator ← 3 ; 4) da:«bar», q'yish:1 da:«foo»)) da:«nested», q'yish:Yol'on da:«legend», q'yish:27 da:«age», q'yish:«Jack» da:«name»
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld