Bo'sh
Bo'sh
Boolean
Rost
Boolean
Yolg'on
Raqam
1
Raqam
-3
Raqam
9,2
Raqam
-9,2
Qator
Qator yangi 
Qator
Qator ← 1 ; 2
Qator
Qator ← 1 ; (Qator ← 2)
Qator
Qator ← 1 ; (Qator ← 2) ; 3
Qator
Qator ← 1 ; ((Ro'yxat yangi) qo'yish:«a» da:«b») ; 3
Qator
Qator ← 1 ; ((Ro'yxat yangi) qo'yish:(Qator ← 9) da:«b») ; 3
Ro'yxat
(Ro'yxat yangi) qo'yish:2 da:«1»
Ro'yxat
(Ro'yxat yangi) qo'yish:2 da:«x»
Ro'yxat
(Ro'yxat yangi) qo'yish:(Qator ← 1 ; 2) da:«x»
Ro'yxat
(Ro'yxat yangi) qo'yish:(Qator ← ((Ro'yxat yangi) qo'yish:«q» da:«y») ; 2) da:«x»
Bo'sh
Bo'sh