B'sh
B'sh
Boolean
Rost
Boolean
Yol'on
Raqam
1
Raqam
-3
Raqam
9,2
Raqam
-9,2
Qator
Qator yangi 
Qator
Qator ← 1 ; 2
Qator
Qator ← 1 ; (Qator ← 2)
Qator
Qator ← 1 ; (Qator ← 2) ; 3
Qator
Qator ← 1 ; ((R'yxat yangi) q'yish:«a» da:«b») ; 3
Qator
Qator ← 1 ; ((R'yxat yangi) q'yish:(Qator ← 9) da:«b») ; 3
R'yxat
(R'yxat yangi) q'yish:2 da:«1»
R'yxat
(R'yxat yangi) q'yish:2 da:«x»
R'yxat
(R'yxat yangi) q'yish:(Qator ← 1 ; 2) da:«x»
R'yxat
(R'yxat yangi) q'yish:(Qator ← ((R'yxat yangi) q'yish:«q» da:«y») ; 2) da:«x»
B'sh
B'sh