There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Yolg’on
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Xarita yangi) qo’yish:((Xarita yangi) qo’yish:Nil da__:«dog», qo’yish:Nil da__:«insects», qo’yish:((Xarita yangi) qo’yish:15 da__:«length», qo’yish:8 da__:«width») da__:«size», qo’yish:(Ro‘yxat ← «tulips» ; «roses» ; «lillies») da__:«flower», qo’yish:Yolg’on da__:«shed», qo’yish:Rost da__:«pool», qo’yish:2 da__:«chairs») da__:«garden»
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
