Nolla
Nolla
Boolean
Totta
Boolean
Väärä
Määrä
1
Määrä
-3
Määrä
9,2
Määrä
-9,2
Lista
Lista uusi 
Lista
Lista ← 1 ; 2
Lista
Lista ← 1 ; (Lista ← 2)
Lista
Lista ← 1 ; (Lista ← 2) ; 3
Lista
Lista ← 1 ; ((Kartta uusi) laita:['a'] osoitteessa:['b']) ; 3
Lista
Lista ← 1 ; ((Kartta uusi) laita:(Lista ← 9) osoitteessa:['b']) ; 3
Kartta
(Kartta uusi) laita:2 osoitteessa:['1']
Kartta
(Kartta uusi) laita:2 osoitteessa:['x']
Kartta
(Kartta uusi) laita:(Lista ← 1 ; 2) osoitteessa:['x']
Kartta
(Kartta uusi) laita:(Lista ← ((Kartta uusi) laita:['q'] osoitteessa:['y']) ; 2) osoitteessa:['x']
Nolla
Nolla