Eidel
Eidel
Boolschen
Richteg
Boolschen
Falsch
Zuel
1
Zuel
-3
Zuel
9,2
Zuel
-9,2
Serie
Serie nei 
Serie
Serie ← 1 ; 2
Serie
Serie ← 1 ; (Serie ← 2)
Serie
Serie ← 1 ; (Serie ← 2) ; 3
Serie
Serie ← 1 ; ((Lëscht nei) setzen:‘a’ bei:‘b’) ; 3
Serie
Serie ← 1 ; ((Lëscht nei) setzen:(Serie ← 9) bei:‘b’) ; 3
Lëscht
(Lëscht nei) setzen:2 bei:‘1’
Lëscht
(Lëscht nei) setzen:2 bei:‘x’
Lëscht
(Lëscht nei) setzen:(Serie ← 1 ; 2) bei:‘x’
Lëscht
(Lëscht nei) setzen:(Serie ← ((Lëscht nei) setzen:‘q’ bei:‘y’) ; 2) bei:‘x’
Eidel
Eidel