(Taswira sabo) sanya:“a"b” a:“test”
Invalid JSON.
(Taswira sabo) sanya:(Jerin ← 1 ; 2 ; (Jerin ← 3 ; 4) ; ((Taswira sabo) sanya:(Jerin ← 3 ; 4) a:“bar”, sanya:1 a:“foo”)) a:“nested”, sanya:Karya a:“legend”, sanya:27 a:“age”, sanya:“Jack” a:“name”
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld