Nil
Nil
Boolean
Gaskiya ne
Boolean
Karya
Lambar
1
Lambar
-3
Lambar
9,2
Lambar
-9,2
Jerin
Jerin sabo 
Jerin
Jerin ← 1 ; 2
Jerin
Jerin ← 1 ; (Jerin ← 2)
Jerin
Jerin ← 1 ; (Jerin ← 2) ; 3
Jerin
Jerin ← 1 ; ((Taswira sabo) sanya:“a” a:“b”) ; 3
Jerin
Jerin ← 1 ; ((Taswira sabo) sanya:(Jerin ← 9) a:“b”) ; 3
Taswira
(Taswira sabo) sanya:2 a:“1”
Taswira
(Taswira sabo) sanya:2 a:“x”
Taswira
(Taswira sabo) sanya:(Jerin ← 1 ; 2) a:“x”
Taswira
(Taswira sabo) sanya:(Jerin ← ((Taswira sabo) sanya:“q” a:“y”) ; 2) a:“x”
Nil
Nil