There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. ମିଥ୍ୟା
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is ନିଲ୍ meters long.
Luckily, this day, there are ନିଲ୍ wasps in the garden.
The dog named ନିଲ୍ sleeps under the tree.
a\"bb\"ccc\"
(ମାନଚିତ୍ର ନୂତନ) ବସ୍ତୁ:((ମାନଚିତ୍ର ନୂତନ) ବସ୍ତୁ:ନିଲ୍ ସ୍ଥାନ:‘dog’, ବସ୍ତୁ:ନିଲ୍ ସ୍ଥାନ:‘insects’, ବସ୍ତୁ:((ମାନଚିତ୍ର ନୂତନ) ବସ୍ତୁ:15 ସ୍ଥାନ:‘length’, ବସ୍ତୁ:8 ସ୍ଥାନ:‘width’) ସ୍ଥାନ:‘size’, ବସ୍ତୁ:(ତାଲିକା ← ‘tulips’ ; ‘roses’ ; ‘lillies’) ସ୍ଥାନ:‘flower’, ବସ୍ତୁ:ମିଥ୍ୟା ସ୍ଥାନ:‘shed’, ବସ୍ତୁ:ସତ ସ୍ଥାନ:‘pool’, ବସ୍ତୁ:2 ସ୍ଥାନ:‘chairs’) ସ୍ଥାନ:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}