(Mapa ùr) cuir:‘a"b’ le:‘test’
Invalid JSON.
(Mapa ùr) cuir:(Liosta ← 1 ; 2 ; (Liosta ← 3 ; 4) ; ((Mapa ùr) cuir:(Liosta ← 3 ; 4) le:‘bar’, cuir:1 le:‘foo’)) le:‘nested’, cuir:Meallta le:‘legend’, cuir:27 le:‘age’, cuir:‘Jack’ le:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld