Sıfır
Sıfır
Boole
Doğru
Boole
Yanlış
Numara
1
Numara
-3
Numara
9,2
Numara
-9,2
Dizi
Dizi yeni 
Dizi
Dizi ← 1 ; 2
Dizi
Dizi ← 1 ; (Dizi ← 2)
Dizi
Dizi ← 1 ; (Dizi ← 2) ; 3
Dizi
Dizi ← 1 ; ((Liste yeni) koyun:‘a’ at:‘b’) ; 3
Dizi
Dizi ← 1 ; ((Liste yeni) koyun:(Dizi ← 9) at:‘b’) ; 3
Liste
(Liste yeni) koyun:2 at:‘1’
Liste
(Liste yeni) koyun:2 at:‘x’
Liste
(Liste yeni) koyun:(Dizi ← 1 ; 2) at:‘x’
Liste
(Liste yeni) koyun:(Dizi ← ((Liste yeni) koyun:‘q’ at:‘y’) ; 2) at:‘x’
Sıfır
Sıfır