(සිතියම නව) වස්තුව:‘a"b’ ස්ථානය:‘test’
Invalid JSON.
(සිතියම නව) වස්තුව:(ලැයිස්තුව ← 1 ; 2 ; (ලැයිස්තුව ← 3 ; 4) ; ((සිතියම නව) වස්තුව:(ලැයිස්තුව ← 3 ; 4) ස්ථානය:‘bar’, වස්තුව:1 ස්ථානය:‘foo’)) ස්ථානය:‘nested’, වස්තුව:නැත ස්ථානය:‘legend’, වස්තුව:27 ස්ථානය:‘age’, වස්තුව:‘Jack’ ස්ථානය:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld