There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. නැත
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is නිල් meters long.
Luckily, this day, there are නිල් wasps in the garden.
The dog named නිල් sleeps under the tree.
a\"bb\"ccc\"
(සිතියම නව) වස්තුව:((සිතියම නව) වස්තුව:නිල් ස්ථානය:‘dog’, වස්තුව:නිල් ස්ථානය:‘insects’, වස්තුව:((සිතියම නව) වස්තුව:15 ස්ථානය:‘length’, වස්තුව:8 ස්ථානය:‘width’) ස්ථානය:‘size’, වස්තුව:(ලැයිස්තුව ← ‘tulips’ ; ‘roses’ ; ‘lillies’) ස්ථානය:‘flower’, වස්තුව:නැත ස්ථානය:‘shed’, වස්තුව:ඔව් ස්ථානය:‘pool’, වස්තුව:2 ස්ථානය:‘chairs’) ස්ථානය:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}