There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Oya
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Ntacyo meters long.
Luckily, this day, there are Ntacyo wasps in the garden.
The dog named Ntacyo sleeps under the tree.
a\"bb\"ccc\"
(Ikarita gishya) shyira:((Ikarita gishya) shyira:Ntacyo kuri:‘dog’, shyira:Ntacyo kuri:‘insects’, shyira:((Ikarita gishya) shyira:15 kuri:‘length’, shyira:8 kuri:‘width’) kuri:‘size’, shyira:(Urutonde ← ‘tulips’ ; ‘roses’ ; ‘lillies’) kuri:‘flower’, shyira:Oya kuri:‘shed’, shyira:Yego kuri:‘pool’, shyira:2 kuri:‘chairs’) kuri:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}