There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Ikinyoma
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Ikarita gishya) shyira:((Ikarita gishya) shyira:Nil kuri:‘dog’, shyira:Nil kuri:‘insects’, shyira:((Ikarita gishya) shyira:15 kuri:‘length’, shyira:8 kuri:‘width’) kuri:‘size’, shyira:(Urutonde ← ‘tulips’ ; ‘roses’ ; ‘lillies’) kuri:‘flower’, shyira:Ikinyoma kuri:‘shed’, shyira:Nukuri kuri:‘pool’, shyira:2 kuri:‘chairs’) kuri:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
