Nil
Nil
Boolean
Nukuri
Boolean
Ikinyoma
Umubare
1
Umubare
-3
Umubare
9,2
Umubare
-9,2
Urutonde
Urutonde gishya 
Urutonde
Urutonde ← 1 ; 2
Urutonde
Urutonde ← 1 ; (Urutonde ← 2)
Urutonde
Urutonde ← 1 ; (Urutonde ← 2) ; 3
Urutonde
Urutonde ← 1 ; ((Ikarita gishya) shyira:‘a’ kuri:‘b’) ; 3
Urutonde
Urutonde ← 1 ; ((Ikarita gishya) shyira:(Urutonde ← 9) kuri:‘b’) ; 3
Ikarita
(Ikarita gishya) shyira:2 kuri:‘1’
Ikarita
(Ikarita gishya) shyira:2 kuri:‘x’
Ikarita
(Ikarita gishya) shyira:(Urutonde ← 1 ; 2) kuri:‘x’
Ikarita
(Ikarita gishya) shyira:(Urutonde ← ((Ikarita gishya) shyira:‘q’ kuri:‘y’) ; 2) kuri:‘x’
Nil
Nil
