(Orodha mpya) weka:['a"b'] saa:['test']
Invalid JSON.
(Orodha mpya) weka:(Msururu ← 1 ; 2 ; (Msururu ← 3 ; 4) ; ((Orodha mpya) weka:(Msururu ← 3 ; 4) saa:['bar'], weka:1 saa:['foo'])) saa:['nested'], weka:Hapana saa:['legend'], weka:27 saa:['age'], weka:['Jack'] saa:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld