There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Falz
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Lista ġdid) tpoġġi:((Lista ġdid) tpoġġi:Nil fi:['dog'], tpoġġi:Nil fi:['insects'], tpoġġi:((Lista ġdid) tpoġġi:15 fi:['length'], tpoġġi:8 fi:['width']) fi:['size'], tpoġġi:(Serje ← ['tulips'] ; ['roses'] ; ['lillies']) fi:['flower'], tpoġġi:Falz fi:['shed'], tpoġġi:Veru fi:['pool'], tpoġġi:2 fi:['chairs']) fi:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}