(Lista ġdid) tpoġġi:['a"b'] fi:['test']
Invalid JSON.
(Lista ġdid) tpoġġi:(Serje ← 1 ; 2 ; (Serje ← 3 ; 4) ; ((Lista ġdid) tpoġġi:(Serje ← 3 ; 4) fi:['bar'], tpoġġi:1 fi:['foo'])) fi:['nested'], tpoġġi:Falz fi:['legend'], tpoġġi:27 fi:['age'], tpoġġi:['Jack'] fi:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld