Tiada
Tiada
Boolean
Benar
Boolean
Salah
Nombor
1
Nombor
-3
Nombor
9,2
Nombor
-9,2
Senarai
Senarai baru 
Senarai
Senarai ← 1 ; 2
Senarai
Senarai ← 1 ; (Senarai ← 2)
Senarai
Senarai ← 1 ; (Senarai ← 2) ; 3
Senarai
Senarai ← 1 ; ((Peta baru) meletakkan:‘a’ pada:‘b’) ; 3
Senarai
Senarai ← 1 ; ((Peta baru) meletakkan:(Senarai ← 9) pada:‘b’) ; 3
Peta
(Peta baru) meletakkan:2 pada:‘1’
Peta
(Peta baru) meletakkan:2 pada:‘x’
Peta
(Peta baru) meletakkan:(Senarai ← 1 ; 2) pada:‘x’
Peta
(Peta baru) meletakkan:(Senarai ← ((Peta baru) meletakkan:‘q’ pada:‘y’) ; 2) pada:‘x’
Tiada
Tiada
