There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Salah
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Tiada meters long.
Luckily, this day, there are Tiada wasps in the garden.
The dog named Tiada sleeps under the tree.
a\"bb\"ccc\"
(Peta baru) meletakkan:((Peta baru) meletakkan:Tiada pada:['dog'], meletakkan:Tiada pada:['insects'], meletakkan:((Peta baru) meletakkan:15 pada:['length'], meletakkan:8 pada:['width']) pada:['size'], meletakkan:(Senarai ← ['tulips'] ; ['roses'] ; ['lillies']) pada:['flower'], meletakkan:Salah pada:['shed'], meletakkan:Benar pada:['pool'], meletakkan:2 pada:['chairs']) pada:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}