(सूची नयाँ) राख्नुहोस्:‘a"b’ मा:‘test’
Invalid JSON.
(सूची नयाँ) राख्नुहोस्:(शृङ्खला ← 1 ; 2 ; (शृङ्खला ← 3 ; 4) ; ((सूची नयाँ) राख्नुहोस्:(शृङ्खला ← 3 ; 4) मा:‘bar’, राख्नुहोस्:1 मा:‘foo’)) मा:‘nested’, राख्नुहोस्:छैन मा:‘legend’, राख्नुहोस्:27 मा:‘age’, राख्नुहोस्:‘Jack’ मा:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld