Nil
Nil
Booleano
Certo
Booleano
Falso
Número
1
Número
-3
Número
9,2
Número
-9,2
Lista
Lista novo 
Lista
Lista ← 1 ; 2
Lista
Lista ← 1 ; (Lista ← 2)
Lista
Lista ← 1 ; (Lista ← 2) ; 3
Lista
Lista ← 1 ; ((Mapa novo) poñer:‘a’ en:‘b’) ; 3
Lista
Lista ← 1 ; ((Mapa novo) poñer:(Lista ← 9) en:‘b’) ; 3
Mapa
(Mapa novo) poñer:2 en:‘1’
Mapa
(Mapa novo) poñer:2 en:‘x’
Mapa
(Mapa novo) poñer:(Lista ← 1 ; 2) en:‘x’
Mapa
(Mapa novo) poñer:(Lista ← ((Mapa novo) poñer:‘q’ en:‘y’) ; 2) en:‘x’
Nil
Nil
