Nil
Nil
Boolean
Kuliqiniso
Boolean
Amanga
Inombolo
1
Inombolo
-3
Inombolo
9,2
Inombolo
-9,2
Uhlu
Uhlu okusha 
Uhlu
Uhlu ← 1 ; 2
Uhlu
Uhlu ← 1 ; (Uhlu ← 2)
Uhlu
Uhlu ← 1 ; (Uhlu ← 2) ; 3
Uhlu
Uhlu ← 1 ; ((Imephu okusha) beka:‘a’ at:‘b’) ; 3
Uhlu
Uhlu ← 1 ; ((Imephu okusha) beka:(Uhlu ← 9) at:‘b’) ; 3
Imephu
(Imephu okusha) beka:2 at:‘1’
Imephu
(Imephu okusha) beka:2 at:‘x’
Imephu
(Imephu okusha) beka:(Uhlu ← 1 ; 2) at:‘x’
Imephu
(Imephu okusha) beka:(Uhlu ← ((Imephu okusha) beka:‘q’ at:‘y’) ; 2) at:‘x’
Nil
Nil
