(Imephu okusha) beka:‘a"b’ ngo:‘test’
Invalid JSON.
(Imephu okusha) beka:(Uhlu ← 1 ; 2 ; (Uhlu ← 3 ; 4) ; ((Imephu okusha) beka:(Uhlu ← 3 ; 4) ngo:‘bar’, beka:1 ngo:‘foo’)) ngo:‘nested’, beka:Cha ngo:‘legend’, beka:27 ngo:‘age’, beka:‘Jack’ ngo:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld