Lutho
Lutho
Yebo-noma-cha
Yebo
Yebo-noma-cha
Cha
Inombolo
1
Inombolo
-3
Inombolo
9,2
Inombolo
-9,2
Uhlu
Uhlu okusha 
Uhlu
Uhlu ← 1 ; 2
Uhlu
Uhlu ← 1 ; (Uhlu ← 2)
Uhlu
Uhlu ← 1 ; (Uhlu ← 2) ; 3
Uhlu
Uhlu ← 1 ; ((Imephu okusha) beka:['a'] ngo:['b']) ; 3
Uhlu
Uhlu ← 1 ; ((Imephu okusha) beka:(Uhlu ← 9) ngo:['b']) ; 3
Imephu
(Imephu okusha) beka:2 ngo:['1']
Imephu
(Imephu okusha) beka:2 ngo:['x']
Imephu
(Imephu okusha) beka:(Uhlu ← 1 ; 2) ngo:['x']
Imephu
(Imephu okusha) beka:(Uhlu ← ((Imephu okusha) beka:['q'] ngo:['y']) ; 2) ngo:['x']
Lutho
Lutho