(Lista új) magyarán:['a"b'] itt:['test']
Invalid JSON.
(Lista új) magyarán:(Sorozat ← 1 ; 2 ; (Sorozat ← 3 ; 4) ; ((Lista új) magyarán:(Sorozat ← 3 ; 4) itt:['bar'], magyarán:1 itt:['foo'])) itt:['nested'], magyarán:Hamis itt:['legend'], magyarán:27 itt:['age'], magyarán:['Jack'] itt:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld