Nulla
Nulla
Logikai
Igaz
Logikai
Hamis
Szám
1
Szám
-3
Szám
9,2
Szám
-9,2
Lista
Lista új 
Lista
Lista ← 1 ; 2
Lista
Lista ← 1 ; (Lista ← 2)
Lista
Lista ← 1 ; (Lista ← 2) ; 3
Lista
Lista ← 1 ; ((Térkép új) magyarán:‘a’ itt:‘b’) ; 3
Lista
Lista ← 1 ; ((Térkép új) magyarán:(Lista ← 9) itt:‘b’) ; 3
Térkép
(Térkép új) magyarán:2 itt:‘1’
Térkép
(Térkép új) magyarán:2 itt:‘x’
Térkép
(Térkép új) magyarán:(Lista ← 1 ; 2) itt:‘x’
Térkép
(Térkép új) magyarán:(Lista ← ((Térkép új) magyarán:‘q’ itt:‘y’) ; 2) itt:‘x’
Nulla
Nulla
