(Mapa nowy) położyć na coś:‘a"b’ __:‘test’
Invalid JSON.
(Mapa nowy) położyć na coś:(Lista ← 1 ; 2 ; (Lista ← 3 ; 4) ; ((Mapa nowy) położyć na coś:(Lista ← 3 ; 4) __:‘bar’, położyć na coś:1 __:‘foo’)) __:‘nested’, położyć na coś:Fałszywy __:‘legend’, położyć na coś:27 __:‘age’, położyć na coś:‘Jack’ __:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
