(Lista nowy) że:‘a"b’ jest:‘test’
Invalid JSON.
(Lista nowy) że:(Serio ← 1 ; 2 ; (Serio ← 3 ; 4) ; ((Lista nowy) że:(Serio ← 3 ; 4) jest:‘bar’, że:1 jest:‘foo’)) jest:‘nested’, że:Fałszywy jest:‘legend’, że:27 jest:‘age’, że:‘Jack’ jest:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld