Zero
Zero
Boolean
Prawdziwe
Boolean
Fałszywy
Numer
1
Numer
-3
Numer
9,2
Numer
-9,2
Lista
Lista nowy 
Lista
Lista ← 1 ; 2
Lista
Lista ← 1 ; (Lista ← 2)
Lista
Lista ← 1 ; (Lista ← 2) ; 3
Lista
Lista ← 1 ; ((Mapa nowy) położyć na coś:‘a’ __:‘b’) ; 3
Lista
Lista ← 1 ; ((Mapa nowy) położyć na coś:(Lista ← 9) __:‘b’) ; 3
Mapa
(Mapa nowy) położyć na coś:2 __:‘1’
Mapa
(Mapa nowy) położyć na coś:2 __:‘x’
Mapa
(Mapa nowy) położyć na coś:(Lista ← 1 ; 2) __:‘x’
Mapa
(Mapa nowy) położyć na coś:(Lista ← ((Mapa nowy) położyć na coś:‘q’ __:‘y’) ; 2) __:‘x’
Zero
Zero
