There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Помилковий
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Ніл meters long.
Luckily, this day, there are Ніл wasps in the garden.
The dog named Ніл sleeps under the tree.
a\"bb\"ccc\"
(Карта нові) поставити:((Карта нові) поставити:Ніл у:‘dog’, поставити:Ніл у:‘insects’, поставити:((Карта нові) поставити:15 у:‘length’, поставити:8 у:‘width’) у:‘size’, поставити:(Список ← ‘tulips’ ; ‘roses’ ; ‘lillies’) у:‘flower’, поставити:Помилковий у:‘shed’, поставити:Правда у:‘pool’, поставити:2 у:‘chairs’) у:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}