(Карта нові) поставити:‘a"b’ у:‘test’
Invalid JSON.
(Карта нові) поставити:(Список ← 1 ; 2 ; (Список ← 3 ; 4) ; ((Карта нові) поставити:(Список ← 3 ; 4) у:‘bar’, поставити:1 у:‘foo’)) у:‘nested’, поставити:Помилковий у:‘legend’, поставити:27 у:‘age’, поставити:‘Jack’ у:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld