(Daim-ntawv-qhia tshiab) muab:['a"b'] rau:['test']
Invalid JSON.
(Daim-ntawv-qhia tshiab) muab:(Sau ← 1 ; 2 ; (Sau ← 3 ; 4) ; ((Daim-ntawv-qhia tshiab) muab:(Sau ← 3 ; 4) rau:['bar'], muab:1 rau:['foo'])) rau:['nested'], muab:Tsis-tseeb rau:['legend'], muab:27 rau:['age'], muab:['Jack'] rau:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld