Nil
Nil
Booleà
És cert
Booleà
Fals
Número
1
Número
-3
Número
9,2
Número
-9,2
Llista
Llista nou 
Llista
Llista ← 1 ; 2
Llista
Llista ← 1 ; (Llista ← 2)
Llista
Llista ← 1 ; (Llista ← 2) ; 3
Llista
Llista ← 1 ; ((Mapa nou) posar:‘a’ a:‘b’) ; 3
Llista
Llista ← 1 ; ((Mapa nou) posar:(Llista ← 9) a:‘b’) ; 3
Mapa
(Mapa nou) posar:2 a:‘1’
Mapa
(Mapa nou) posar:2 a:‘x’
Mapa
(Mapa nou) posar:(Llista ← 1 ; 2) a:‘x’
Mapa
(Mapa nou) posar:(Llista ← ((Mapa nou) posar:‘q’ a:‘y’) ; 2) a:‘x’
Nil
Nil