(Mapa nou) posar:['a"b'] a:['test']
Invalid JSON.
(Mapa nou) posar:(Llista ← 1 ; 2 ; (Llista ← 3 ; 4) ; ((Mapa nou) posar:(Llista ← 3 ; 4) a:['bar'], posar:1 a:['foo'])) a:['nested'], posar:Fals a:['legend'], posar:27 a:['age'], posar:['Jack'] a:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld