There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Nee
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Neat meters long.
Luckily, this day, there are Neat wasps in the garden.
The dog named Neat sleeps under the tree.
a\"bb\"ccc\"
(List nĳ) set: ((List nĳ) set: Neat by:['dog'], set: Neat by:['insects'], set: ((List nĳ) set: 15 by:['length'], set: 8 by:['width']) by:['size'], set: (Searje ← ['tulips'] ; ['roses'] ; ['lillies']) by:['flower'], set: Nee by:['shed'], set: Ja by:['pool'], set: 2 by:['chairs']) by:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}