Neat
Neat
Beslissing
Ja
Beslissing
Nee
Nûmer
1
Nûmer
-3
Nûmer
9,2
Nûmer
-9,2
Searje
Searje nĳ 
Searje
Searje ← 1 ; 2
Searje
Searje ← 1 ; (Searje ← 2)
Searje
Searje ← 1 ; (Searje ← 2) ; 3
Searje
Searje ← 1 ; ((List nĳ) set: ['a'] by:['b']) ; 3
Searje
Searje ← 1 ; ((List nĳ) set: (Searje ← 9) by:['b']) ; 3
List
(List nĳ) set: 2 by:['1']
List
(List nĳ) set: 2 by:['x']
List
(List nĳ) set: (Searje ← 1 ; 2) by:['x']
List
(List nĳ) set: (Searje ← ((List nĳ) set: ['q'] by:['y']) ; 2) by:['x']
Neat
Neat