(Map zatsopano) ikani:['a"b'] pa:['test']
Invalid JSON.
(Map zatsopano) ikani:(Mndandanda ← 1 ; 2 ; (Mndandanda ← 3 ; 4) ; ((Map zatsopano) ikani:(Mndandanda ← 3 ; 4) pa:['bar'], ikani:1 pa:['foo'])) pa:['nested'], ikani:Zabodza pa:['legend'], ikani:27 pa:['age'], ikani:['Jack'] pa:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld