There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Zabodza
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Map zatsopano) ikani:((Map zatsopano) ikani:Nil pa:['dog'], ikani:Nil pa:['insects'], ikani:((Map zatsopano) ikani:15 pa:['length'], ikani:8 pa:['width']) pa:['size'], ikani:(Mndandanda ← ['tulips'] ; ['roses'] ; ['lillies']) pa:['flower'], ikani:Zabodza pa:['shed'], ikani:Zowona pa:['pool'], ikani:2 pa:['chairs']) pa:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}