Nil
Nil
Boolean
Tinuod
Boolean
Bakak
Numero
1
Numero
-3
Numero
9,2
Numero
-9,2
Paglista
Paglista bag-o-nga 
Paglista
Paglista ← 1 ; 2
Paglista
Paglista ← 1 ; (Paglista ← 2)
Paglista
Paglista ← 1 ; (Paglista ← 2) ; 3
Paglista
Paglista ← 1 ; ((Mapa bag-o-nga) gibutang:['a'] sa:['b']) ; 3
Paglista
Paglista ← 1 ; ((Mapa bag-o-nga) gibutang:(Paglista ← 9) sa:['b']) ; 3
Mapa
(Mapa bag-o-nga) gibutang:2 sa:['1']
Mapa
(Mapa bag-o-nga) gibutang:2 sa:['x']
Mapa
(Mapa bag-o-nga) gibutang:(Paglista ← 1 ; 2) sa:['x']
Mapa
(Mapa bag-o-nga) gibutang:(Paglista ← ((Mapa bag-o-nga) gibutang:['q'] sa:['y']) ; 2) sa:['x']
Nil
Nil