There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. No
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nada meters long.
Luckily, this day, there are Nada wasps in the garden.
The dog named Nada sleeps under the tree.
a\"bb\"ccc\"
(Lista notisia) perde:((Lista notisia) perde:Nada na:‘dog’, perde:Nada na:‘insects’, perde:((Lista notisia) perde:15 na:‘length’, perde:8 na:‘width’) na:‘size’, perde:(Sèt ← ‘tulips’ ; ‘roses’ ; ‘lillies’) na:‘flower’, perde:No na:‘shed’, perde:Bal na:‘pool’, perde:2 na:‘chairs’) na:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}
