Nada
Nada
Sí òf nò
Bal
Sí òf nò
No
Number
1
Number
-3
Number
9.2
Number
-9.2
Sèt
Sèt notisia 
Sèt
Sèt ← 1 ; 2
Sèt
Sèt ← 1 ; (Sèt ← 2)
Sèt
Sèt ← 1 ; (Sèt ← 2) ; 3
Sèt
Sèt ← 1 ; ((Lista notisia) perde:‘a’ na:‘b’) ; 3
Sèt
Sèt ← 1 ; ((Lista notisia) perde:(Sèt ← 9) na:‘b’) ; 3
Lista
(Lista notisia) perde:2 na:‘1’
Lista
(Lista notisia) perde:2 na:‘x’
Lista
(Lista notisia) perde:(Sèt ← 1 ; 2) na:‘x’
Lista
(Lista notisia) perde:(Sèt ← ((Lista notisia) perde:‘q’ na:‘y’) ; 2) na:‘x’
Nada
Nada
