There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Bẹẹkọ
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Ofo meters long.
Luckily, this day, there are Ofo wasps in the garden.
The dog named Ofo sleeps under the tree.
a\"bb\"ccc\"
(Akojọ tuntun) fi:((Akojọ tuntun) fi:Ofo nipa:['dog'], fi:Ofo nipa:['insects'], fi:((Akojọ tuntun) fi:15 nipa:['length'], fi:8 nipa:['width']) nipa:['size'], fi:(Jara ← ['tulips'] ; ['roses'] ; ['lillies']) nipa:['flower'], fi:Bẹẹkọ nipa:['shed'], fi:Bẹẹni nipa:['pool'], fi:2 nipa:['chairs']) nipa:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}