(Akojọ tuntun) fi:‘a"b’ nipa:‘test’
Invalid JSON.
(Akojọ tuntun) fi:(Jara ← 1 ; 2 ; (Jara ← 3 ; 4) ; ((Akojọ tuntun) fi:(Jara ← 3 ; 4) nipa:‘bar’, fi:1 nipa:‘foo’)) nipa:‘nested’, fi:Bẹẹkọ nipa:‘legend’, fi:27 nipa:‘age’, fi:‘Jack’ nipa:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld