(Maapu tuntun) fi:‘a"b’ ni:‘test’
Invalid JSON.
(Maapu tuntun) fi:(Atokọ ← 1 ; 2 ; (Atokọ ← 3 ; 4) ; ((Maapu tuntun) fi:(Atokọ ← 3 ; 4) ni:‘bar’, fi:1 ni:‘foo’)) ni:‘nested’, fi:Irọ ni:‘legend’, fi:27 ni:‘age’, fi:‘Jack’ ni:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
