There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Лажно
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Нула meters long.
Luckily, this day, there are Нула wasps in the garden.
The dog named Нула sleeps under the tree.
a\"bb\"ccc\"
(Мапа Нова) пут:((Мапа Нова) пут:Нула ат:['dog'], пут:Нула ат:['insects'], пут:((Мапа Нова) пут:15 ат:['length'], пут:8 ат:['width']) ат:['size'], пут:(Листа ← ['tulips'] ; ['roses'] ; ['lillies']) ат:['flower'], пут:Лажно ат:['shed'], пут:Истина ат:['pool'], пут:2 ат:['chairs']) ат:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}