There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Dëkkul
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Dara meters long.
Luckily, this day, there are Dara wasps in the garden.
The dog named Dara sleeps under the tree.
a\"bb\"ccc\"
(Listin xees) teg:((Listin xees) teg:Dara ci:['dog'], teg:Dara ci:['insects'], teg:((Listin xees) teg:15 ci:['length'], teg:8 ci:['width']) ci:['size'], teg:(Jokkalante ← ['tulips'] ; ['roses'] ; ['lillies']) ci:['flower'], teg:Dëkkul ci:['shed'], teg:Dëgg ci:['pool'], teg:2 ci:['chairs']) ci:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}