(Listin xees) teg:['a"b'] ci:['test']
Invalid JSON.
(Listin xees) teg:(Jokkalante ← 1 ; 2 ; (Jokkalante ← 3 ; 4) ; ((Listin xees) teg:(Jokkalante ← 3 ; 4) ci:['bar'], teg:1 ci:['foo'])) ci:['nested'], teg:Dëkkul ci:['legend'], teg:27 ci:['age'], teg:['Jack'] ci:['name']
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld