(Khariidad cusub) dhigaa:‘a"b’ at:‘test’
Invalid JSON.
(Khariidad cusub) dhigaa:(Liiska ← 1 ; 2 ; (Liiska ← 3 ; 4) ; ((Khariidad cusub) dhigaa:(Liiska ← 3 ; 4) at:‘bar’, dhigaa:1 at:‘foo’)) at:‘nested’, dhigaa:Been at:‘legend’, dhigaa:27 at:‘age’, dhigaa:‘Jack’ at:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld
