Waxba
Waxba
Haa maya
Haa
Haa maya
Maya
Tirada
1
Tirada
-3
Tirada
9,2
Tirada
-9,2
Taxane
Taxane cusub 
Taxane
Taxane ← 1 ; 2
Taxane
Taxane ← 1 ; (Taxane ← 2)
Taxane
Taxane ← 1 ; (Taxane ← 2) ; 3
Taxane
Taxane ← 1 ; ((Liiska cusub) walax:‘a’ meeshaas:‘b’) ; 3
Taxane
Taxane ← 1 ; ((Liiska cusub) walax:(Taxane ← 9) meeshaas:‘b’) ; 3
Liiska
(Liiska cusub) walax:2 meeshaas:‘1’
Liiska
(Liiska cusub) walax:2 meeshaas:‘x’
Liiska
(Liiska cusub) walax:(Taxane ← 1 ; 2) meeshaas:‘x’
Liiska
(Liiska cusub) walax:(Taxane ← ((Liiska cusub) walax:‘q’ meeshaas:‘y’) ; 2) meeshaas:‘x’
Waxba
Waxba