Eber
Eber
Boolean
Run
Boolean
Been
Tirada
1
Tirada
-3
Tirada
9,2
Tirada
-9,2
Serije
Serije cusub 
Serije
Serije ← 1 ; 2
Serije
Serije ← 1 ; (Serije ← 2)
Serije
Serije ← 1 ; (Serije ← 2) ; 3
Serije
Serije ← 1 ; ((Seznam cusub) dhigaa:‘a’ at:‘b’) ; 3
Serije
Serije ← 1 ; ((Seznam cusub) dhigaa:(Serije ← 9) at:‘b’) ; 3
Seznam
(Seznam cusub) dhigaa:2 at:‘1’
Seznam
(Seznam cusub) dhigaa:2 at:‘x’
Seznam
(Seznam cusub) dhigaa:(Serije ← 1 ; 2) at:‘x’
Seznam
(Seznam cusub) dhigaa:(Serije ← ((Seznam cusub) dhigaa:‘q’ at:‘y’) ; 2) at:‘x’
Eber
Eber