There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Sealňyş
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Nil meters long.
Luckily, this day, there are Nil wasps in the garden.
The dog named Nil sleeps under the tree.
a\"bb\"ccc\"
(Sanaw täze) obýekt:((Sanaw täze) obýekt:Nil ýeri:‘dog’, obýekt:Nil ýeri:‘insects’, obýekt:((Sanaw täze) obýekt:15 ýeri:‘length’, obýekt:8 ýeri:‘width’) ýeri:‘size’, obýekt:(Seriýa ← ‘tulips’ ; ‘roses’ ; ‘lillies’) ýeri:‘flower’, obýekt:Sealňyş ýeri:‘shed’, obýekt:Dogry ýeri:‘pool’, obýekt:2 ýeri:‘chairs’) ýeri:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}