(Sanaw täze) obýekt:‘a"b’ ýeri:‘test’
Invalid JSON.
(Sanaw täze) obýekt:(Seriýa ← 1 ; 2 ; (Seriýa ← 3 ; 4) ; ((Sanaw täze) obýekt:(Seriýa ← 3 ; 4) ýeri:‘bar’, obýekt:1 ýeri:‘foo’)) ýeri:‘nested’, obýekt:Sealňyş ýeri:‘legend’, obýekt:27 ýeri:‘age’, obýekt:‘Jack’ ýeri:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld