(หนังสือี่ ใหม่) วาง:‘a"b’ ที่:‘test’
Invalid JSON.
(หนังสือี่ ใหม่) วาง:(ชุด ← 1 ; 2 ; (ชุด ← 3 ; 4) ; ((หนังสือี่ ใหม่) วาง:(ชุด ← 3 ; 4) ที่:‘bar’, วาง:1 ที่:‘foo’)) ที่:‘nested’, วาง:ไม่ ที่:‘legend’, วาง:27 ที่:‘age’, วาง:‘Jack’ ที่:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld