(ዝርዝር አዲስ) ነገር:‘a"b’ ቦታ:‘test’
Invalid JSON.
(ዝርዝር አዲስ) ነገር:(ተከታታይ ← 1 ; 2 ; (ተከታታይ ← 3 ; 4) ; ((ዝርዝር አዲስ) ነገር:(ተከታታይ ← 3 ; 4) ቦታ:‘bar’, ነገር:1 ቦታ:‘foo’)) ቦታ:‘nested’, ነገር:አይ ቦታ:‘legend’, ነገር:27 ቦታ:‘age’, ነገር:‘Jack’ ቦታ:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld