There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Yalan
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Boş meters long.
Luckily, this day, there are Boş wasps in the garden.
The dog named Boş sleeps under the tree.
a\"bb\"ccc\"
(Siyahı yeni) obyekt:((Siyahı yeni) obyekt:Boş yer:‘dog’, obyekt:Boş yer:‘insects’, obyekt:((Siyahı yeni) obyekt:15 yer:‘length’, obyekt:8 yer:‘width’) yer:‘size’, obyekt:(Seriya ← ‘tulips’ ; ‘roses’ ; ‘lillies’) yer:‘flower’, obyekt:Yalan yer:‘shed’, obyekt:Doğru yer:‘pool’, obyekt:2 yer:‘chairs’) yer:‘garden’
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}