There are 2 chairs in the sunny garden.
A rubber duck swims in the pool.
Is there a shed in the garden? Well.. Жок
In the garden you smell the fragrance of tulips and roses and lillies.
The garden is Боштук meters long.
Luckily, this day, there are Боштук wasps in the garden.
The dog named Боштук sleeps under the tree.
a\"bb\"ccc\"
(карта жаңы) койду:((карта жаңы) койду:Боштук эле:['dog'], койду:Боштук эле:['insects'], койду:((карта жаңы) койду:15 эле:['length'], койду:8 эле:['width']) эле:['size'], койду:(тизме ← ['tulips'] ; ['roses'] ; ['lillies']) эле:['flower'], койду:Жок эле:['shed'], койду:Oоба эле:['pool'], койду:2 эле:['chairs']) эле:['garden']
{"garden":{"dog":null, "insects":null, "size":{"length":15, "width":8}, "flower":["tulips","roses","lillies"], "shed":false, "pool":true, "chairs":2}}