(карта жаңы) койду:‘a"b’ эле:‘test’
Invalid JSON.
(карта жаңы) койду:(тизме ← 1 ; 2 ; (тизме ← 3 ; 4) ; ((карта жаңы) койду:(тизме ← 3 ; 4) эле:‘bar’, койду:1 эле:‘foo’)) эле:‘nested’, койду:Жок эле:‘legend’, койду:27 эле:‘age’, койду:‘Jack’ эле:‘name’
a	b
{"test":"a\t\tb"}
{"test":"a\nb"}
{"test":"a\"b"}
{"test":"a\b"}
______________________Escape
hello	world
a\"b
\"hello world\"
hello\two\nrld
hello\two\nrld
hello\t\two\n\nrld